### ISSUE TITLE
Final review for Compound Schema documents

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/json-schema-spec#1032]
I never got around to a proper review of this when it was a PR, so I'm trying to get it in before we release the next draft.

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L1856-L1862
> Bundling is done in such a way that
> all URIs (used for referencing) in the base document and any referenced/embedded
> documents do not require altering.

This constraint is the cornerstone of the rules for bundlers need to follow. Therefore, I recommend formalizing this statement a bit more as "Bundling SHOULD be done ...".

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L1863-L1867
> Each embedded JSON Schema Resource MUST identify itself with an absolute URI using the "$id" keyword,

I can't tell if this statement is wrong, misleading, or over prescriptive. An `$id` can be relative in an embedded schema. In that case the effective URI for embedded schema is the effective URI of the `$id` resolved against the effective URI of the parent schema. If this statement is saying that you shouldn't use a relative URI when _bundling_ (and it's ok elsewhere), then I'd say this is overly prescriptive. No functionality is lost by using relative URIs, so MUST is far too strict. I think RECOMMENDED is fine. I'd just remove the "with an absolute URI" part and let the `$id` section of the spec describe what a valid `$id` can be.

You could even leave out this whole paragraph. It's just explicitly stating a consequence of that cornerstone constraint from before.

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L1868-L1875
> When the Schema Resource referenced by a by-reference applicator is bundled, the Schema Resource
> MUST be located as a value of a "$defs" object at the containing schema's root.

MUST is far too strong. This should be the RECOMMENDED way to bundle schemas. As long as you don't break that cornerstone constraint, implementers should be free to bundle however they want.

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L1876-L1885

Again this is just explicitly stating a consequence of the cornerstone constraint. It might be better to move this to the other place you're spelling out consequences of the cornerstone constraint.

Typo: "Bundled Schema Resource MUST NOT" => "Schema Resources MUST NOT"

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L1893-L1898
> If multiple schema resources are present in a single document, then
> schema resources which do not have a "$schema" keyword in their root
> schema object MUST be processed as if "$schema" were present with the
> same value as for the immediately enclosing resource.

If there are nested embedded schemas, the immediately enclosing resource might not have a `$schema` either. This should be, "**nearest** enclosing resource". Or, leave the `$schema` keyword out of it and reference the dialect of the immediately enclosing resource instead.

**Comment by Relequestual** [comment]
I agree with you on most points here, and I'll form a PR. But one I'm not convinced.

In terms of the first paragraph, I wanted to JUST define what bundling WAS, and then later define the constraints.
You're right in that this can be better phrased. I'll work something into the PR to try and resolve this issue.

---

> https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L1868-L1875
> 
>     When the Schema Resource referenced by a by-reference applicator is bundled, the Schema Resource
>     MUST be located as a value of a "$defs" object at the containing schema's root.
> 
> MUST is far too strong. This should be the RECOMMENDED way to bundle schemas. As long as you don't break that cornerstone constraint, implementers should be free to bundle however they want.

The reason for this clause was to bundle schemas in a predictable way, so different tooling should create the same bundled schema (making it testable with a specifically defined result).

If this was only RECOMMENDED, not only would this not be testable with a single test suite, but bundlers may create their own new keyword to place subschemas in, and then we get into the whole discussion over if you can reference subschemas in unknown keyword locations (and I'd rather just avoid that, because we already HAVE a place to put them).

> As long as you don't break that cornerstone constraint, implementers should be free to bundle however they want.

How else might an implementation do this? If they decide to embed a schema resource in a location which is not as a value of `$defs`, and then reference it, the resource won't be validated as a schema by general tooling, because it doesn't know that value should be a schema.

**Comment by Relequestual** [comment]
> This constraint is the cornerstone of the rules for bundlers need to follow. Therefore, I recommend formalizing this statement a bit more as "Bundling SHOULD be done ...".

WHy only SHOULD? Why not MUST? Have you got a use case in mind where you would not want to do this?

One of the goals of the bundling process being defined is to LOCK DOWN the approach and results to be consistent across implementations, as currently there are a few "bundlers" which are widely used which don't work right with edge cases.

It's true that this part of the spec is maybe a little verbose, but it is deliberately so in order to be explicit about situations to which otherwise people might not feel the rules apply.

**Comment by Relequestual** [comment]
In terms of testability, you could legitimately argue that you could test the resulting output of validation, but I would anticipate bundler libraries to be on their own, and tests for them would be nice.

**Comment by jdesrosiers** [comment]
> The reason for this clause was to bundle schemas in a predictable way, so different tooling should create the same bundled schema

The important thing isn't that they use the same mechanism. The important thing is that you get the same behavior. If there's another way to get the same behavior with a different mechanism, then that should be allowed. What if I'm building a bundler for a custom dialect that has a keyword specifically for embedded schemas. If the bundler is only designed for that dialect, then why not allow it.

> bundlers may create their own new keyword to place subschemas in

The consequences of using an undefined keyword are already covered in the spec. We shouldn't need a MUST here to keep bundler implementers from doing that. If we are that concerned about it, we can mention here not to use undefined keywords. We don't need to forbid all other ways of bundling in case someone comes up with something clever that we haven't thought of.

> WHy only SHOULD? Why not MUST? Have you got a use case in mind where you would not want to do this?

I don't have anything in mind, I was just being conservative. Maybe someone is building a bundler for a specific domain where the output is never used. In that case, why not allow references to be rewritten.

**Comment by Relequestual** [comment]
I'm always willing to be convinced, and in this case, I am.
I'll work on a further PR.

**Comment by Relequestual** [comment]
Follow up PR posted.
If you approve, can we close this issue off when it merges?
