### ISSUE TITLE
Question about behaviour of $ref in a sub-schema with an $id

### ISSUE THREAD

**Issue by jviotti** [json-schema-org/json-schema-spec#1052]
Hey there! Excuses if this has been discussed somewhere else, but I couldn't find an answer in the official test suite.

My doubt is whether a `$ref` pointing at the root of the document (i.e. `#`) is evaluated against the absolute root the document or the root of the current schema within the document. If we have a schema that declares a top level `$id`, and a definition which also contains its own `$id`, does the `$ref: #` reference point at the outer or at the inner schema?

For example:

```json
"$id": "foo",
"$defs": {
    "myobject": {
      "$id": "bar",
      "anyOf": [
        { "type": "string" },
        {
          "type": "object",
          "properties": {
            "foo": { "$ref": "#" }
          }
        }
      ]
    }
},
"anyOf": [
  { "type": "number" },
  { "$ref": "#/$defs/myobject" }
]
```

Does that `$ref: #` evaluate to `foo` or `bar`? Should the following object match?

```json
{ "foo": { "foo": 1 } }
```

**Comment by karenetheridge** [comment]
This is the relevant section of the specification: https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2

The canonical URI at the position of that `$ref` is "bar#/anyOf/1/properties/foo", so that's the base URI used for resolving the $ref, so the result is "bar#". Consequently, your data will not validate, because `1` is neither a string nor an object.

**Comment by jviotti** [comment]
That makes sense, thanks a lot for the clarifications!
