### ISSUE TITLE
Add nullable property to indicate a type can be null

### ISSUE THREAD

**Issue by santialbo** [json-schema-org/json-schema-spec#1067]
### Current situation
Nullable types are very common in JSON world.
In order to make a type nullable either you have to add `"null"` to the types array or use `oneOf`
```json
{ "type": ["string", "null"] }
```
```json
{ "oneOf": [ { "type": "string" }, { "type": "null" } ] }
```
### Rationale
I believe this approach of making a type nullable is not very intuitive <sup>1</sup>.

At least one other specification (OpenAPI) supports an extension of the JSON schema spec that includes the `nullable` property<sup>2</sup>.

I suggest adding this `nullable: boolean` property to the JSON schema spec as a more intuitive and less verbose way of making types nullable.

<sup>1</sup> https://stackoverflow.com/search?q=json+schema+nullable
<sup>2</sup> https://swagger.io/specification/#fixed-fields-20

**Comment by santialbo** [comment]
Ignore this, nullable has been removed from the upcoming Open API spec
https://github.com/OAI/OpenAPI-Specification/pull/2246

**Comment by Relequestual** [comment]
@santialbo It might be worth noting that OAS didn't just remove nullable, but they will be fully moving over to supporting JSON Schema draft 2020-12 rather than having a subset superset of a rather outdated version of JSON Schema.

We've been working closely with them for at least the past year (probably more) to make it happen.

I'm personally really proud of what our team has achieved! =]

**Comment by santialbo** [comment]
Thanks for the heads up @Relequestual 😄
