### ISSUE TITLE
License format

### ISSUE THREAD

**Issue by brettz9** [json-schema-org/json-schema-spec#1086]
Any interest to add a `license` `format`, e.g., to allow for a [SPDX identifier](https://spdx.org/licenses/) or SPDX expression (like `(MIT OR GPL-3.0)`) along with a means to indicate general copyright (in npm, as "UNLICENSED") and a means to indicate a file or URL path.

**Comment by gregsdennis** [comment]
I'm not sure: are you asking for this functionality as a new keyword?  If so, maybe this belongs in the vocabularies repo.

**Comment by brettz9** [comment]
No, just a value for `format`.

**Comment by gregsdennis** [comment]
We're steering clear of expanding `format` as it's really only caused problems.  That said, you're welcome to create a new vocabulary to add new values.

**Comment by brettz9** [comment]
Has it only caused problems because it doesn't allow multiple values? Or interoperability? Somewhere I can read about this?

**Comment by gregsdennis** [comment]
In general, having one keyword perform multiple kinds of validations is a headache for implementors because it's hard to do.  So they've pushed for looser requirements.  In addition, each implementation has a different level of support for the each of the formats, so interoperability (which is very important to us) is less achievable.  It's also a headache for the consumers of the implementations for the same reasons.

Finally, the spec only "requires" (`SHOULD`) that the ones it lists are supported.  This means that implementations are free to support others.  This poses additional problems for cross-implementation compatability.  But some of this is alleviated with the addition of vocabularies which can add new keywords and expand existing ones while giving the implementation a chance to say whether it supports them.

Overall, `format` isn't a great keyword, and we suggest that explicit keywords are created in external vocabularies rather than tacking on to `format`.

**Comment by brettz9** [comment]
Thank you for the very helpful explanation..
