### ISSUE TITLE
Regarding uniqueItems error interpretation

### ISSUE THREAD

**Issue by nuno-andre** [json-schema-org/json-schema-spec#1099]
JSON Schema specs define an array as _[an ordered sequence of zero or more values](https://tools.ietf.org/html/rfc8259#section-1)_ and its instance equality as _[both are arrays and have an equal value item-for-item](http://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.4.2.2)_ but, AFAIK, do not state which mathematical object corresponds to this type and therefore neither its concept of multiplicity.

So, for instance, in a `uniqueItems` validation against `[1, 1, 2, 2, 2, 3]`, how many errors should we say have occurred?

- **_Two errors_**: `1` and `2` are not unique.
- **_Three errors_**: the second `1`, the second `2`, and the third `2` are repeated elements.
- **_Five errors_**: `{1, 1, 2, 2, 2}`.

**Comment by gregsdennis** [comment]
I think a single output unit would suffice here.  It's the keyword that failed to validate, so it makes sense to only include a single unit for the keyword.

---

Bearing that in mind, [#973 is considering](https://github.com/json-schema-org/json-schema-spec/issues/973#issuecomment-768002201) adding an instance-based structure (instead of a schema-based structure) as a possible output format.  If this is used, it _may_ make sense to include each violation.  This hasn't been hashed out yet though.

**Comment by nuno-andre** [comment]
Yes, I was not precise enough. I was assuming one validation error, the question was about the need to identify the individual errors in _verbose_ or _detailed_ outputs. Luckily, both questions were solved :)

I see that @karenetheridge's implementation adopts the third option, which is consistent with the definition of an array as an indexed set and also probably the most robust approach.

I am going to close this issue and subscribe to #973 to be aware of upcoming changes.

Thank you all for this answer and for all the others, this repo has become my JSON-Schema Bible ;)
