### ISSUE TITLE
Handling of `"$dynamicRef"`s

### ISSUE THREAD

**Issue by watuwo** [json-schema-org/json-schema-spec#1106]
`"$dynamicRef"` works like `"$ref"` (from the draft 2020-12: "Otherwise, its behavior is identical to `"$ref"`") under conditions only known at evaluation time (from the draft: "only [...] resolvable in the process of evaluating the schema with an instance").

How is bundling (section 9.3.1) supposed to work? Can we determine in general whether a `"$dynamicRef"` is a "references [...] to an external Schema Resource"? We could always try to treat `"$dynamicRef"` like `"$ref"` and just ignore cases where no target is available?

What is the suggested behavior of a validator if a `"$dynamicRef"` can not be dereferenced? Should it produce a result analogous to the result of an assertion failure (if yes, can this be used with `"$if"`, `"$not"`, ...)? Should it abort (if yes, aren't there 3 results of validation: "valid", "invalid" and "unsuitableSchema")?

Can a set of JSON Schemas always be classified as either well-defined or not-well-defined (e.g. when the user specifies the Schema)?

Is the following true? If `{"$id": "https://example1.com", "$dynamicRef": "https://example2.com#foo"}` occurs anywhere where a Schema is expected, one can use this Schema (alone) to validate the input / instance root (with a dynamic scope only containing the Schema named `"https://example1.com"`; from the draft: "The outermost dynamic scope is the schema object at which processing begins, even if it is not a schema resource root"). This will always fail (in some way) if no schema named `"$https://example2.com#foo"` has been made available. Such a failure can always be provoked unless `"$dynamicRef"` has an adjacent `"$dynamicAnchor"` or the `"$dynamicRef"` URI can be statically dereferenced.

**Comment by jdesrosiers** [comment]
> `"$dynamicRef"` works like `"$ref"` [...] under conditions only known at evaluation time

Although this is technically true, the only time a `$dynamicRef` behaves like a `$ref` and nothing more is if `$dynamicRef` is not used the way it was intended to be used. It's not a normal case and not a behavior you should use on purpose. If you have a case were a `$dynamicRef` would behave exactly like a `$ref` and no more, then you should be using a `$ref` instead.

> How is bundling (section 9.3.1) supposed to work?

There are no special considerations for `$dynamicRef` when bundling. It works the same as it does in an unbundled schema.

> Can we determine in general whether a `"$dynamicRef"` is a "references [...] to an external Schema Resource"?

No. The dynamic context will be dependent on the instance. It's possible for a `$dynamicRef` to resolve locally in some cases and externally in others.

> What is the suggested behavior of a validator if a `"$dynamicRef"` can not be dereferenced?

Same as if a `$ref` can't be dereferenced. I'd throw something like "Error: Schema not found".

> Should it produce a result analogous to the result of an assertion failure [...]?

No

> Should it abort (if yes, aren't there 3 results of validation: "valid", "invalid" and "unsuitableSchema")?

Yes. As will most code, exceptions are possible.

> Can a set of JSON Schemas always be classified as either well-defined or not-well-defined (e.g. when the user specifies the Schema)?

That depends on how you define "well-defined". I assume that in this case you mean that you can know statically (without an instance) whether all references will always resolve to a valid schema. Yes, you can.

> Is the following true? ...

No. The `$dynamicRef` in that schema will first resolve to `https://example2.com#foo`. Then dynamic resolution will be attempted using that schema as a starting point. In this case, `https://example1.com` does not participate in dynamic scope resolution. `https://example2.com` is the schema that must have a `$dynamicAnchor`. If it does, dynamic scope resolution can look for the outermost schema in the dynamic context that has a matching `$dynamicAnchor`.

I feel like some of these answers are not very helpful. If you have further questions, please ask. Keep in mind that questions with specific examples are best because we can walk through how the example should evaluate.

**Comment by watuwo** [comment]
Actually you helped me a lot. Now I understand that we have to do this (conceptually):

1. We first have to check whether the resolved `"$dynamicRef"` URI is associated to a Schema in the static "Schema Pool" (set of available Schemas) through a fragment-matching `"$dynamicRef"`. We have to do a lookup in the static Schema definitions (or remember a URI from their loading), not the dynamic context/scope directly.
2. Only if there is such an association we check the dynamic context/scope.

I had misunderstood this section: "If the initially resolved starting point URI includes a fragment that was created by the `"$dynamicAnchor"` keyword ...". I thought we had to look for the fragment in the dynamic scope directly (directly to step 2). I was unaware that there was the static check (step 1) first. Now I understand that "created by a `"$dynamicAnchor"`" refers to the creation of the URI during loading of the Schema.

Should this interpretation now be right, then I would be very happy.

**Comment by jdesrosiers** [comment]
Yep, I think you got it.

**Comment by watuwo** [comment]
Typically a schema contains many subschemas (from applicator keywords and `"$defs"`). Which of these schemas can be used to validate the instance data directly (validation not triggered by applicator keyword)?

If any of the subschemas could be used to validate the instance data directly, wouldn't the `"$dynamicRef"`s often point nowhere (e.g. if `{ "$dynamicRef": "#meta" }` from inside "https://json-schema.org/draft/2020-12/meta/core" is used directly to validate some instance data)?

**Comment by jdesrosiers** [comment]
Yes, evaluation of a schema could from any sub-schema and that could result in a `$dynamicRef` not being resolvable. Such things would need to be taken into account when choosing to use that keyword.
