### ISSUE TITLE
Add Semver support as built-in type

### ISSUE THREAD

**Issue by vilherda** [json-schema-org/json-schema-spec#1108]
Hello,

In the same way as there is support to date and time types, it will be so useful to add support to a new type to represent data on fields declared as "semver", by example.

I supose that "everyone" knows about, but just in case, here is the URL of the standard:

- <https://semver.org/>

Regards

**Comment by handrews** [comment]
This is the sort of keyword that is best handled through an extension vocabulary (see the `$vocabulary` documentation in the spec).  We are not adding more to `format` (it should be replaced by vocabularies, although we won't officially deprecate it unless/until replacements are available and widely accepted).

**Comment by jamesodhunt** [comment]
@handrews - Can you explain how that would work? Is the intention for the JSON Schema standards group to provide standard vocabularies for the existing `date`, `date-time`, `email`? If so, do you think the standards group would consider adding `semver` to that standard set of vocabs? For good reason semver has essentially become the _de facto_ versioning scheme in use today so it would be great to be able to validate schemas using such versions )without everyone having to reinvent the pattern matching for semver).

On a related topic, I wonder, if that were to happen, whether the JSON schema itself would move to semver rather than just a version encoded as a date? :wink:

**Comment by gregsdennis** [comment]
An alternative would be to use a `pattern` keyword with the regular expression `^[0-9]+\.[0-9]+\.[0-9]+$` (or `^[0-9]+\.[0-9]+\.[0-9]+(-.)?$` to support prerelease versions).

**Comment by gregsdennis** [comment]
> I think those alone are reason enough to consider inclusion in the JSON schema spec as we really don't want them to be proliferated too much!

So create a new schema:

```json
{
  "$id": "https://myserver.dev/schemas/semver",
  "$schema": "<pick a draft>",
  "type": "string",
  "anyOf": [
    {"pattern": "<regex 1>"},
    {"pattern": "<regex 2>"}
  ]
}
```

and store it somewhere it can be accessed publicly.  Now you can `$ref` to it whenever you want, and so can I.

My point is that `pattern` sorts out your problem without having to define a new format or create a new vocabulary, which you seem averse to.

Regarding JSON Schema version, no, semver is not on the table at this time.  We've discussed it and decided that's not the route we want to take.

**Comment by Relequestual** [comment]
> @jamesodhunt: On a related topic, I wonder, if that were to happen, whether the JSON schema itself would move to semver rather than just a version encoded as a date? 😉

No. Semver doesn't actually make much sense for specifications IMHO. It sends the wrong message.
If we did, we would still be pre 1.0.0 anyway, so it would be of little use.

**Comment by Relequestual** [comment]
Closing this in favour of, @vilherda if you'd like to chat more on your options, feel free to reach out on our slack server. Link on the main site.
