### ISSUE TITLE
Schema extension makes validation effectively useless

### ISSUE THREAD

**Issue by ceving** [json-schema-org/json-schema-spec#1116]
### Reference

Quote from the draft: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-6.5

> Additional schema keywords and schema vocabularies MAY be defined by any entity.

### Problem

This has a catastrophic effect on the validation, because this makes it impossible to distinguish between an *invalid* schema and an *extended* schema.

This is a valid schema:

    {"type": "integer"}

And most people would consider this to be an *invalid* schema:

    {"typ": "integer"}

But it is not. Instead it is an *extended* schema.

### Example

I use the PostgreSQL extension [is_jsonb_valid](https://github.com/furstenheim/is_jsonb_valid) in this example.

~~~
select
  "value",
  "schema",
  is_jsonb_valid ("schema"::jsonb, "value"::jsonb) as "validation"
from
  (values ('"foo"'), ('1'), ('null'), ('{}'), ('[]')) as "values"("value"),
  (values ('{"type":"integer"}'), ('{"typ":"integer"}')) as "schemas"("schema");
~~~

This gives the following result.

 value |       schema       | validation 
-------|--------------------|------------
 "foo" | {"type":"integer"} | false
 "foo" | {"typ":"integer"}  | true
 1     | {"type":"integer"} | true
 1     | {"typ":"integer"}  | true
 null  | {"type":"integer"} | false
 null  | {"typ":"integer"}  | true
 {}    | {"type":"integer"} | false
 {}    | {"typ":"integer"}  | true
 []    | {"type":"integer"} | false
 []    | {"typ":"integer"}  | true

As you can see the validation with the *invalid* schema succeeds always.

### Conclusion

It is definitely the wrong default for a validation to succeed, if the schema is invalid. But section 6.5 from the mentioned draft makes it impossible to recognize, that the schema is invalid. If it is not possible to check, if a particular schema is invalid, the hole validation against such a schema makes no sense.

### Appendix
I hope NASA will never use the current JSON schema validation.

*Malory:* The sensor validation succeeded.
*Alice:* But I still think there is something strange with this rocket.
*Bob:* Did you use the right schema?
*Malory:* Maybe I used [some SO answers](https://api.stackexchange.com/2.3/answers?order=desc&sort=activity&site=stackoverflow).
*Bob:* Whatever! Your default is to fire the guys into the sky.

**Comment by gregsdennis** [comment]
> And most people would consider this to be an invalid schema:
> 
> ```
> {"typ": "integer"}
> ```

Where are you getting "most people"?

`typ` is not a JSON Schema keyword.  JSON Schema has always maintained that unknown keywords are to be ignored.  Thus, for the purpose of validation, `{"typ":"integer"}` is equivalent to `{}`, which validates _all_ values.  This is due to the nature of JSON Schema being a _constraints_ system.  No keywords - no constraints.

The use of `typ` instead of `type` in your examples is realistically merely a typo.  I would expect someone to do testing on a schema (and the validator they're using) that they write before putting it into production.

Note that the key difference between an unknown keyword (possible extension) and a known keyword used incorrectly (invalid) is that an invalid schema won't pass validation by its meta-schema.

---

Regarding extension, draft 2019-09 (the previous draft) defined the ideas of vocabularies.  This is the only extension mechanism that has been defined by JSON Schema (and TBH, we're still working it out a bit).  It has built into it a system for verifying that extensions (vocabularies) should be understood by the validator or else the validator MUST refuse to process the schema.

That extension you linked to claims to operate on draft 4, which is _very_ old.

**Comment by Relequestual** [comment]
I totally understand your frustration. When I typo something and spend hours looking for the problem, it hurts when I find it. Why is this allowed? Why isn't the tooling better?

It once took me 3 hours to find a semicolon on the end of a line which had an if statment. The code was syntactically valid, but logically flawed. We didn't have Java linting tools made avilable to us back then.

It's totally possible, and some very popular libraries already do, to lint your schemas for unknown keywords.
You are able to amend your meta-schema to prevent additional keywords.

However, many non-validation tooling takes advantage of this clause in the spec to add keywords which are related to a specific contexts beyond validation. And, is before an extensibility mechanism was formed.

Many validation libraries also allow users to add their own keywords to extend functionality.

What would you say to all those additional use cases?

**Comment by Relequestual** [comment]
> I hope NASA will never use the current JSON schema validation.

@ceving Please watch your tone. We currently subscribe to the Conduct expectations laid out in RFC7154.

> participants extend respect and courtesy to their colleagues at all times.

If you expect something to come of this issue, passive agressive statements aren't the way to make it happen.

**Comment by ceving** [comment]
> It once took me 3 hours to find a semicolon on the end of a line which had an if statment. The code was syntactically valid, but logically flawed.

The problem is neither that errors exists nor that it takes long to find them. The problem is the wrong default in case of an error!

- Maybe you remember C: `if ( (fd = open (pathname, flags)) < 0) exit (1);` The default in case of an error is: better do nothing.
- A police officer asks you to show him your ID card. You give him your Open Water Diver certificate. Do you think he will accept it?
- You validation a XML file with a XML file not being a XML schema. Will this work?
- You ask for an Iptables recommendation. People will tell you the second most important is: [set the default policy do drop](https://www.thegeekstuff.com/2011/06/iptables-rules-examples/).

Whenever validation happens the default is always **NO** and never **YES**.

But there is one exception: JSON schema validation. Here the default is YES. This is nothing more than a security disaster.

**Comment by ceving** [comment]
> > I hope NASA will never use the current JSON schema validation.
> 
> @ceving Please watch your tone. We currently subscribe to the Conduct expectations laid out in RFC7154.
> 
> > participants extend respect and courtesy to their colleagues at all times.
> 
> If you expect something to come of this issue, passive agressive statements aren't the way to make it happen.

1. I have chosen the example to make clear: Wrong defaults can kill people!
2. And beyond doubt killing a person is the least respectful way to treat a person.
3. This leads to the question: Does the choosen default extend respect to all persons at all times?

**Comment by Relequestual** [comment]
>     1. I have chosen the example to make clear: Wrong defaults can kill people!

Multiple people individually approached me to moderate a potential CoC issue. Please don't make light of it.
We haven't interacted with you before, and your tone was considered disrespectful and uncourteous.

---

Moving on, if you'd like to re-raise this issue with a more appropriate tone, it might be something we can discuss.

It's been a contentious issue for a long time, mainly because of the lack of defined extensibility.
Now that we have defined extensiblity, it might be something we can look into.

However, people using versions prior to if we change that, will still have the same issue.
A linter could help solve that, but we gotta build it.

Are you up for helping?
(Apologising for your tone, even if a simple misunderstanding, would go a long way to making friends =] )

**Comment by karenetheridge** [comment]
You can validate the schema against its metaschema. You can write your own metaschema that declares all unknown keywords are invalid, by extending the main metaschema and adding `"unevaluatedProperties": false`. I've actually done so in my $work's metaschemas, for exactly the reason you describe -- if there is a typo in a schema property I want to know about it rather than it being silently ignored.

It's an easy solution and it's one that "unevaluatedProperties" was explicitly designed for.
