### ISSUE TITLE
$ref processing with adjacent keywords

### ISSUE THREAD

**Issue by paul-f** [json-schema-org/json-schema-spec#1122]
Regarding $ref processing, CREF5 in section 8.2.3.1 says:

"Note that this definition of how the results are determined means that other keywords can appear alongside of "$ref" in the same schema object."

In other words, this is legal:
`{
    $ref: "other.json",
    required: {"name"]
}`

If the referenced schema "other.json" also contains "required", which value has precedence? Also, what happens if "other.json" is a boolean schema (e.g. false)?

**Comment by Fannon** [comment]
If I may add a question here: If there is no precedence, we'll get undefined behavior if this feature is used. So if some libraries decide to interpret it that way or another, we'll get inconsistencies.

Maybe I just missed something, but in [JSON Schema 2020-12](https://json-schema.org/draft/2020-12/json-schema-core.html#ref) this was started to be allowed:

> Allow keywords adjacent to "$ref"

And [here] you can see actually a nice example of why this is really useful. It allows you for example to change defaults or add description which is more specific to the place where the $ref was embedded. This is also the use case that I've had frequently.

```jsonc
{
               "title": "Feature B",
               "properties": {
                   "enabled": {
                       "description": "If set to null, Feature B
                                       inherits the enabled
                                       value from Feature A",
                       "$ref": "#/$defs/enabledToggle"
                   }
               }
           }
```

Now if it's undefined which description wins, you can't really rely on this feature that the ecosystem understands it like you assume. What I assume: If I define adjacent properties to $ref, they take predecence so I can be more specific. If there is a conflict, the local / adjacent properties overwrite the properties from the referenced object.

**Comment by Fannon** [comment]
@handrews Thanks for the quick reply!

Ok, I get that there may be different use cases with different opinions. But isn't this something you could then at least describe what was the intention? 

I see the problem with the JSON Schema ecosystem. If one tool (let's say SwaggerUI) chooses one approach and another tool chooses the other, the same OpenAPI file will be interpreted differently. Actually, this will now likely depend on what $ref dereferencing library you or the tool uses? If I now want to write a JSON Schema that works for both tools, it will not work / will lead to different outcomes. Now I need to postprocess / prepare for each tool differently. 

But I get that this is a difficult problem. I'm biased here, because I only had use cases so far that would prefer one way of doing this. I get your point that this is not always the case. But still, I think keeping this open and flexible does come with a cost of ecosystem consensus.

**Comment by jdesrosiers** [comment]
@Fannon, I'm going to chime in here because I don't think the core misunderstanding was addressed.

> If there is no precedence, we'll get undefined behavior if this feature is used. So if some libraries decide to interpret it that way or another, we'll get inconsistencies.

Annotations like `description` are a special case, so let's set that aside for a moment and consider the original example.

```json
{
  "$id": "other.json",
  "required": ["age"]
}
```

```json
{
  "$id": "main.json",
  "$ref": "other.json",
  "required": {"name"]
}
```

Here, "main.json" asserts that "name" is required, but it also references "other.json" which says "age" is required. So, in "main.json" is "name" required, or is "age" required? They both are. There's no precedence because there is no conflict. Both assertions apply. Libraries don't have to choose. Let's inline the reference to help see what's happening.

```json
{
  "$id": "main.json",
  "$ref": {
    "$id": "other.json",
    "required": ["age"]
  },
  "required": {"name"]
}
```

That's not valid syntax for `$ref`, but that's how it's evaluated. Converting this to valid syntax, it would look like this.

```json
{
  "$id": "main.json",
  "allOf": [{
    "$id": "other.json",
    "required": ["age"]
  }],
  "required": {"name"]
}
```

Both `required` assertions are still there and their assertions are both applied.

Going back to your example, `description` works the same way. The library doesn't choose which `description` to use, both `descriptions` describe the value. Hopefully that context helps make @handrews's explanation make more sense. A JSON Schema implementation would return both descriptions as annotations. From there, it's not defined by JSON Schema how an application uses those annotations. The application might chose one over the other, or concatenate them, or whatever else it want's to do.

**Comment by Fannon** [comment]
Thanks for the detailed answers! I think I understand your point and the examples now better.

> Here, "main.json" asserts that "name" is required, but it also references "other.json" which says "age" is required. So, in "main.json" is "name" required, or is "age" required? They both are. 
> There's no precedence because there is no conflict. Both assertions apply. Libraries don't have to choose. Let's inline the reference to help see what's happening.

So in this case, an "allOf" kind of validation is implied, between the object itself and the referenced object?

**Comment by jdesrosiers** [comment]
> So in this case, an "allOf" kind of validation is implied, between the object itself and the referenced object?

Yes, that's correct.

**Comment by Fannon** [comment]
Thanks for the clarifications and the quick and well written responses!

My understanding is now that this is freedom of interpretation is actually desired by JSON Schema and that it's the responsibility for the consumers (specific libraries) or ecosystems (e.g., OpenAPI) to further constraint / define the expected behaviors. 

Are there other parts of the JSON Schema spec where we have a similar situation? Is this responsibility known to the consumers / ecosystems, so they address and define it?

**Comment by jdesrosiers** [comment]
> Are there other parts of the JSON Schema spec where we have a similar situation?

I guess the standard output format is somewhat similar. It's designed for interoperability rather than human consumption. In theory, in order to present validation errors to a user, you would pass the standard output to a library that would convert the output into nice error messages appropriate for the context. Unfortunately, to my knowledge, no one has written such a library yet for the standard output format, but there are a couple for ajv's non-standard output format that illustrate the concept. This one optimizes for use as an API error response, https://www.npmjs.com/package/@apideck/better-ajv-errors. This one optimizes for human consumption, https://www.npmjs.com/package/better-ajv-errors.
