### ISSUE TITLE
Define how contains interacts with unevaluatedProperties

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/json-schema-spec#1135]
We recently (https://github.com/json-schema-org/json-schema-spec/pull/1092) added support for `contains` to apply to objects, but we neglected to define how `contains` interacts with `unevaluatedProperties`. It should be consistent with how `unevaluatedItems` works.

**Example**

```json
{
  "allOf": [
    {
      "type": "object",
      "contains": { "type": "number" }
    }
  ],
  "unevaluatedProperties": { "type": "boolean" }
}
```

```json
{ "a": 1, "b": 2, "c": "NaN" }
```

Given this schema and instance, we should expect properties "a" and "b" to be "evaluated" and "c" to be unevaluated. "c" should be validated against the `unevaluatedProperties` schema and fail because it's not a boolean. However, currently `unevaluatedProperties` is only defined in terms of `properties`, `patternProperties`, `additionalProperties`, and itself, so `contains` doesn't create the relevant annotations and all of the properties will be considered unevaluated.

I'll create a PR soon to bring this in sync with the `unevaluatedItems` behavior.

**Comment by karenetheridge** [comment]
That brings in an inconsistency between `items` and `additionalProperties`. We used to see `additionalItems` and `additionalItems` as more or less analogues of each other, with the main difference being that the "index" of an object is a property name rather than an integer, and items are ordered and properties are not. If the application of `contains` to object properties will negate the application of `additionalProperties` to those properties, shouldn't applying `contains` to array items negate the application of `items` to those items as well?

Does it ever make sense to have `contains` as a sibling keyword to `additionalProperties`?

I wonder if we should re-evaluate the interaction of these keywords at the same time as the consideration of how `unevaluatedProperties` and `unevaluatedItems` interacts with evaluated-but-not-successfully properties/items in https://github.com/json-schema-org/community/discussions/67.

**Comment by pix-a11** [comment]
2021-11-06 11:22 GMT-07:00, Mercado Pago ***@***.***>:
>
>
> [image: MercadoPago]
>
> SELU456395
>
> [image]
> Lupita, detectamos un nuevo ingreso a tu cuenta
>
>
> Fecha
>
> Hoy a las 12:22 hs.
>
> Dispositivo y navegador
>
> Android, Chrome
>
> No reconozco este ingreso
>
> Si fuiste tú, ignora este e-mail.
>
> ¿No estás seguro? Te recomendamos cambiar la clave.
>
> ¿Necesitas ayuda? Contáctanos
>
>
> [image]
