### ISSUE TITLE
Order of schema properties processing

### ISSUE THREAD

**Issue by olegshtch** [json-schema-org/json-schema-spec#1138]
I'm working with `$dynamicAnchor` and found out some unspecified rules.

If I have anchor declared in the external reference then if just place declarations in new schema:

```json
{
...
 "$ref": "external ref",
 "$defs": {
  "def": {
   "$dynamicAnchor": "anchor"
  }
 }
...
```

`$dynamicRef` get attached to anchor from external schema.

I could use `allOf` to reorder processing

```json
{
...
 "allOf": [
   { "$defs": {
   "def": {
    "$dynamicAnchor": "anchor"
   }
  } },
  { "$ref": "external ref" }
 ]
...
```

that way `$dynamicRef` get attached to anchor from this schema so I can conclude `$defs` is processed after `$ref` and recursive tree example from Specification means `$dynamicAnchor` processing before `$ref`.

Is order of schema properties declared somewhere?

**Comment by Relequestual** [comment]
I'm not sure I fully understand what you're trying to express here. Can you provide FULL minimal example please?
You can test multiple files in this sandbox: https://json-schema.hyperjump.io

Regardless of the specific problem you're facing, the ordering of keywords in a file have no impact on execution.
Some keywords must be run before others.

> I could use `allOf` to reorder processing

No, you cannot.

Dynamic anchors are related to the runtime call stack, aka "dynamic scope".

> ...that way $dynamicRef get attached to anchor...

I simply can't tell because you haven't included your full schemas.

How exactly do you think `$defs` is processed? `$defs` on its own has no processing features and surves only as a reserved location which can be reliably referenced. The subschema values of a `$defs` object are only processed as part of evaluation if they are referenced.

**Comment by olegshtch** [comment]
@Relequestual https://github.com/jimblackler/jsonschemafriend

It supports draft2020-12 and passes recent test suites.
