### ISSUE TITLE
Support for adding multiple levels of validation errors

### ISSUE THREAD

**Issue by stevengoossensB** [json-schema-org/json-schema-spec#1377]
As already discussed in #270 , I think there should be functionality to make a distinction between an ERROR (e.g. breaking a build) and a WARNING (something that should be changed in metadata, not blocking problem). 

I would add a key errorLevel, with levels "error", "warning", "deprecated" and add this to the validation errors.

**Comment by gregsdennis** [comment]
Hi, thanks for bringing this back up. It's been a while and revisiting old topics is often useful.

I'm actually the primary member leading the effort for the specified output formats.  You can follow the `output` label to see relevant issues.

I think my [stance](https://github.com/json-schema-org/json-schema-spec/issues/270#issuecomment-401660761) as stated in that issue remains unchanged.  Essentially, feel that "error level" is an application-level concern. Different applications will have different priorities for the errors, and it's their responsibility to interpret what a validation returns.

Also, with the output format that is now specified, applications have much more information available to make that determination than they did when that issue was active.

I don't think the specification has the purview to determine for everyone which errors can be considered warnings or critical.  We just report that something didn't match what was expected and leave interpretation to the consumer.

**Comment by gregsdennis** [comment]
Closing for now as I don't see an action here.  Happy to reopen after further discussion.
