### ISSUE TITLE
equality between properties

### ISSUE THREAD

**Issue by vasile-baluta** [json-schema-org/json-schema-spec#1419]
Hi!

If I have json like this

{
    "property1": "value1",
    "property2": "value1"
}

How will a schema look like that invalidates the json if property1 has same value as property2?

**Comment by jdesrosiers** [comment]
Unfortunately, this is one of the things JSON Schema isn't currently capable of expressing. We would need a new keyword similar to `uniqueItems`, but works on objects instead of arrays.

**Comment by gregsdennis** [comment]
@vasile-baluta are you asking to validate whether _any_ two properties have the same values, or just that `property1` and `property2` need to be different while other properties present in the instance could have any value.

If the first (all unique property values), then what @jdesrosiers said.

If the second (just `property1` needs to be different from `property2`), then there is a solution if you're using .Net.  I've defined a [vocabulary](https://docs.json-everything.net/schema/vocabs/data-2022/) that allows you to reference data from the instance and use it in a validation via a new keyword: `data`.  Other implementations have a variation of this (typically `$data`), but those have other drawbacks.

A schema that would invalidate the instance you posted would be something like this:

```json
{
  "$schema": "https://json-everything.net/meta/data-2022",
  "type": "object",
  "properties": {
    "property1": { "type": "string" },
    "property2": {
      "type": "string",
      "not": {
        "data": {
          "const": "/property1"
        }
      }
    }
  }
}
```

The link to the vocabulary above explains how this works in a bit more detail, but basically, the values of `data` are used to build a subschema.  In this case, we pull the value from `property1` and put it under the `const` keyword.  That gives us a schema that we can use to evaluate the instance.  Since we're using the `not` keyword, the validation result is inverted.

So this says

- `property1` should be a string
- `property2` should be a string
- `property2` should not be whatever `property1` is

**Comment by vasile-baluta** [comment]
Thanks @gregsdennis ! 

I use Python and I solved it using a custom validator but I plan to create a repository at GitHub to show my solution.

BR
