### ISSUE TITLE
Option for parsers to intepret precision of numbers

### ISSUE THREAD

**Issue by awwright** [json-schema-org/json-schema-spec#152]
In some cases, parsers may want to expose the precision of a number in addition to its value -- especially for scientific cases where `1.2e4` is different than `12000.000` - same value, very different precisions.

In this case, we should allow parsers to define "integer" as "any number with a precision of exactly 1" instead of its current definition "any number with a zero fractional part".

This is a bit esoteric, but it is a totally valid use of JSON.

**Comment by Relequestual** [comment]
I'm for further discussing and fleshing out this thought! Seems like a sensible solution to the issue presented.

**Comment by HotelDon** [comment]
I'm a bit confused as to what "having a precision of exactly one" actually means. Mathematical precision, at least as far as I can tell, refers to all the digits in a number, so having a precision of one would include only the numbers 0 through 9.

**Comment by handrews** [comment]
I feel like this is best addressed by a `format`, along the lines of #361 but perhaps something accounting for exponential notation?  These cases do not necessarily need to be solved by the same format value.

**Comment by handrews** [comment]
@awwright I'm pretty sure that since we define JSON Schema over the data model and not over the JSON text, this doesn't work.  Or at least not in any interoperable way, as the mapping of floating-point text to internal representations is not standardized.

We've rejected numerous requests around distinctions that are only present in the JSON text for numeric formats, so I'm going to close this.  @awwright if I missed something please re-open/re-file.

**Comment by awwright** [comment]
This is fine. I haven't come across any use-cases in the... four... years this has been open.
