### ISSUE TITLE
Clarification Needed on the Status and Future Updates of JSON Schema Specification

### ISSUE THREAD

**Issue by VimukthiRajapaksha** [json-schema-org/json-schema-spec#1530]
Hi Team,

It appears that the `draft-bhutton-json-schema-01` specification is marked as "Expired & Archived" on the [datatracker.ietf.org](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01) website. See the attached image for reference:

<img width="318" alt="image" src="https://github.com/json-schema-org/json-schema-spec/assets/23322140/544e0cb5-e6a8-44d0-a3d3-d6420f65517b">

1. Do you have plans to update this specification? If so, could you provide a timeline for the new draft?
2. Alternatively, is there a different specification that will replace the current "JSON Schema" specification?

Any insights or updates on this would be greatly appreciated.

Thank you!

**Comment by gregsdennis** [comment]
Hey @VimukthiRajapaksha.  Thanks for the questions.

The team is currently working towarda new release of the specification, but we've made some organizational (like JSON Schema Org) and process changes since the last time we released, and we want to make sure we've got everything right.  Please see the current [roadmap](https://github.com/orgs/json-schema-org/projects/15/views/1).

Secondly, the existing releases ("drafts") are production-ready releases, and many people and orgs use them as such.  They were only published under the IETF draft system because that was what was available.  We never intended for them to expire, but that's what that publication route requires.  We have republished all of the documents [on our website](https://json-schema.org/specification) just in case they are ever taken from the IETF site.  Future releases will be self-published.

**Comment by jdesrosiers** [comment]
More information can be found in this [blog post](https://json-schema.org/blog/posts/future-of-json-schema)
