### ISSUE TITLE
Wiki is not migrated

### ISSUE THREAD

**Issue by ReactiveRaven** [json-schema-org/json-schema-spec#16]
The contents of the wiki at [json-schema/json-schema/wiki](https://github.com/json-schema/json-schema/wiki) have not been migrated/redirected to their new home [here](https://github.com/json-schema-org/json-schema-spec/wiki).

**Comment by Acubed** [comment]
This might be able to be done with a Git push, I think GitHub keeps the wiki as a (hidden) Git repo somewhere.

**Comment by Relequestual** [comment]
@awwright you're right on that! If you think it will help, I'll look into migrating the wiki, and then how we can redirect people from the old one. Maybe insert something at the top of each file. Assuming I can write to it that is. =/

**Comment by awwright** [comment]
@Relequestual I think I can do that, but I'd like to spend at least a trivial amount of time thinking if we can improve the wiki. I think 90% of the content on it now is either better suited for either the website (getting started and documentation) or the issue tracker (feature proposals)

**Comment by Relequestual** [comment]
Agreed on that!

If you update a wiki page and then delete it, does the creator get notfiied? For items that are migrated to issues, we will need some mechanism for letting people know where their wiki pages have gone.

I still struggle to understand why people were directed to the wiki for making suggestions... =/

**Comment by handrews** [comment]
I'm assuming this stalled as the last comment is several months old.

I have started auditing the spec-related wiki pages alongside the audit of the old repo issues that I already started and posted to the Google group.  I currently do not plan to do anything with wiki pages that are not directly related to advancing the specification work.

My plan, unless someone suggests otherwise, is to go over the wiki pages, the old repo's issues, and the new repo's issues, and distill all of the spec work down into issues on the new repo that can be filed with a summary of all of the past discussions.  At this point, many feature discussions are spread over a wiki page and multiple issues filed against both the old and new repos.  Many initially-different proposals converge on the same set of major proposals.

For letting people know what happens with the wiki, we can just edit the pages and either completely replace their contents with a link to the new issue, or just prominent feature such a link at the top of the page.  There's no problem with editing the old wiki- I just fixed a broken link there right now.

@awwright please let me know if you would like for me to continue with this, either as stated or with a modified approach.

**Comment by awwright** [comment]
@handrews That sounds mostly good, for entries on the old wiki perhaps let's link to the relevant issue here; if any.

We should only create issues for proposals that mesh suitably well with the existing goal of annotating or validating JSON documents. Other goals... we'll have to figure them out based on their merits, I guess.

**Comment by Relequestual** [comment]
To my mind, the core goal of JSON Schema is to enable a systematic and complete means to validate a JSON document.

**Comment by handrews** [comment]
@awwright :  I definitely intend to crosslink every which way that seems remotely useful and not too confusing.

@Relequestual :  I'd also really like to figure out the right way to think about hyper-schema alongside the validation requirements.  But not in this issue :-)

**Comment by handrews** [comment]
@awwright are you able to close issues in the old repo?  Or do we need to try to get the attention of the original filers to close them?

I was going to suggest an alternative of creating some new labels to advertise issue status, but it looks like even if you can create new labels there I can't use them.

**Comment by awwright** [comment]
@ReactiveRaven I think we've sort of settled on trying to move as much as possible into either the issue tracker or the website. Does that solution work for you?

**Comment by awwright** [comment]
I'll close this out for inactivity... If there's any particular things missing from the website or wiki feel free to open an issue in the appropriate tracker.
