### ISSUE TITLE
Rename "id" to "$id"

### ISSUE THREAD

**Issue by JanTvrdik** [json-schema-org/json-schema-spec#20]
https://github.com/json-schema/json-schema/issues/215

**Comment by seagreen** [comment]
This might be a bad idea, but was `$scope` ever considered as well? `id` was a really confusing name to me when I was first learning about JSON schemas.

**Comment by handrews** [comment]
In json-schema/json-schema#215 , @YurySk commented:

> 1. My, reasonably composed, V4 schemas are valid in V5 without a simple change. I can then change a validator to a version with V5 support. Then I do QA, see that the things are working and leave the schemas be (i.e. not even bother with any DevOps stuff related to the schema files).
2. My, reasonably composed, V4 schemas are NOT V5 valid for a number of good reasons. Then I sit down, update them thoughtfully, QA, deploy, etc.
3. same as 2, but with the only incompatibility being '$id'. Do I really need to go though the motions knowing full well "$id" is the only difference?

My response to this is that we should supply an upgrade tool that handles all automatable conversions from one draft to the next.  So far that could include:

* update the value of `$schema`
* convert `id` to `$id`
* convert `exclusive*` boolean keywords to numeric form (proposed in #77 )

I know that it is possible to preserve order while loading, editing, and writing JSON back out in Python's standard JSON library, so this could be done without scrambling everyone's schemas.

This makes the upgrade mechanical- not entirely without risk, but does not require "thoughtful" updates or extensive testing.

**Comment by Relequestual** [comment]
If we or someone made such a tool as you describe @handrews, we should make a fuss about it on the site.

**Comment by Relequestual** [comment]
I'm in favour of this proposal.

**Comment by epoberezkin** [comment]
It's quite easy to make a conversion tool using Ajv and schema with custom keywords ;)
So a special schema will be used to convert schema to the next version. Very meta.
I can make it once the standard is stable.

**Comment by Relequestual** [comment]
Draft 5 is done. I haven't looked at the diffs in details to determin if it was non version forward compatible. I believe @awwright intended draft 5 to mostly be a fix for issues in draft 4

**Comment by handrews** [comment]
> Draft 5 is done. I haven't looked at the diffs in details to determine if it was non version forward compatible.

Validation is compatible.  Hyper-schema is not (previously, `method` in the LDO was explicitly documented to use HTTP methods, but @awwright changed it to be based on "get" vs "post" usage in HTML forms instead, invalidating all `method`s that were set to "PUT", "PATCH", or "DELETE" and adding ambiguity to "GET" and "POST").

**Comment by awwright** [comment]
@handrews "... and certain changes to make the spec compatible with existing standards" is pretty much what the idea was; eventually, the semantics of "method" was slightly tweaked, but backwards-compatible for the most part; four special-case "rel" keywords were dropped, "base" keyword was introduced (I might propose changing that because it's a schema keyword, we might want it to mean something else... I forget what), also in Validation the "uriref" format was introduced; also in Core use of $ref and "id" was restricted

**Comment by handrews** [comment]
There don't seem to be any objections to this in the nearly six months since it was filed, just the suggestion to consider `$scope` instead of `$id`.  As long as we are retaining the identification functionality of the keyword (it sets the schema's identifying URI as well as changing the resolution base), I think we should stick with `$id`.

I have also seen at least one implementation which only supports `$id` and not `id`, so that's some running code to add to the consensus :-)

I think that it would make sense to add support for `$id` and deprecate, but not yet remove `id`.  When we have a good migration story and tool(s) we can then drop `id` from the next draft.

**Comment by seagreen** [comment]
@handrews Sounds good to me. I agree that as long as identification is part of it's functionality `$id` is better than `$scope`.

**Comment by awwright** [comment]
This is a pretty big change so I still need to review implementations and see what sort of impact it would have. Hopefully this means next meta-schema update, but I'm not totally sure.

**Comment by handrews** [comment]
@awwright can you be a little more clear on what needs to be researched?  We can help collect the information if we know what you are looking for.

**Comment by Relequestual** [comment]
Looks like this should be fixed by #154

**Comment by handrews** [comment]
Resolved by #212.
