### ISSUE TITLE
$schema values for published specifications

### ISSUE THREAD

**Issue by joemcintyre** [json-schema-org/json-schema-spec#237]
In the core specification, the list of values for $schema was removed, and the reader is directed to find this value in other documents.
I expected to find this value in each of the validation and hyper-schema specifications, however it was not added to these.
Is my expectation of where to find this value for the published specifications correct? If so, a $schema section with this value should be added to each of these specifications.

**Comment by handrews** [comment]
@joemcintyre The URIs will be updated in the validation and hyper-schema specifications once the new meta-schema (draft-06) is finalized immediately prior to the next publication of those specifications (which will be draft-wright-jsonschema-*-01 because of IETF naming/numbering rules.  Each of those specs has a section called "Meta-Schema" or "Metaschema" (hmm... I should make those consistent).  Those sections currently exist and point to the older draft-04 meta-schemas with a CREF note that they will be updated shortly.

Since this step is already tracked as part of #206 (the "verify that the specification and meta-schema match" step), I'm going to close this issue.
