### ISSUE TITLE
[draft-06 core] critical - contradictions in the section about $id keyword

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#242]
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L349

@awwright @handrews @Relequestual 

Please do not publish it in such shape

I'm going to add explanations a bit later (probably tomorrow morning here).

**Comment by awwright** [comment]
@epoberezkin Anything to elaborate on here?

**Comment by epoberezkin** [comment]
@awwright sorry for the delay.

It is somewhat related to the conversation in #243 

Maybe the problem is my wrong interpretation of the paragraph linked above, but I always think that I can't be the only one confused, so at the very least it could be good to clarify.

The way I read $id section is the following:
a) $id is uri reference
b) $id in root schema should be an absolute URI
c) $id in subschema should start start from # (plus other restrictions)

This interpretation obviously contradicts the examples below.

Also, as I understand that is not the intended meaning, $id in root can be any uri-reference as well as $id in subschemas.

If that is the case I do not understand why the $id for the purpose of naming subschemas should be separately explained, because the way these names are defined they are still uri-references and they still change base URI (by appending or replacing hash fragment).

So it seems to me that we are including in I-D some information about how $id can be used without in any way extending what it can be both syntactically and semantically. @awwright you always say such things should not be part of I-D. And this explanation does not just seem redundant, it looks like we are limiting what $id in subschemas can be and only by looking at examples and combining with the previous sentences you may understand the intended meaning.

@awwright @handrews Can you explain why this "To name subschemas in a JSON Schema document" paragraph is needed at all? From my point of view it achieves nothing but confusion.

Same partially applies to the sentence:

> The root schema of a JSON Schema document SHOULD contain an "$id" keyword with an absolute-URI

Although if you say that $id in root being absolute URI is a recommendation rather than restriction I agree with that - while there is a usage practice where root $id is not absolute URI, it is recommended that it is.

**Comment by handrews** [comment]
@epoberezkin do you still feel this way with the language in PR #245?

**Comment by handrews** [comment]
> If that is the case I do not understand why the $id for the purpose of naming subschemas should be separately explained, because the way these names are defined they are still uri-references and they still change base URI (by appending or replacing hash fragment).

Because we need to define plain name fragment identifiers (fragids) as valid fragids for the `application/schema+json` media type, and explain their use.  Plain name fragids are not automatic things.  A media type has to specify:

* That they are supported at all
* Any restrictions on their syntax
* How you define one to identify a structure within a document

This is done through the `"$id"` syntax.  In PR #245 I add a Fragment Identifiers section based on W3C best practices for media type fragids.  In that section I mention that we support plain name fragids, but refer readers to the `"$id"` section for how they are defined and used.

Without that, the only type of fragids supported would be JSON Pointer fragids.

**Comment by epoberezkin** [comment]
> Without that, the only type of fragids supported would be JSON Pointer fragids.

@handrews Ok, so it essentially tries to say that hash fragment of $id can either be JSON pointer or fragment identifier, but it says that the whole $id should be it. As a side note, by allowing $id to be JSON pointer it allows to shadow the location where this JSON pointer would point... But it's already like this in draft4. Not sure if it should be allowed, but we don't need to change it now.

While this PR clarifies that the hash fragment can contain JSON pointer, it still looks like $id in subschemas can only be hash fragments. I may be missing something, but I don't see where it says (or implies) that $id in subschema can be absolute or relative URI with or without hash fragment.

Also I still don't see anywhere in ID even with PR #245 where it says that hash fragments in URIs in $ref are JSON pointers (#243). I see these:

1. $id defines "URI for the schema", with some limitations.
2. $ref points to "URI of a schema to use"

From the above I see that $ref can only point to the part of the schema that has $id, as nowhere it says that hash fragment in $ref should be interpreted as a location in schema object where the schema itself is located at URI without hash fragment and hash fragment should be interpreted as JSON pointer (apart from examples maybe?).

For example:

```json
{
  "propreties": {
    "foo": { "$ref": "#/definitions/foo" }
  },
  "definitions": {
    "foo": { "type": "string" }
  }
}
```

From where in the I-D document it follows that the above should work? I am not trying to be difficult, I really don't see it, could you please explain (ideally, post the links to the relevant lines in I-D)? I still think that by removing "JSON reference" specification from the I-D we've lost this connection.

**Comment by epoberezkin** [comment]
Actually, by looking at the example above, it's also not clear where it says that `{"$ref": "#"}` points to the current root schema regardless whether it has $id or not, although it can be changed by $id in subschema.

Or where it says that URI in $ref should be resolved relative to the current base URI?

Maybe it is implied, but I am not sure by what. JSON reference spec is [saying it directly](https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html#rfc.section.4).

**Comment by handrews** [comment]
> Ok, so it essentially tries to say that hash fragment of $id can either be JSON pointer or fragment identifier, but it says that the whole $id should be it. 

**IF** you want to define a local identifier, **THEN** you do so by setting "$id" to a plain name fragment URI reference.

**ALSO**, "$id" can be other types of URI references, which change the base.

I don't know how to make this more clear.  It specifically says:

> _**To name subschemas**_ in a JSON Schema document, subschemas can use "$id" to give themselves a document-local identifier.

That means FOR THE PURPOSE OF NAMING THEMSELVES, subschemas can use an "$id" consisting of only a plain name fragment.  It does not restrict the value of "$id" when using "$id" for other purposes.  It just calls out this one specific purpose and explains how it works, **because that is what you have to do to support plain name fragids.**

> As a side note, by allowing $id to be JSON pointer it allows to shadow the location where this JSON pointer would point.

The PR specifically calls out this case and states that the resulting behavior is undefined:

> The effect of defining an "$id" that is appears to be a JSON Pointer that does not match the expected JSON Pointer for that schema is not defined.

In a future draft, we can discuss better resolution mechanisms, but for now this relieves implementations of the burden of detecting and handling this, which is good enough to get draft 6 out the door.

> Also I still don't see anywhere in ID even with PR #245 where it says that hash fragments in URIs in $ref are JSON pointers

Because the value of "$ref" is a URI, and the use of fragments in URIs are defined by the media type of the resource at that URI.  "$ref" URIs refer to `application/schema+json` documents.  That is the media type we are defining.  We define (more clearly in PR #245) that the `application/schema+json` media type supports two fragid syntaxes:  

1.  JSON Pointer (if the fragment matches the JSON Pointer-as-fragment syntax, which is defined including URI encoding in the JSON Pointer RFC)
2.  Plain names (if the fragment does *not* match the JSON Pointer syntax)

This is perfectly in accordance with W3C best practices for fragid specifications for media types.

"$ref" does not and **must not** impose restrictions on the fragments.  That is the role of the target media type.

> it's also not clear where it says that {"$ref": "#"} points to the current root schema regardless whether it has $id or not

If you read the JSON Pointer RFC, you will note that the empty string is a valid JSON Pointer, which points to the root of the JSON document.  As I wrote in PR #245:

> Fragment identifiers matching the JSON Pointer syntax, **_including the empty string_**, MUST be interpreted as JSON Pointer fragment identifiers.

This also makes it much easier to keep track of the current JSON Pointer as you walk through the schema, because "#" is a JSON Pointer (a known location) and not a plain name (a location that only exists if declared by the specific "$id" usage described for the purpose of declaring plain name fragments.

**Comment by epoberezkin** [comment]
@handrews thank you for the comments. I did miss a couple of things.

Maybe it's just me, but I find this approach when instead of explicitly saying something it is implied from some other places, often outside of the document, very confusing. I've read many other RFCs and they are much more explicit, clear and self-sufficient than this document. With this document I often have to guess where everything comes from and how it's all connected...

For example, I don't understand why your sentence above "It does not restrict the value of '$id' when using '$id' for other purposes." can't be part of the document.

But whatever, we can leave it at as it is, with a bit of help people will be able to figure out what we are trying to say with this document.

**Comment by handrews** [comment]
@epoberezkin we can keep working on the language in the next draft.  The goal right now is to get a workable draft 06 out.  Once we've done that, please feel free to submit a PR with language you find more helpful.

There are things that I definitely prefer to leave out for conciseness:

* A five-second skim of the JSON Pointer spec shows that there's a whole section about fragments
* Anyone digging this deep into RFCs should learn about fragments and why they are determined by the target media type and not the scheme or source context.
* I do link clearly to an entire document about fragid best practices.  It's not exactly hidden.
