### ISSUE TITLE
[question] Clarification of "id" behavior in draft-03/04/05

### ISSUE THREAD

**Issue by erayd** [json-schema-org/json-schema-spec#302]
I am working on implementing strict support for each release of the spec from draft-03 onwards, and would like to clarify my understanding of how the `id` keyword is supposed to work, as I am struggling to form a coherent picture from reading the spec documents. My current understanding is as follows:

For draft-05:
 1) When `id` is encountered, it is resolved against the current base, and the current base is changed to reflect the result of that resolution.
 2) In addition, the subschema in which `id` appears should be registered within the implementation against that URI, as per [§8.2.1,p2](https://tools.ietf.org/html/draft-wright-json-schema-00#section-8.2.1).
 3) To clarify, this means that if a subschema in `http://example.com/schema/a` defines an `id` of `http://example.com/schema/b`, then any references to `http://example.com/schema/b` are fulfilled by the subschema in which that `id` occurs, and the actual content at `http://example.com/schema/b` is never fetched.

Are `id` registrations as per (2) applicable only within the schema document in which they occur, or should they also be exposed to other schemas loaded within the validator implementation? For example, if a subschema in `http://example.com/schema/a` defines an `id` of `http://example.com/schema/b`, should a `$ref` (pointing to to `http://example.com/schema/b`) that occurs in `http://example/com/schema/c` resolve to the subschema in `http://example.com/schema/a`? 

Does [§8.2.2](https://tools.ietf.org/html/draft-wright-json-schema-00#section-8.2.2) apply to subschemas, or just to root schemas only?

In the following example, should `"propOne"` be a string, or a number? `"defOne"` has claimed the `"#definitions/defTwo"` URI for itself, but by doing so it overrides `"defTwo"`, which would otherwise be the legitimate target of dereferencing `"#definitions/defTwo"` as a JSON pointer.
```JSON
{
  "definitions": {
    "defOne": {
      "id": "#definitions/defTwo",
      "type": "number"
    },
    "defTwo": {
      "type": "string"
    }
  },
  "properties": {
    "propOne": {
      "$ref": "#definitions/defTwo"
    }
  }
}
```

For draft-04:
 * [§7.2.4](https://tools.ietf.org/html/draft-zyp-json-schema-04#section-7.2.4) seems to indicate that subschemas which provide an `id` are not registered against that URI, unless the `id` cannot be dereferenced as a JSON pointer. This would mean that according to draft-04, in the example above, `"propOne` should be a string.
 * Draft-04 otherwise looks the same as draft-05.

For draft-03:
 * `id` is used to change the resolution base, but is *not* used to register subschemas.

It seems quite likely that some of my assumptions are wrong - I would really appreciate it if somebody could let me know whether my understanding is correct, or if not, where I am misunderstanding the intended behavior. Thanks :-).

**Comment by handrews** [comment]
Hi @erayd, I'll address these from oldest to newest:

#### draft-03

This draft is very old and I'm not aware of any significant system still using it.  I'd be curious about who is using it and why.  Do you know of examples still active in the wild?  It's not clear to me why it's worth the effort to implement this six years after its expiration.

#### draft-04

Pretty much everyone found the whole canonical vs inline distinction confusing, which is why it was dropped.

The short answer is:  all `id`s should result in the schema being registered against the resolved URI.

The long answer is:  with something like `"id": "#foo"`, all of the directives for canonical dereferencing apply: resolve the URI Reference against the current base and associate the resulting URI with the schema.  In _addition_, if an implementation supports inline dereferencing, then the implementation can associate the schema with just plain `"#foo"` and match any references to `"#foo"` in the current file with the same base without doing the canonical resolution.  Which is intended to have the same result as canonical dereferencing but... um... actually I have never understood what the advantage is supposed to be.  It's an optional feature anyway.

#### draft-05

There's no actual draft-05 meta-schema associated with the **draft-wright-json-schema-*-00** specifications, which means there is no way for a schema to indicate that it is using those specs.  As you noted, the behavior is intentionally identical to draft-04 for the Core spec and all but one new `"format"` value of Validation spec.  This is why no new meta-schema was published.

Since **draft-wright-json-schema-*-01** will be out literally any day now (whenever @awwright has a chance to review/accept the last PR and do the actual publication) and _will_ have a draft-06 meta-schema, I would recommend focusing on that and skipping the not-existing-as-a-meta-schema "draft-05".

That said, your draft-05 questions carry over into draft-06, so....

#### draft-06

`'id` was renamed `$id` in draft-06, but otherwise any changes in wording should only clarify the behavior.

> the actual content at http://example.com/schema/b is never fetched.

Technically, you don't have to (and shouldn't assume you will always be able to) actually fetch schemas from URLs.  If you already have the schema identified that way (because of `$id` being set in another file, or because you had that schema pre-loaded somehow), then you'd never even try to fetch that URL.  There might not be anything there, and that's perfectly fine because the `"$id": "http://example.com/schema/a"` declared in http://example.com/schema/a tells you everything you need to know to use http://example.com/schema/b anyway.  So...

> Are id registrations as per (2) applicable only within the schema document in which they occur, or should they also be exposed to other schemas loaded within the validator implementation? 

They should also be exposed to other schemas loaded within the validator implementation.  A URI is a global identifier.  If someone declares two different schemas with the same URI, such as having one actually fetchable at that URI which is different from one identified by that URI elsewhere, well... garbage in, garbage out.

Which brings us to your `"propOne"` example.  The relevant quote from the spec (in what was §8.2.2; now §9.2.2) is:

> When multiple schemas try to identify with the same URI, validators SHOULD raise an error condition.

In your example, you have an actual subschema at `#/definitions/defTwo`, while the schema at `#/definitions/defOne` attempts to use `id` (now `$id`) to identify itself as `#/definitions/defTwo`.  That means two schemas are identifying with that URI, and the result should be an error at schema load time.

Did I miss anything?

**Comment by awwright** [comment]
@erayd I would advise against implementing anything except the latest draft. Old drafts are kept around for historical interest only, otherwise they are replaced in their entirety by newer drafts. If there's a particular need for reverse compatibility, support features as they're used "in the wild" instead: You'll find that different implementations have very different interpretations of exact behavior, and there is no right way to do many things (because of ambiguous language, conflicting requirements, or bad implementations).

Technically there's no such thing as draft-05, it's _very casually_ used to refer to draft-wright-json-schema-00, which clarifies the semantics of the draft-04 meta-schema.

> Are id registrations as per (2) applicable only within the schema document in which they occur

URIs are universal identifiers, they will always mean the same thing regardless of where or what context they appear in. This doesn't mean we will actually have access to that schema, and deciding which schemas are available to which other schemas is up to the implementation. It would probably be least surprising if all known schemas are available to be referenced by any schema.

> Does §8.2.2 apply to subschemas, or just to root schemas only?

That section applies to all schemas. Subschema and root schema are just relationships, there's not a meaningful difference unless one schema is inside another, in which case the parent schema we call the "root schema" and the child we call the "subschema".

> but by doing so it overrides "defTwo", which would otherwise be the legitimate target of dereferencing "#definitions/defTwo" as a JSON pointer.

Note that the JSON Pointer has a leading slash. draft-wright-json-schema-00 doesn't support the case where a fragment in an "id" has a leading slash like `"id": "#/definitions/defTwo"`.

**Comment by erayd** [comment]
Thanks guys - those replies are really helpful, and clear up most of my confusion :-).

One thing I would like to clarify around draft-03 (and only draft-03, I'm aware this is not the case in later drafts) - am I correct in my interpretation that `id` changes the resolution base only, and does *not* provide a URI by which the `id`-containing schema can be addressed? The wording seems to specify the former, but does not mention the latter at all that I could see.

Regarding why I'm supporting draft-03 despite it being ancient - I'm trying to untangle the validation behavior of [an implementation](https://packagist.org/packages/justinrainbow/json-schema) which currently supports a rather permissive superset of draft-03 and draft-04, but is not strictly compliant with either, and adding draft-06 to the mix will only confuse things further. Noting the functionality is already there, and I have to untangle it all *anyway* in order to achieve strict compliance, it seems worth the effort to maintain draft-03 support for the sake of backwards-compatibility, particularly noting that draft-05 says [the following](https://tools.ietf.org/html/draft-wright-json-schema-00#section-6.1):

> JSON Schema implementations SHOULD implement support for current and previous published drafts of JSON Schema vocabularies as deemed reasonable.

**Comment by erayd** [comment]
> Note that the JSON Pointer has a leading slash. draft-wright-json-schema-00 doesn't support the case where a fragment in an `"id"` has a leading slash like `"id": "#/definitions/defTwo"`.

What is the desired behavior when such an `id` value is encountered? Is this one of those _"it's undefined, so whatever the implementation decides to do with it"_ situations, or is there an intended (or at least conventional) way of dealing with these (e.g. change the resolution base, but don't register the uri)?

**Comment by awwright** [comment]
@erayd The spec is unopinionated, and it probably depends on context. If the schema is being designed, or provided by an untrusted third party, it should probably produce a fatal error. If you're merely consuming a well-known schema, produce a warning, or just handle it the best way you can if there's a way to do so unambiguously.

In the wild, you're probably never going to encounter this case. It probably won't hurt anything to treat this as a fatal error.

**Comment by erayd** [comment]
@awwright Yes - thanks :-). Really appreciate the answers you and @handrews have provided here, they have been extremely helpful.

I do have one further question - are `"id"` and `"$ref"` only parsed when they occur in the context of a schema, or are they still parsed even when they occur as a property name? For example, is the schema below valid? If `"id"` is parsed as an identifier, it should be valid, but if `"id"` is just treated as a standard property, then it's not valid, because `"notAnObject"` is not a schema object, and `"properties"` requires its members to all be schemas. As I understand it, `"properties"` itself is an object, but not a schema.

```JSON
{
  "properties": {
    "id": "notAnObject"
  }
}
```

I'm also still waiting on an answer to this:

> One thing I would like to clarify around draft-03 (and only draft-03, I'm aware this is not the case in later drafts) - am I correct in my interpretation that `id` changes the resolution base only, and does *not* provide a URI by which the `id`-containing schema can be addressed? The wording seems to specify the former, but does not mention the latter at all that I could see

**Comment by awwright** [comment]
@erayd `"$id"` `$ref` and family are all schema keywords, they're expected as properties of a schema only.

Except for $ref, in older drafts it was a special construct, but this didn't make much sense, and very few people implemented it in that fashion.

I don't see any reason why a schema shouldn't be addressable by the `"id"` it specifies, in any draft. Older drafts are more ambiguous on this, though.

**Comment by erayd** [comment]
Perfect - thanks heaps :-). :1st_place_medal:

**Comment by chyzwar** [comment]
@handrews I will be working on implementation for draft-06. I would like to understand what type of things can break in new schema versions.

My implementation would like to handle new version of schema easily. What things would not change and what can evolve?

**Comment by awwright** [comment]
@chyzwar The Changelog section in the draft should give you an idea of which sections to focus on. If you're writing a validator, you should try to keep reverse compatibility with existing schemas no matter what.

For hyper-schema specifically there's <https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema-hyperschema-01>.

**Comment by handrews** [comment]
@chyzwar I finally started the equivalent FAQ for core and validation:

https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema%5B-validation%5D-01

It could use more work (also, @awwright please let me know if I missed something or have anything wrong) but it does describe the significant changes.
