### ISSUE TITLE
type: integer problem

### ISSUE THREAD

**Issue by brettz9** [json-schema-org/json-schema-spec#311]
[Section 5.26](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.26) of the validation spec has an example using `"type": "integer"`. Also in http://json-schema.org/latest/json-schema-core.html#rfc.section.8.2.1 and the schema.

However, the core spec does not mention "integer" among the primitive types: http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2

**Comment by brettz9** [comment]
Updated the original post

**Comment by handrews** [comment]
integer was accidentally removed in that draft but was restored in the following draft https://tools.ietf.org/html/draft-wright-json-schema-01

the web site still needs to be updated with the HTML version of the latest draft which hasn't happened b/c @awwright has been traveling, @Relequestual is temporarily unavailable, and I'm trying to get through the backlog of web site updates since the markdown conversion and pretty much anything else will conflict with each other.

**Comment by brettz9** [comment]
I don't see integer as a type in the following draft either: https://tools.ietf.org/html/draft-wright-json-schema-01#section-4.2

**Comment by awwright** [comment]
@brettz9 "integer" is recognized as a subset of "number", which is defined in [the "type" keyword of the separate validation document](https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.25):

> ... or "integer" which matches any number with a zero fractional part.

**Comment by DavidBiesack** [comment]
-01 Change Logs do not mention `integer` - perhaps add a note to the Change Logs?

**Comment by handrews** [comment]
@DavidBiesack it wasn't a change, it was a typo in the previous draft that was fixed in this one.  At no point in any draft was integer ever not considered a type.  Even in the previous draft it was mentioned as a type in numerous places, just not in the actual type definition.

**Comment by handrews** [comment]
Also, it's not possible to edit published drafts anyway.  You can only publish new drafts.
