### ISSUE TITLE
Update json-schema/json-schema to redirect people here!

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#33]
- [ ] Edit the description to redirect people to this repo.
- [ ] Add a github issues template to redirect people here.
- [ ] Add a github pull request template to redirect people here.

I can't do this so... @awwright ?
I mean, I can make the templates and make a PR if it would help time wise.

**Comment by awwright** [comment]
I don't think I have access to that repo either, unfortunately

**Comment by Relequestual** [comment]
But didn't you make some commits: https://github.com/json-schema/json-schema/commits/gh-pages ?

**Comment by awwright** [comment]
That was merged by someone else iirc... that branch should be deleted too

**Comment by handrews** [comment]
@Julian do you have commit access to the old repo?  I see a recent commit (July 2016) from you that does not appear to be the result of a merge?  (and for that matter do you have the ability to close issues on the old repo?)

**Comment by Julian** [comment]
I have both, yeah, but not a huge amount of time these days. If you can lay out exactly what we want done I can do it though.

**Comment by awwright** [comment]
I believe this is all done. There's a notice in the README that should suffice.

**Comment by handrews** [comment]
@Julian would you be willing to look over
https://docs.google.com/spreadsheets/d/1pcT638kI7vrY4MjWxgMKUVpjuwceC9EtRuCcHldzB5c/edit#gid=0
and close any of the FIXED/ANSWERED/DUPLICATE/"should be closed" issues if you agree with those evaluations?  You can just click on the link in the left column to bring up the issue, so it should be easy to check and close things from the spreadsheet.  Obviously these need not all be done at once, but it would tremendously reduce the noise level when sorting out unresolved things from the old repo.

@awwright or @Relequestual : If this is all done, could you close this issue?

**Comment by Julian** [comment]
I probably can't go through each of those in the next few days, but maybe instead, if @Relequestual or @awwright do and sign off, I can do the closings. Does that work?

**Comment by awwright** [comment]
@handrews I don't see much use in paying any attention to that repository. Or at least let's wait until it starts causing even more problems for us. We've already poured a ton of energy into trying to fix as much as we can.

I'll let @Relequestual decide if this is close-worthy

**Comment by handrews** [comment]
@awwright as someone who just came into this project, having a repository full of issues lingering around was incredibly confusing.  I actually thought at first that the project was abandoned and almost moved on- it took me some effort to sort out that you were still active over here, and even more effort to figure out the relationship between the repos and how to approach things in the old vs new repos.

I understand that we can't shut down the old repo because of lack of permissions, but we can close it off as much as possible to minimize confusion and keep the project focused.  JSON Schema as a project will look much better to anyone trying to understand its current status if there is *not* huge pile of unresolved and unresolvable issues, and various things being "tracked" in up to three places (old repo wiki, old repo issues, and new repo issues).

**Comment by Relequestual** [comment]
I haven't the time to review all of the above, but the main thing I would like to make sure we do is stop people posting new issues and pull requests to the old repo.
To achive this, a pull request template and an issue template can be added, so users are shown a set message when  they attempt to do those things. I'll see if I can find time this afternoon to make this and make a PR into the project, which I'll then ask @Julian to merge in.

@Julian Thanks for finding the slither of time to even take a look here. Can totaly appreciate the lack of resource on this!

**Comment by Relequestual** [comment]
@handrews I really appreciate the hard work and effort you've clearly put into trying to clear this miss up. A real personal thanks on that!

I agree, we should close off issues as either out of date or migrated. if I manage to find some time to review the above list, I'll make a suggestion, and from the looks of it someone else will need to perform the actions to close them in the old repo, but I can link back to here and the new issue on this repo (or the web repo) as appropriate.

I'll self assign this issue to myself and take responsbility for it... I can't promise how soon it will be resolved, but it WILL be resolved and closed!

**Comment by awwright** [comment]
It looks like we've done a sufficient amount of work to direct people away from the old repo, think this is worthy of closing, @Relequestual?

**Comment by handrews** [comment]
It's been two months since I put a notice in every issue at the old repo- several people moved or closed there, the others haven't had a peep.  @Julian was kind enough to go close those out just now (thanks!) so I think we can declare this done.

I also submitted a PR so now the only thing visible on master is the README redirecting folks to here.  I think that should be sufficient deterrent to filing new issues and PRs.  @Relequestual of course re-open if you disagree but I think this is about as good as we're going to get without full admin access over there.
