### ISSUE TITLE
[draft6 validation meta-schema] validate property names in patternProperties

### ISSUE THREAD

**Issue by santhosh-tekuri** [json-schema-org/json-schema-spec#334]
I suggest addition to validation meta-schema, to restrict property names of patternProperties are regex.

```
         "patternProperties": {
              "type": "object",
 +            "propertyNames": { "format": "regex" },
              "additionalProperties": { "$ref": "#" },
              "default": {}
          },
```

The spec says:

```
Each property name of this object SHOULD be a valid regular expression, according to the ECMA 262 regular expression dialect.
```

**Comment by adamvoss** [comment]
]Someone else can correct me when they get around to it, but I think what you are running into is the definition of SHOULD.

The spec uses [this definition](https://www.ietf.org/rfc/rfc2119.txt):
> ```
> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
> may exist valid reasons in particular circumstances to ignore a
> particular item, but the full implications must be understood and
> carefully weighed before choosing a different course. 
> ```

Adding the check to the meta-schema, as done here, would change that to MUST (if we assume a valid schema must pass validation by the meta-schema).

**Comment by handrews** [comment]
@santhosh-tekuri Yes, I've argued for a more strict meta-schema in the past and was not successful.  In my work when I want more strict validation I just load a stricter meta-schema into the validator under the standard meta-schema URI.  I really just do this for internal testing (making sure no one misspelled a keyword, for instance).

@adamvoss your interpretation of SHOULD is correct.  I don't know that there are any clear rules on what sort of things make it reasonable to ignore a SHOULD.  In this case, I could see someone implementing a validator that supports Perl's regex syntax, which is much more extensive.

Users of that implementation would not be able to rely on other validators being able to understand their regexes, but for schemas in a closed system such as for a company's internal tools, that may be totally acceptable.  Putting the format in the meta-schema would make that impossible.

Also, the "regex" format was apparently dropped between draft-03 and draft-04.  I think this came up in another issue and no one could figure out why it was dropped (none of the current team were involved) so if you would like to file an issue requesting it be restored in the next draft please feel free.

However, I think we'll need to close this one as the meta-schema needs to be flexible rather than strict.
