### ISSUE TITLE
Java API to generate sample json from json-schema?

### ISSUE THREAD

**Issue by ymohdriz** [json-schema-org/json-schema-spec#337]
Hi team,

Is there any java API to generate sample json from json-schema?
All I found is javascript, node.js APIs.

It would be helpful if there is a JAVA API.

Thanks,
Mohammed

**Comment by erosb** [comment]
You can try running one of the javascript libraries on nashorn.

**Comment by handrews** [comment]
There are some tools like this listed at the bottom of our [software page](http://json-schema.org/implementations.html) under "Other", although I don't know if any are written in Java.

This project only works on the spec, so I'm going to close this since creating a Java API is well outside of our scope.  However, if you find one we would love to have it listed on our software page!  If you can't find one, I'd suggested finding a well-supported validation library with a Java API and filing this as a request with that project.

**Comment by ymohdriz** [comment]
Hi @handrews,

Found a java API to generate sample json from json-schema. https://github.com/apptik/JustJson/tree/master/json-generator

Can you add list this API in the software page, so that it will be useful for many users.

Thanks,
Mohammed
