### ISSUE TITLE
How to write simple multiple choice schema?

### ISSUE THREAD

**Issue by nashwaan** [json-schema-org/json-schema-spec#435]
For **single** choice schema (like radio buttons), we can simply write:
```json
{
  "type": "string",
  "enum": ["red", "yellow", "green"]
}
```
and this will accept input like `"red"` or `"green"`. Great.

-----

But, what is the simple json schema to accept **multiple** choice so the following should be valid:
`[]`
`["red"]`
`["yellow", "red"]`
`["red", "green", "yellow"]`

 and these should be invalid:
 `["red", "red"]`
`["red", "black"]`

The solution I can come up with for checkbox-like scenarios:
```json
{
  "type": "array",
  "uniqueItems": true,
  "additionalItems": false,
  "items": [
    {
      "type": "string",
      "enum": ["red", "yellow", "green"]
    },
    {
      "type": "string",
      "enum": ["red", "yellow", "green"]
    },
    {
      "type": "string",
      "enum": ["red", "yellow", "green"]
    }
  ]
}
```

But this is redundant and inefficient for larger multiple-choices, say 100.
So what is the correct way to achieve this without rewriting `"red", "yellow", "green"` multiple times?

**Comment by handrews** [comment]
Hi @nashwaan 
  This sort of question is best to ask on the mailing list or with the #json-schema tag on stackoverflow.  This repository is for discussing changes to the specification :-)

  But to answer your question:

```JSON
{
    "items": {
        "type": "string",
        "enum": ["red", "yellow", "green"]
    },
    "uniqueItems": true
}
```

should do it.  You could also add `"maxItems": 3`, but since there are only three legal values and the values must be unique, it's not strictly necessary- all possible arrays of length 4 or more will either fail the enum or the uniqueItems constraint.

**Comment by nashwaan** [comment]
Thanks a millition @handrews for your prompt answer.
I have been struggling with this for very long time!
Your solution is correct and so simple that I have definitly was over-thinking about it.

Sorry, about asking in the wrong place. Next time I will use #json-schema tag on stackoverflow.

Thanks again @handrews

**Comment by handrews** [comment]
@nashwaan you're welcome!  There is also a json-schema Google group if you do not get a prompt answer on stack overflow.
