### ISSUE TITLE
Audit normative vs informative references

### ISSUE THREAD

**Issue by dlax** [json-schema-org/json-schema-spec#471]
[Currently](http://json-schema.org/work-in-progress/WIP-jsonschema-hyperschema.html#rfc.references), RFC8288 on "Web Linking" appears in "Informative References". Is this intended? At a first glance, I would have expected it to be normative.

**Comment by handrews** [comment]
You don't need to *implement* RFC8288 for hyperschema.  We're referencing its philosophical model and terminology.  A lot of the "normative" references should be "informative", actually.

**Comment by handrews** [comment]
@dlax I hope you don't mind but I've generalized this to track an overall audit of the references.  As I noted above, I'm pretty sure it's a jumbled mess.  I'll update this issue with a better explanation before going into a PR.

**Comment by handrews** [comment]
@awwright I notice that all of the standards that are referenced as providing the syntax for values for `format` and `content*` are listed as informative.  Is that correct?  The IESG statement on normative vs informative says:

> Normative references specify documents that must be read to understand or implement the technology in the new RFC, or whose technology must be present for the technology in the new RFC to work.

In some sense, to implement format validation, one would need at least a partial implementation of such standards.

Compare this with listing the Linked Data Platform as a normative reference just because it defines "describedby" as a link relation.  Given that JSON Schema Core defines its own refinement of "describedby", which is itself documented in the IANA registry, is LDP really a normative reference here?

@dlax depending on the answers to these, RFC 8288 may indeed be normative for hyper-schema.  You definitely need to understand its concepts in section 2 (even though you would not re-implement the HTTP `Link` header from section 3).

**Comment by awwright** [comment]
@handrews I would think should be normative references.

My understanding is things like examples ("compare this to how XXX specification works") are informative, references to behavior defined elsewhere need to be normative.

Mere references to values defined elsewhere I suspect would be normative too. It might depend on how it's worded. For example, you don't need to import every single possible value for a link relation, importing Web Linking is sufficient.

**Comment by handrews** [comment]
@awwright sounds good.  So giving CBOR as an example of another media type that could fit the data model is informative, but the essential syntax for a value, or a closed enumerated set, would probably be normative.  An open enumerated set (such as link relations) would only need to reference where the concept and/or registry is defined normatively.

**Comment by handrews** [comment]
Merged #496
