### ISSUE TITLE
"format" as "date" or "format" as "full-date"

### ISSUE THREAD

**Issue by Yesugey941** [json-schema-org/json-schema-spec#483]
In Json, is it valid to set "format" as "full-date" ? One of my colleague is referring this page.

To ask in another way, is this json schema correct?

```
{
  "title": "MyTestSchema",
  "type": "object",
  "properties": {
    "MyDateValue": {
      "type": "string",
      "format": "full-date",
      "description": "We expect yyyy-MM-dd"
    }
  }
}
```

**Comment by handrews** [comment]
It's technically always correct because `format` is extensible.  However, user-defined formats will be ignored by validators that don't recognize them.  And of course, if someone else is using a validator that they have configured to recognize the same name but treat it differently, then you will have an interoperability problem.  However, with this particular value, `full-date`, it depends on your version of JSON Schema.

In draft-04 or draft-06, `full-date` is not an official format.  Although anyone who adds it as a custom format and does not have it mean the same thing it means in RFC 3339 is asking for trouble, so you're probably fine using it this way even in those versions.

In the forthcoming (next week? hopefully?) draft-07, `full-date`  is part of the reserved RFC 3339 format namespace, and if implemented, MUST be compatible with RFC 3339's definition of `full-date`.  draft-07 also defines `date` as a synonym for `full-date` and recommends using it instead, as `date` is more common in the wild as far as I know.

Either way, this usage you're showing here is probably pretty safe since it matches RFC 3339, and as of draft-07 the standard does not enforce support but does enforce that, if implemented, it must behave as expected by RFC 3339.

I know that's a bit complicated, but does it answer your question?

**Comment by Yesugey941** [comment]
Hi Handrews, that was exactly what I was looking for. Thanks!

**Comment by handrews** [comment]
Great- I'll go ahead and close this, then

**Comment by shrazvi** [comment]
If I am using a "date-time" as a format for a particular field, can it be used to validate "date only" "time only" values as well?
      "MinDate": {
        "type": "string",
        "format": "date-time",
        "description": "The minimum date value supported by the field."
      },

      "MaxDate": {
        "type": "string",
        **"format": "date-time",**
        "description": "The maximum date value supported by the field."
      },

      "DateOnly": {
        "type": "boolean",
        "description": "Specifies whether the field should support dateonly values"
      },

      "TimeOnly": {
        "type": "boolean",
        "description": "Specifies whether the field should support timeonly values"
      },
