### ISSUE TITLE
Simplify draft-07 meta-schema

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#486]
- remove unnecessary `"items": {}` in `examples`
- use boolean schema `true` as the default value of keywords where the default is `{}`

I can make a PR

**Comment by epoberezkin** [comment]
The same problem exists in draft-06 meta-schema, it can be updated as well.

**Comment by handrews** [comment]
I saw that at some point after pushing the draft-06 meta-schema and decided it was not worth changing given that someone shows up and complains every time we "fix" it.  So I'd rather leave draft-06 alone except for actual bugs.

I'd be fine with consistently using `true` instead of `{}` in draft-07, though, so if you'd like to submit a PR for that part, please do!

However, I put the technically-unnecessary `items` in for `examples` because otherwise someone thought it was an accident that `examples` didn't specify something.  Think of it as documentation emphasizing that the contents of the array are unconstrained.

Alternatively, you could remove it and put in a `$comment` explaining it, but why write a comment with the schema can show it clearly?

**Comment by epoberezkin** [comment]
ok, thanks

**Comment by handrews** [comment]
Merged #495
