### ISSUE TITLE
Copyright license is unclear

### ISSUE THREAD

**Issue by jfinkels** [json-schema-org/json-schema-spec#532]
The `README` states

> The source material in this repository licensed under the AFL or BSD license.

However, no copy of the exact copyright license is included in this repository. Can you please include a copy of the text of the exact license? This may be important if someone wishes to, for example, include a copy of the `schema.json` meta-schema as part of a software package.

**Comment by awwright** [comment]
This is probably workable, but most IETF work doesn't seem to include a license in the repository itself, you normally get a license from one of several external locations; the primary one being [RFC 5378](http://www.rfc-editor.org/rfc/rfc5378.txt) (which applies since the work is intended for IETF submission as an Internet-Draft).

Is there something in particular you're looking to copy?

**Comment by handrews** [comment]
Looking at two active RFC authors ( https://github.com/mnot/I-D and https://github.com/dret/I-D ) shows that it's common practice to only have the license in the draft text.

I was going to argue that "AFL or BSD" is a SPDX license expression and therefore has a precise meaning already, but actually neither of those is a license abbreviation:

https://spdx.org/licenses/

We should probably at least give a precise identification.

**Comment by jayrylan** [comment]
@handrews Has there been anymore decision making? I've put together a thoroughly typed TypeScript definition for JSONSchema, and I'd like to include documentation for each property directly from the spec.

Can I do this? What license should I release it under (and which exact version)? Of AFL or BSD, I'd highly prefer to release under BSD (it's more similar to MIT, which all of my existing packages are licensed as).

**Comment by handrews** [comment]
@jayrylan the spec itself is under whatever licensing the IETF uses (it's documented somewhere, but I don't remember where).  I'm pretty sure you can quote anything you want as long as you a. identify which draft it is and b. make it clear that you are citing a work-in-progress since this is still in the draft stage.

The question here is about the licensing for... um... actually I have no idea.  It's probably left over from when the web site used to be in the same repository as the spec?  Quote it like you'd quote any IETF draft and you'll be fine :-)

**Comment by awwright** [comment]
Traditionally RFCs are shared on the sneakernet, so I know there's no
problem with redistribution.

Anyways, if I didn't mention already, all of my work is public domain, for
what that's worth.

**Comment by Relequestual** [comment]
Closing in favour of #1160
