### ISSUE TITLE
Global Reference from Subschema with $id

### ISSUE THREAD

**Issue by dekryptic** [json-schema-org/json-schema-spec#536]
> `The "$id" keyword defines a URI for the schema, and the base URI that other URI references within the schema are resolved against.`

I played around with this idea [here](https://runkit.com/5a6144280fe2d50012b341c0/5a6144280fe2d50012b341c1). Is there any way to reference `definitions/name` in `parent` without having to specify an id for `definitions/name`, i.e. `$ref: "name"`?

**Comment by handrews** [comment]
`definitions/name` can also be referenced as

`{"$ref": "#/definitions/name"}`

using the [JSON Pointer fragment syntax](https://tools.ietf.org/html/draft-handrews-json-schema-00#section-5).  You do not need to use `"$id"` within the `name` schema in order to do this.  JSON Pointer referencing does not use `"$id"`, it just uses the JSON structure of the current document.

**Comment by dekryptic** [comment]
I tried that [here](https://runkit.com/5a64e5b93bf2b80012b14638/5a64e5ba1ac74a001212abd0), but I get a MissingRefError.

**Comment by handrews** [comment]
@dekryptic Oh, I see the problem.

`$id` both defines the identifier and resets the base URI.  `$id` values are URI references as defined in RFC 3986.

Let's assume that your external base URI (the URI from which you fetched the schema) is `https://example.com/schemas/foo`.

When we hit the schema with `{"$id": "nested"}`, then per RFC 3986 "nested" is interpreted as a path component, which is resolved against the external base to produce the new base `https://example.com/schemas/nested`.

Within a subschema under that `$id`, we hit your `$ref` and resolve it to `https://example.com/schemas/nested#/definitions/name`

However, the `definitions` section is *outside* of the object with `"$id": "nested"`.  It's JSON Pointer fragment URI is either `https://example.com/schemas/foo#/defintions/name` (starting with the external base), *or* because it has `"$id": "name"`, it could _also_ be referenced as `https://example.com/schemas/name` (by resolving that `$id` against the external base).

This is why when you had `{"$ref": "name"}` instead of `{"$ref": "#/definitions/name"}` it worked.  That `"name"` was again interpreted as a path component and resolved againsst `https://example.com/schema/nested` to produce `https://example.com/schemas/name`

Generally, when we want to give an explicit name within a single document, we don't use a path component (because those usually indicate separate files, even though that's just a convention).  So instead we would use plain name URI fragments: `{"$id": "#nested"}` and `{"$id": "#name"}`.

Note that fragments have no practical effect on the base URI, because whenever you resolve against a base, if the base has a fragment the first step of resolution is to remove the base's fragment.  So when you have `{"$id": "#name", ...}` and reference it as `{"$ref": "#name"}` within the same file, without having changed the non-fragment portion of the base URI, the for all practical purposes you can ignore the base-changing behavior.  Plain name fragments just don't affect it.

I know that's a lot of babbling about different URI components and resolution mechanisms, please let me know which parts are unclear.

**Comment by handrews** [comment]
@dekryptic did this answer your question?  If I don't hear from you for a few more days I'll assume this was sufficient and close it.  You're welcome to re-open or join the slack channel (invite link at the bottom of the json-schema.org page) and ask there.

**Comment by awwright** [comment]
@dekryptic Yeah, since "id" is a URI Reference, you're probably intending to use fragments. Same thing as doing `<a href="#bottom">Jump</a>` in HTML.

**Comment by handrews** [comment]
It's been a month with no further question or comment since the answers were given, so I'm closing this.
