### ISSUE TITLE
General expressions support and cross-field validations

### ISSUE THREAD

**Issue by brunodymios** [json-schema-org/json-schema-spec#541]
What about having a requirement saying that field A must be always equal to **field B divided by field C**?
Consider the case in which we are managing financial data and we need this information to both show in a form the auto-computed value and validate/recompute this value server-side.

Having this kind of possibility directly in the Json Schema (even through the support for referencing other fields in properties like "_minimum_" or "_multipleOf_") could be extremely useful and makes Json Schema even more complete in my opinion.
Such a feature will enable for creating both server-side and client-side validations by only relying on the Json Schema describing the data.

Is this currently being addressed somehow?

**Comment by anweiss** [comment]
Big +1 to this. Support for co-occurrence constraints in JSON schema would be incredibly advantageous in terms of deferring property and property value interpretation to the schema itself instead of building such interpretation into JSON consumption tooling.

**Comment by handrews** [comment]
@brunodymios @anweiss you might want to take a look at @awwright's data relationship proposal #549 and see if that would meet your needs?

**Comment by anweiss** [comment]
Thanks @handrews. Per some of your comments, what I'm mostly interested in is data relationship validations in the instance document itself and not references to external data parameters via URIs per the proposed `valueRange`, `valueDefine`, `valueUniqueKeys`, etc keywords

**Comment by handrews** [comment]
@awwright I'm increasingly convinced that the right way to implement this whole area of functionality, whether `$data`, this proposal, or any of the other vaguely related proposals, is as an additional vocabulary.

Yeah, I know, vocabularies are my solution to nearly everything, but as you note, this is both difficult to implement yet in demand from a certain subset of users.  We've had multiple related issues filed over just the past few months, and `$data` has come up regularly since draft-04 and been in use in at least one implementation.

I don't think that adding this sort of thing disrupts the existing core spec (including the additions to it already planned for draft-08).  It will also continue to be possible to implement existing validation and hyper-schema without it.  And as you note, this is "code-on-demand" territory which is an optional constraint for REST in general, which tells us something.

How would you feel about working on this as an additional vocabulary?  It can then succeed or fail on its own, like XForms (although hopefully we can learn from XForms' difficulties).  And it also would mean that we don't add a huge and burdensome requirement to basic validator implementations when we're trying to stabilize core and validation as an actual standard.

**Comment by awwright** [comment]
#549 covers the fundamental idea behind what's been missing, I think, but still needs to describe how it covers cases like this issue.

I sort of have an idea on how to fill that in, except this issue asks for one more thing: it's asking for a relationship between three fields. It wants to assert that `A = B / C` (and presumably that `B mod C = 0`). I don't know of any way to do this except implement some sort of scripting language or scripting vocabulary, and an array of general assertions. This is very powerful (in the bad sense [(1)](https://www.w3.org/2001/tag/doc/leastPower.html) [(2)](https://www.w3.org/DesignIssues/Principles.html) [(3)](https://en.wikipedia.org/wiki/Rule_of_least_power), in that we lose many of the semantic meanings over if a keyword were used).

Further, there's math considerations. JSON Schema is arbitrary precision. But most people will probably want to implement IEEE floating point.

**Comment by brunodymios** [comment]
I agree on what has been written above. A first step is to introduce relationships between data inside the same JSON Schema definition and define how they relates in order to cross-validate them.

I did not think about data precision before @awwright comment, since the `A = B / C` expression was used as an example only.  Regarding this, I think that the most important thing is to have something that is coherent in both client and server validators.  

Remote data sources for validations can of course help very often but I see them as a subsequent step with respect to these "local" cross-validations and I would maintain them separated.

**Comment by handrews** [comment]
We've consolidated the proposals of this sort into #855.  If this conversation is still of interest, please continue it there.
