### ISSUE TITLE
better handling of required properties

### ISSUE THREAD

**Issue by marcelh-gh** [json-schema-org/json-schema-spec#547]
_**ENHANCEMENT**_

the current solution with an array listing all the required properties for an object gets tedious especially for large objects with lots of properties.

it would be much nicer if a required flag could be used at the property level.

**example:**

instead of...
`"type":"object",
"required": [
            "propA","propC"
        ]`

...
`"type":"object",
"properties":{
"propA":{"type":"string", "required":"true"},
"propB":{"type":"string"},
"propA":{"type":"string", "required":"true"}`

this is exactly like for example Mongoose (ORM for MongoDB) handles this.

**Comment by marcelh-gh** [comment]
since I am generating my schemas based on TypeScript types/interfaces using typescript-json-schema, the issue is not that bad for me. but when you create a schema manually, the above suggestions would help quite a bit.
also, even for the generated case, it would increase readability of the schema.

**Comment by Relequestual** [comment]
Sorry but I think most people would dissagree with yout suggestion.
It was actually changed FROM the way you suggest to how it CURRENTLY is back in draft 4.
I don't want to delve back into old issues that aren't even in this repo to find the arguments (if they are there at all).

> it would be much nicer if a required flag could be used at the property level.

I completly dissagree. I want to easily see what properties of an object are required in one go, without having to inspect every property.

As such, I'm closing this issue, because I can't think of a stong argument as to why we would revert this. I'm open to being convinced.

**Comment by handrews** [comment]
One reason to keep things the way they are is that it makes it very easy to re-use a group of property definitions with different sets of required fields.  While you can do this with boolean flags, it's much more verbose.

**Comment by desmondgc** [comment]
One reason to change this would be to simplify schema comparison. Consider the following schemas:

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "prop1",
    "prop2"
  ],
  "properties": {
    "prop1": { "type": "string" },
    "prop2": { "type": "string" }
  }
}
```

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "prop2",
    "prop1"
  ],
  "properties": {
    "prop2": { "type": "string" },
    "prop1": { "type": "string" }
  }
}
```

These schemas are semantically identical but the underlying JSON is not since array order is significant. Differences in property order are correctly ignored by many JSON comparison tools e.g. [JSON Diff](http://www.jsondiff.com/).

(Yes there are other array-valued properties like "type" that should also have set-like characteristics.)
