### ISSUE TITLE
Correct interaction between conflicting allOf and type

### ISSUE THREAD

**Issue by ehrmann** [json-schema-org/json-schema-spec#553]
What's the correct behavior for a schema like this where the `allOf` conflicts with `type`?

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "allOf": [ { "required": ["foo"] } ]
}
```

Should `null` validate?

The documentation for `allOf` states

> An instance validates successfully against this keyword if it validates successfully against all schemas defined by this keyword's value. 

And `type` states

> An instance validates if and only if the instance is in any of the sets listed for this keyword. 

Since `null` validates for

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "required": ["foo"]
}
```

my guess is that it should also validate when `required` is an an `allOf`.

**Comment by awwright** [comment]
The two schemas you listed are functionality identical.

What do you mean by "allOf conflicts with type"?


On Mar 2, 2018 14:13, "David Ehrmann" <notifications@github.com> wrote:

What's the correct behavior for a schema like this where the allOf
conflicts with type?

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "allOf": [ { "required": ["foo"] } ]
}

Should null validate?

The documentation for allOf states

An instance validates successfully against this keyword if it validates
successfully against all schemas defined by this keyword's value.

And type states

An instance validates if and only if the instance is in any of the sets
listed for this keyword.

Since null validates for

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "required": ["foo"]
}

my guess is that it should also validate when required is an an allOf.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/json-schema-org/json-schema-spec/issues/553>, or mute
the thread

**Comment by ehrmann** [comment]
Maybe there isn't a conflict. Do both `null` and `{"foo":0}` validate for

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "required": ["foo"]
}
```

**Comment by awwright** [comment]
Yeah.

Note that `null` also validates against `{required: ["foo"]}`.


On Mar 2, 2018 16:21, "David Ehrmann" <notifications@github.com> wrote:

Maybe there isn't a conflict. Do both null and {"foo":0} validate for

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "required": ["foo"]
}

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/json-schema-org/json-schema-spec/issues/553#issuecomment-370085215>,
or mute the thread

**Comment by handrews** [comment]
@ehrmann most keywords work along the principle of "if the instance is of the relevant type, then ...", so `"required": ["foo"]` should be read as _if this instance is an object, then it MUST have a property named "foo"_

The validation against `"type": ["null", "object"]` is considered separately from the validation against `required`, so the behavior is the same whether there is an `allOf` separating them or not.
