### ISSUE TITLE
Questions about internal referencing

### ISSUE THREAD

**Issue by yuloh** [json-schema-org/json-schema-spec#576]
Hello,

I am just catching up on all the changes that have been made since Draft-04.  I am having a little trouble understanding exactly how the internal referencing behavior defined in Draft-05 [8.2.1](https://tools.ietf.org/html/draft-wright-json-schema-00#section-8.2.1) is supposed to work.

I looked through the issues and PRs and saw that the most recent description is this:

> If the resulting URI identifies a schema within the current document, or within another schema document that has been made available to the implementation, then that schema SHOULD be used automatically.

If I am understanding correctly, given this example schema, when I resolve the $ref and go to load `http://localhost:1234/dateTime` I should first check the current document and see that is is defined already, then load that schema.

```json
{
  "$id": "http://localhost:1234/person",
  "type": "object",
  "properties": {
    "createdAt": {
      "$ref": "dateTime"
    }
  },
  "definitions": {
    "dateTime": {
      "$id": "dateTime",
      "type": "string",
      "format": "date-time"
    }
  }
}
```

To be able to do that I think I would need to first find all `$id` keywords within the current document before attempting to load it from elsewhere.  Now what if `dateTime` is inside of a reference itself, e.g.

```json
{
  "$id": "http://localhost:1234/person",
  "type": "object",
  "properties": {
    "createdAt": {
      "$ref": "dateTime"
    }
  },
  "definitions": {
    "common": {
    	"$ref": "common"
    }
  }
}
```

```
{
  "$id": "http://localhost:1234/common",
  "definitions": {
    "dateTime": {
      "$id": "dateTime",
      "type": "string",
      "format": "date-time"
    }
  }
}
```

Is it still considered part of the current document?  If so that seems problematic.  I need to check all `$id` keywords within the current document to know if it's already defined locally before attempting to resolve a reference, but I can't actually access all `$id` properties without resolving a reference.

Hopefully I explained that well enough.  Let me know if I need to clarify anything.

**Comment by handrews** [comment]
@yuloh we do not recommend implementing draft-05.  For core and validation, it was a clarification of draft-04 rather than a change.  There was technically a change in a format value, but it was changed again in draft-06 so it's not worth supporting.  There is no meta-schema for draft-05, and therefore no way to indicate that you are using it.

I rewrote the sections on identification and dereferencing (again) in the most recent draft.  All of this is clarification and is applicable to both draft-06 and draft-07: https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8

Draft-07 (draft-handrews-*-01) core and validation are backwards-compatible with draft-06 (draft-wright-*-01), so I recommend implementing both of those.

I'll answer your specific questions about how it works in the next comment.

**Comment by awwright** [comment]
And note, the intended behavior serves a similar function to `id` in HTML and other hypermedia formats, where you can specify `id="foo"` on an element, and then if you refer to it elsewhere in the document (like `href="#foo"`) the processor knows exactly where in the document that points to.

**Comment by handrews** [comment]
@yuloh Both [JSON document](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-4.1) and [JSON Schema document](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-4.3) are defined in the core spec, so any use of the term "document" is as defined in those sections.

In general, you process documents, make note of references, and resolve them as you find them.  If you run out of identifiable, loadable documents before you resolve all references, then that's an error.

In your example, if you start from "person", you would note the references to both "dateTime" and "common".  After you finish scanning "person" for schemas, you won't have found either.

If you try to fetch "dateTime" over HTTP, that will fail because it is not its own document.  So you then try to fetch "common" over HTTP, which (presumably) succeeds.  (_Or you may have been provided all of these schema documents offline in advance, such as by passing in files from a local filesystem, in which case you would try look up the schema based on its `$schema` value, but it's fundamentally the same process whether local or remote_)

As you process "common", you'll note the identifier for "dateTime" and be able to resolve that reference as well.

I'm really not sure how to make this more clear.  We have literally rewritten this section in every single draft based on complaints since the last draft, and none of the rewrites have ever been all that successful.  I wish we could find something that works.

**Comment by yuloh** [comment]
Thanks for the quick response.

> @yuloh we do not recommend implementing draft-05.

Sorry I should have clarified. I am implementing support for draft-06.  I mentioned draft-05 because that is the first time I saw this wording used.

> @yuloh Both JSON document and JSON Schema document are defined in the core spec, so any use of the term "document" is as defined in those sections.

I read the definition but I was unsure if the contents of an external document were considered part of another document if they were referenced.  In this example I was trying to figure out if the referenced subset of `http://localhost:1234/common` was considered part of `http://localhost:1234/person`.  This scenario may fall under 'another schema document that has been made available to the implementation' in which case the distinction doesn't matter.

Thanks for the thorough explanation, it's very helpful.  My understanding based on draft-04 was that I should resolve references like this:

1. Resolve the `$ref` against `id` or the URI the schema was loaded from ('dateTime' resolves against 'http://localhost:1234/person`, returning `http://localhost:1234/dateTime`
2. Try to load the referenced document from that URI (`http://localhost:1234/dateTime`.
3. If loading fails raise an error.

It sounds like you are saying it should work like this instead:

1. Resolve the `$ref` against `id` or the URI the schema was loaded from ('dateTime' resolves against 'http://localhost:1234/person`, returning `http://localhost:1234/dateTime`).
2. Try to load the referenced document from that URI (`http://localhost:1234/dateTime`).
4. If loading fails note that it's unresolved and try resolving all other available `$ref`s in the current document (resolve `http://localhost:1234/common`).
5. Search each resolved document for the unresolved reference from step 3.
6. If you still have not been able to resolve the reference raise an error.

Does that make sense?

**Comment by handrews** [comment]
@yuloh almost- you SHOULD (in the formal RFC recommended-but-not-mandatory sense) try to load from within the document first.  This is in part to avoid overburdening servers that host schemas (some of which will be expecting runtime downloads, but others do not- for instance, hopefully not every single occurrence of the meta-schemas results in an HTTP request to json-schema.org!)

**Comment by yuloh** [comment]
OK, that makes sense.

Is this how draft-04 is supposed to work or is this behavior new for draft-06?  I'm not sure if I should backport this for dereferencing draft-04 schemas.  I also opened [an issue with the test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/217) because I was unsure about that.

I still don't fully understand the benefit of being able to use references like this.  I read #318 and the linked PR which says internal referencing allows skipping the process of resolving URI references.

In this example it does allow us to skip resolving `http://localhost:1234/dateTime` over the network (and allows us to not make it available at that URI at all), but in order to resolve it I still needed to resolve `http://localhost:1234/common`, and if there were any other references inside of the document I would have to of resolved all of them in an attempt to find `dateTime` before giving up and finally attempting to load it using the URI.  In the best case scenario you could avoid one request but in the worst case scenario you have to make N requests, where N is the # of external references you had to resolve before finding the schema you were looking for.

I think this will also make libraries more vulnerable to infinite loops caused by circular references.  In my library the reference is resolved lazily as it's accessed.  Since it's only accessed as needed by the validator it will never resolve references that aren't needed to validate the current data and it won't recurse deeper than the data is nested.  If I have to check every `$ref` in the current document to see if a `$ref` can be resolved then my reference resolving code becomes vulnerable to infinite loops.

If the goal is to prevent overburdening servers I think there are simpler ways to accomplish that.  I personally use a local copy of any schema I need to reference and override the loader so any attempt to load `http://json-schema.org/draft-07/schema` will use the local copy instead.  Another approach is to bundle the schema using something like [json-schema-ref-parser](https://github.com/BigstickCarpet/json-schema-ref-parser).

**Comment by handrews** [comment]
None of the authors/editors of draft-04 are still active with the project, so I have no idea what they intended.  @awwright might have an idea, but honestly we'd rather people moved off of draft-04 at this point.  If you've had an implementation of draft-04 all of this time an people are fine with it, just leave it as-is.  Hopefully no one is writing new draft-04 implementations at this point.

> If I have to check every $ref in the current document to see if a $ref can be resolved then my reference resolving code becomes vulnerable to infinite loops.

OK something's still confusing apparently because I've implemented this and that's not a problem.

>  If I have to check every $ref in the current document to see if a $ref can be resolved

Why would you do that?  You just need to check the `$id`s in the document and see what URIs are available within the document.  You really only need to find all of the base URIs and non-JSON Pointer fragments (e.g. `"$id": "#foo"`), as JSON Pointer fragments can be lazily resolved against the base.

But you have to do that anyway, because the only possible way to find a plain name fragment is to scan the file until you find it.  It's not possible to get in a loop doing that because you're just walking the JSON object/array structure of the schema, you're not actually following `$ref`s.

Actually resolving the `$ref`s has to be done lazily.  If you want to avoid scanning the document up-front, then you can do something like:

1. encounter a `$ref` that needs to be resolved
2. if it can be resolved from an already-known base URI plus a JSON Pointer fragment, do that
3. if it can't, scan the current document for `$id`s to see if the base URI and/or plain name fragment are present, and use that
4. if you still can't find it, start resolving unresolved remote references and scanning those documents
5. if you run out of identifiable schema documents, error out

The only difference here is step 3, and it's not possible to loop there because JSON is not cyclical.

You're not going to get into an infinite loop in step 4 because presumably you keep track of which remote URIs you've already loaded and scanned.

> I personally use a local copy of any schema I need to reference and override the loader so any attempt to load http://json-schema.org/draft-07/schema will use the local copy instead.

That's exactly step 2, where "already known" can mean "parsed from the command line in advanced" or some other outside mechanism of pre-loading the schemas.

> Another approach is to bundle the schema using something like json-schema-ref-parser.

And now I'm even more confused because things like json-schema-ref-parser's "bundle" and "dereference" features are exactly why step 3 exists.  If you bundle a bunch of otherwise-separate-document schemas into a single document, then all of the bundled subschemas will set a new base URI with `$id`.  When you load a file like that, why wouldn't you look for those ids and use them when they are referenced?  The whole point of putting them all in one file is to avoid having to resolve them externally.

**Comment by yuloh** [comment]
> Why would you do that? You just need to check the $ids in the document and see what URIs are available within the document

I'm referring to this step: 

> if you still can't find it, start resolving unresolved remote references and scanning those documents

You can't know what ids are defined without resolving every single reference in the document.  It seems like this outweighs any benefits as far as avoiding loading external references.

Your solution for avoiding the infinite loop makes sense, and the steps are very helpful for understanding how the references should be resolved.

> If you bundle a bunch of otherwise-separate-document schemas into a single document, then all of the bundled subschemas will set a new base URI with $id. 

I was referring to bundling schemas and replacing the $ref with a relative reference to /definitions.  In that case you don't need to scan the document up front for ids because every reference is a relative pointer to the actual location.

My main point is that the behavior outlined in the internal referencing section seems to add a lot of complexity to implementations and doesn't provide the cited benefit. This might just be indicative of me not fully understanding the use case for $id.

I did see the comment about leveraging it to bundle the schema without using references which does seem useful.  It sounds like that is what you are describing in your comment too?

**Comment by handrews** [comment]
> You can't know what ids are defined without resolving every single reference in the document.

I still don't follow.  To determine whether you can resolve *within a single document* you only need to scan *that single document*.  You don't need to "resolve" anything.  If you don't find it in the document, go on to the next step, which is what you would do anyway.  Scanning is about identifying, not resolving.  Resolve lazily.  But in order to resolve, you have to know what identifiers you have.

It's like playing "Go Fish".  If I ask you if you have any 10s, you have to look in your hand to tell if you have any 10s.  You can look in advance and remember what cards you have, or you can look when I ask you to look.

> My main point is that the behavior outlined in the internal referencing section seems to add a lot of complexity to implementations and doesn't provide the cited benefit. This might just be indicative of me not fully understanding the use case for $id.

I still don't see the complexity, and I've implemented it (I never actually implemented a validator, but I implemented full `$id`/`$ref` support to make sure I understood all of the cases).

If you don't resolve internally, then you go fetch the same document you already have over HTTP and... scan it.  Resolving internally is exactly the same as externally, **except you don't fetch the document over HTTP because you are already in the middle of processing it**.  That's it.  There's nothing else going on here.

Finish processing the current file, see if your reference resolved, and if not, proceed with external referencing.

There's some standards-ese to make it precise, but the entire point is simply to avoid jumping out of the document you're already processing and then jumping back in.  How does skipping that out-and-back-in step makes things complicated?  It is objectively fewer steps to accomplish.

**Comment by yuloh** [comment]
> I still don't follow. To determine whether you can resolve within a single document you only need to scan that single document. You don't need to "resolve" anything.

Going back to the original example schema I am talking about this:

> So you then try to fetch "common" over HTTP, which (presumably) succeeds. 

At this point I am resolving an unrelated reference (common) to see if it contains the schema I originally wanted to resolve (dateTime).

If I am understanding you correctly, if resolving common does not yield dateTime  and the original document contained any other references I would then continue resolving each of those until I found dateTime or exhausted all options.

That is the complexity I am referring to.  With my current draft 4 implementation I don't need to scan the entire document and resolve unrelated references to see if an external reference is actually in the current document.  I just try to resolve it (in this case loading `http://localhost:1234/dateTime`).

Does that make sense?

> the entire point is simply to avoid jumping out of the document you're already processing and then jumping back in

Using my original example, I am jumping out of the current document to resolve common. We didn't save a step, we loaded the same amount of external references as we would have if we tried loading dateTime directly. Is that not the case?

**Comment by awwright** [comment]
Let's walk through how I would do it, maybe that will help.

First, note that you won't usually be downloading schemas over HTTP. Normally you might just throw a bunch of schemas into a directory and load them all at runtime, or compile it into the program itself.

The only reason you would do so is if there's no hope of knowing which schemas you're dealing with ahead of time. For example, a web browser with functionality to validate JSON documents against a server-provided schema, before you try to submit it.

In my notion of how this works, there's also a Link header that you can use to specify all the JSON Schema documents needed to comprehend the JSON document being composed/viewed. So maybe the server says "first download these JSON Schema files <.../a.json>, <.../b.json>", then it says "this document here must also be described by the JSON Schema <urn:foo:bar>" and one of schemas it downloaded has `{"$id":"urn:foo:bar", ...}` so it uses that one. This is effectively the same thing as scanning a directory and loading all the schemas at runtime that I described above.

Suppose we _don't_ do that, but we download the document at the HTTP URI specified in $ref. (With me so far?)

So in this case, suppose a server tells me I need to validate my document against `http://localhost:1234/person`  before submitting it (the second pair of documents you provided), and there's no Link references to schemas I can download, so I have to try to download that URI directly.

0. Download `http://localhost:1234/person`. The server returns a 200 without any redirect or Content-Location header, so use the returned document as the "person" schema.
0. Scan the "person" schema for $ref/$id objects. It finds no other schemas with an $id, but it does find two references to "/dateTime" and "/common".
0. Download "/dateTime". The server returns 404.
0. Download "/common". The server returns 200 (no redirect, no Content-Location), so use the returned document for "/common".
0. Scan the "/common" schema for subschemas and references. It finds one subschema, "/dateTime". The validator uses this schema to validate references to "/dateTime" even though the first request 404'd.

At this point, all references now resolve to a schema.

If both documents returned 404, there'd be no way to validate.

If both documents returned 200, you'd have to figure out a way to decide which one is authoritative. If both are identical, it doesn't matter. If they're different, maybe throw an error instead of choosing one.

Does this make sense?

**Comment by yuloh** [comment]
Hi @awwright, thanks for chiming in.

I understand completely how the schemas should be resolved as of draft-05.  In the past few comments I have been trying to explain why I think the pattern of schema resolution described as of Draft-05 is not beneficial.

Let me reiterate how I was resolving schemas before based on my understanding of draft-04.  Let's say I am attempting to validate the property `createdAt`.

0. Download http://localhost:1234/person. The server returns a 200 without any redirect or Content-Location header, so use the returned document as the "/person" schema.
1. Start validating using the "/person" schema and encounter a reference to "/dateTime".
2. Download "/dateTime". The server returns 404.

I resolved `dateTime` against the base URI, attempted to fetch the external schema using the resolved URI, and it failed.  I had to resolve one external reference in order to validate `createdAt`, which is the same number of external references as your example.  I did not attempt to load `common` because it has nothing to do with the properties I am validating.

Now imagine the schema has a couple more references:

```json
{
  "$id": "http://localhost:1234/person",
  "type": "object",
  "properties": {
    "createdAt": {
      "$ref": "dateTime"
    }
  },
  "definitions": {
  	"a": {
  		"$ref": "a"
  	},
  	"b": {
  		"$ref": "b"
  	},
    "common": {
    	"$ref": "common"
    }
  }
}
```

Using my draft-04 approach I would still only have to resolve a single external reference to validate `createdAt`.

Using the draft-06 approach, assuming scanning the document starts at the top, I would have to resolve 3 external references to validate `createdAt`.  I would resolve 'a', then 'b', and finally 'common'.

The reason I am pointing this out is because it contradicts the reasons cited for the draft-06 behavior being necessary.  In this thread the two reasons cited were:

- To avoid overburdening servers
- To avoid having to leave the current document

In the best case the burden on the servers is the same and the worse case is significantly worse.  The same is true for leaving the current document.

The only benefit I can actually see is that you can bundle schemas without updating references, but that comes at the cost of implementation complexity and runtime performance.

The downsides I am attempting to explain is:

- You have to make one to two additional passes over each document that weren't necessary before.  Once to attempt to find the matching `$id` without resolving external references, then again to start resolving references in attempt to find it (steps 3 and 4 of [this comment](https://github.com/json-schema-org/json-schema-spec/issues/576#issuecomment-376016760))
- You have to resolve N more references than before, where N is the number of unrelated references you resolve before either finding the schema you were looking for or failing to and attempting to load it directly (step 3 in your example).
- You have to keep track of which remote URIs you already loaded to prevent infinite loops.  It's arguably good to do this anyway but requiring it to do any reference resolution is added complexity.  As I explained previously this isn't necessary if you aren't loading every single reference in the document.
- None of this behavior is necessary if you are using json-reference without JSON Schema $id (like OpenAPI).  It was much easier to isolate the JSON Schema changes before when it only changed how the URI scope was resolved.

As I said before the reason I asked if this applies to draft-04 is because a test was added to the daft-04 test suite requiring this behavior.

**Comment by Julian** [comment]
@yuloh my own validator is still not quite draft 6 ready, so I'll comment almost only on the test suite portion (there), but here all I'll say I believe is that I *think* my validator's behavior is fairly close to what you describe [on how you're lazily looking things up in draft 4] and your bullets look pretty agreeable :) so please do press on here until things are clear.

**Comment by awwright** [comment]
@yuloh Again, the older drafts don't function differently (not much, if at all). There's no distinct draft-04 or draft-06 approach. The only things that each draft defines are the keywords: references to other schemas, how to assign URIs to schemas, and (for HTTP) how to define which schema a resource uses.

There's no one correct process to dereference schemas, and what you're doing probably isn't wrong, but I would highly advise front-loading as much work as possible. That is, you should download all the schemas and completely understand the schema you're using before trying to validate something. That seems to be the solution for the example you gave.

**Comment by handrews** [comment]
> Using the draft-06 approach, assuming scanning the document starts at the top, I would have to resolve 3 external references to validate createdAt. I would resolve 'a', then 'b', and finally 'common'.

@yuloh why would you do that?  As I have said repeatedly, you scan for *identifiers* (`$id`) in the single document.  You do not just start chasing `$ref` all over the place.  The initial scan ***does not do ANYTHING AT ALL with `$ref`***.

So you start validating and hit "createdAt".  You check what identifiers you've seen so far.  The only base URI you've seen is "http://localhost:1234/person" so you attempt to resolve the `$ref` to "http://localhost:1234/dateTime" externally.  If that works, then you're done.

However, in your example you are saying that you get a 404.

At this point you have two options, *both of which are compliant with the spec*:

1.  Give up and return an error.  You haven't see this URI in the local document, and your attempt to fetch it failed.  The spec does not require you to do anything else.  For strict compliance, this is what I would expect.
2.  Get fancy and go find everything that might be loadable, load it, and see if you find it.  This depends a lot on how the implementation works and how it allows users to control resolution- nearly every implementation I've seen offers some options here.

Option 2 has nothing to do with the spec at all.  **AT ALL**.  And "everything that might be loadable" is intentionally vague (and not a phrase from the spec, it's just what I typed right now).  Many implementations, as @awwright note, allow just loading schemas from a directory or something.

If your implementation allows pre-loading from a directory, and you haven't pre-loaded all of them, you probably should.  You might find the thing.  Presumably the end-user supplied them expecting them to be loaded.

If your implementation only resolves over HTTP, or has already loaded all local schemas and not found anything, and your user has somehow indicated that they are OK with extra networking requests / processing time in an attempt to find everything, it would be reasonable to go find all the URIs (including from other `$ref`s) and load them.

But there is nothing whatsoever in the spec that requires or even suggests that.  In fact, the spec suggests **against** automatically loading `$ref`'d schemas over the network.

**Comment by yuloh** [comment]
I'm not sure how we keep misunderstanding each other

> @yuloh why would you do that? As I have said repeatedly, you scan for identifiers ($id) in the single document. You do not just start chasing $ref all over the place. The initial scan ***does not do ANYTHING AT ALL with $ref***.

The reason I opened this issue was to clarify if I needed to resolve references during the scan for identifiers.

> To be able to do that I think I would need to first find all $id keywords within the current document before attempting to load it from elsewhere. Now what if dateTime is inside of a reference itself, e.g. Is it still considered part of the current document? 

https://github.com/json-schema-org/json-schema-spec/issues/576#issue-308376720

To which you replied:

> If you try to fetch "dateTime" over HTTP, that will fail because it is not its own document. So you then try to fetch "common" over HTTP, which (presumably) succeeds.

https://github.com/json-schema-org/json-schema-spec/issues/576#issuecomment-376001675

Later you said:

> if you still can't find it, start resolving unresolved remote references and scanning those documents

https://github.com/json-schema-org/json-schema-spec/issues/576#issuecomment-376016760

And after that @awwright added:

> Download "/dateTime". The server returns 404.
> Download "/common". The server returns 200 (no redirect, no Content-Location), so use the returned document for "/common".

https://github.com/json-schema-org/json-schema-spec/issues/576#issuecomment-376090724

These responses really make it sound like I am supposed to start resolving unrelated references if the initial scan does not find the identifier.

> Give up and return an error. You haven't see this URI in the local document, and your attempt to fetch it failed. The spec does not require you to do anything else. For strict compliance, this is what I would expect.

Great.  This is all I wanted to know.

> Get fancy and go find everything that might be loadable, load it, and see if you find it. This depends a lot on how the implementation works and how it allows users to control resolution- nearly every implementation I've seen offers some options here.
> Option 2 has nothing to do with the spec at all. AT ALL.

Ok, it really sounded like this is what I was expected to do based on the replies I received.  Good to know that it's not required behavior.  It wasn't clear at all to me if 'current document' included other (possibly unresolved) references.

Thanks for your patience and sorry for the confusion.

**Comment by handrews** [comment]
> It wasn't clear at all to me if 'current document' included other (possibly unresolved) references.

Ah, this was the main point of confusion, then.  I had thought the definition of "document" in the spec was clear enough.

> Ok, it really sounded like this is what I was expected to do based on the replies I received. Good to know that it's not required behavior.

Two final thoughts on this:

1. If you take the same schema except that you have something else that directly references "common" (causing you to load and scan it, and find "dateTime" as an `$id`), then if you take the minimal approach, whether you'll successfully resolve "createdAt"'s `$ref` to "dateTime" will depend on whether you hit the direct reference to "common" before you hit "createAt" or not.  Which will be a very arbitrary effect for the user, and given the unordered nature of objects may change unpredictably from one environment to the next, or as more fields are added.  However...
1. ...arguably, if the user is going to use a file with multiple base URIs stuffed into it, it is their responsibility to provide it to the implementation up front to avoid that behavior.

It's just worth calling out that the minimal approach, while fully conforming to the spec, may behave counter-intuitively.

Might be worth an interoperability note, now that I think about it, since variations in key iteration order are what make the behavior inconsistent.
