### ISSUE TITLE
Instance, Schema, MetaSchema, ....

### ISSUE THREAD

**Issue by GEricson** [json-schema-org/json-schema-spec#616]
Assume that http://json-schema.org/draft-04/schema is used to represents a metametaschema document
Assume a metaschema document that defines a generic house with various rooms and other element.
Assume a schema document that defines the elements of a mobile house.  This would extend generic house.
Finally an instance document for a specific model of mobile house.

Not sure if this is the right approach to accomplish this.
- the generic house could include a $schema referencing the json metametaschema document
- the mobile house could include a $schema referencing the generic house metaschema document 
- the instance document could include a $schema referencing the mobile home schema document.

Do we also need to use the "allOf" statement to accomplish this goal?

**Comment by gregsdennis** [comment]
I think the second one (that describes a generic house) is just a schema. The meta-schemas are "meta" because they validate themselves.  They are schemas that describe schemas.

I think what you're looking for is extensibility, which is one of the focuses for draft-08.

I could link some of the issues around this, but I'm on my phone, and I don't know the numbers off the top of my head.  If no one else comes in to do it before I can, I'll add some links when I can get to a computer.

**Comment by GEricson** [comment]
@gregsdennis Thanks in advance for the references.   Extension is certainly another way to go.
One question is the role of $schema.  I've used $schema as described above and it passes validation and is a useful way to develop instance documents with real-time validation.  However, the community that I'm working with is convinced this is a misuse of $schema.  I'm looking for a conformant way to get this benefit.

**Comment by handrews** [comment]
@GEricson `$schema` use in instance documents is not part of the JSON Schema specification, as it would contradict the guiding principle that JSON Schema does not, in any way, restrict instance documents (in terms of type, size, reserved properties, etc.).  It MUST be possible to use JSON Schema with any JSON document (although some uses are more useful than others, of course).

However, I have seen applications adopt `$schema` in the instance as their own convention, and nothing in JSON Schema prevents you from doing so.  But you cannot expect JSON Schema tooling, in general, to offer support for it.  At most, it can be an opt-in non-default behavior that you could configure.  I don't believe it is supported.

Personally, I would probably recommend using some other keyword to reduce confusion.  Using `$schema` suggests direct JSON Schema support, which is not the case.  Using a similar-ish property name that is _not_ a JSON Schema keyword would be suggestive without causing confusion, IMHO.

`$schema` should be thought of as an instruction to the JSON Schema implementation of what specific version (e.g draft-04 vs draft-07) and vocabulary (e.g. validation vs hyper-schema) is in use _in the schema containing the `$schema` keyword_, and therefore how to process that schema.

------

Regarding your other questions, @gregsdennis is correct that your mobile home schema is an "extension" of the generic home schema.  Neither are meta-schemas, as neither describe themselves.

I put "extension" in quotes because, while the term gets used with JSON Schema rather frequently, it's a bit misleading.  I suspect this is why @gregsdennis actually said **"extensibility"** rather than "extension"- a subtle but accurate distinction.

JSON Schema is a constraint system, so "extending" a schema further constrains it (the empty schema has no constraints- it allows everything).  Most people are thinking of OO when they say "extends", and OO extensions tend to add functionality.

You would generally use a `$ref` in your mobile home schema to refer to the generic house schema.  In all published drafts of JSON Schema, `$ref` cannot have adjacent keywords, so you need to wrap it in an `allOf` (this may be relaxed in the next draft but that's irrelevant if you're all the way back on draft-04, which is three major drafts behind the current state of things).

**Comment by gregsdennis** [comment]
Pretty much all of the issues with the [validation](https://github.com/json-schema-org/json-schema-spec/issues?q=is%3Aopen+is%3Aissue+label%3Avocabulary) label deal with extending schemas in some way.  This is still a topic very much in discussion.  Please review these and feel free to join in and ask questions.

Thanks for the additional details @handrews.

**Comment by handrews** [comment]
@GEricson The vocabulary stuff is mostly about extending schema vocabularies (and therefore self-descriptive meta-schemas).  There are some situations where some of those tools would be useful for regular schemas, but those are relatively rare and involve recursive structures.  In most cases, `allOf` and `$ref` are sufficient.  We would have to see details of the schemas involved to say more about it.

**Comment by GEricson** [comment]
@handrews, @gregsdennis : Thank you for your responses.  
A couple of additional questions:
1.  When developing a schema document, like the generic house schema document.  This is both a schema document for house instance documents and an instance of the draft schema document.  In this case, should $schema be used?  If so, what should it reference?
2. Is there a keyword for use in an instance document with a value that identifies the schema document to validate against?  (Using the "allOf" keyword in the instance document does not seem to constrain the structure of that instance document.)

I will look at the vocabulary issues.  Thanks again.

**Comment by handrews** [comment]
@GEricson `$schema` is a keyword for use in schema documents, to indicate the schema's own schema.  Which is itself a schema, so it will also use `$schema` for *it's* schema.  A schema for a schema is a meta-schema.  Usually, a schema's schema will have a `$schema` that points to itself (the two standard meta-schemas do this).  That is how the `$schema` chain terminates.

So your house schema will probably have a `$schema` pointing to `http://json-schema.org/draft-04/schema` (or ideally a newer draft), which has a `$schema` that points to itself.

There are ***absolutely no instance document keywords*** related to JSON Schema.  None.  Zero.  A fundamental design choice of JSON Schema is that instance documents are not constrained in any way.

**Comment by GEricson** [comment]
@handrews: Thanks.  I had not understood the termination policy.
