### ISSUE TITLE
Add example(s) to json-schema-validation.html

### ISSUE THREAD

**Issue by MNF** [json-schema-org/json-schema-spec#664]
The page https://json-schema.org/latest/json-schema-validation.html describes many different keywords, but there is no example, how such keywords are used.   
It can be one schema example,which includes all described  keywords or (better, but more time consuming) multiple examples, showing variations of possible values for different keywords.

**Comment by awwright** [comment]
* For users, we have http://json-schema.org/understanding-json-schema/ which includes numerous examples and instructions for multiple programming languages
* For implementors, we have the [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite), the definitive reference of examples and their expected behavior

**Comment by awwright** [comment]
We've tended to find that if there's too much informative/non-normative content in the official specification (descriptions of why things are, or examples), it tends to drown out the authoritative/normative content.

I think we can consider adding some examples, if there's particular areas that need improvement.

Do you have examples of other RFCs that provide more examples?

We do realize the need for examples, so we separately publish a few different documents with this goal:

* For users, we have http://json-schema.org/understanding-json-schema/ which includes numerous examples and instructions for multiple programming languages
* For implementors, we have the [JSON Schema Test Suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite), the definitive reference of examples and their expected behavior

Is this suitable for you?

**Comment by Relequestual** [comment]
@MNF Thanks for raising this issue.
I can understand that reading normative specification language is hard, and it's not nessecerily that helpful for thos wishing to actually write JSON Schema documents. It's a hard skill to learn, and takes time.

Having complete informative information in with the normative specification document is asking for trouble! This is from experience.

If you would like some more examples, please be specific, and ask for them over on the [Understanding JSON Schema repo](https://github.com/json-schema-org/understanding-json-schema), which is the associated informative information for this specification.

**Comment by MNF** [comment]
@awwright , 
example of RFC with more non-normative examples is 
https://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse where multiple sections contain
`The following is a non-normative example request`

@Relequestual , I didn’t ask to have “complete informative information”. However
I came to the document from google and expected to have al least one example of “additionalProperties“ within the document.

Also it will be good to have in the same document (probably in “Note for readers”) the references to 
https://github.com/json-schema-org/understanding-json-schema and 
https://github.com/json-schema-org/JSON-Schema-Test-Suite as you did in your replies.
