### ISSUE TITLE
To much {"type" : "sometype"} everything.

### ISSUE THREAD

**Issue by Crutchmaster** [json-schema-org/json-schema-spec#731]
How about using string as shortcut for {"type" : "sometype"}?
For example
```
{
  "type": "object",
  "properties": {
    "number":      { "type": "number" },
    "street_name": { "type": "string" },
    "street_type": { "type": "string",
                     "enum": ["Street", "Avenue", "Boulevard"]
                   }
  }
}
```
will look like
```
{
  "type": "object",
  "properties": {
    "number":      "number",
    "street_name": "string",
    "street_type": { "type" : "string",
                     "enum": ["Street", "Avenue", "Boulevard"]
                   }
  }
}
```
Level 2: comma-separated properties for same types:
```
{ 
  "type" : "object",
  "properties": {
    "id,year,month,day,amount" : "number",
    "company_name,product_name" : "string"
  }
}
```

**Comment by erosb** [comment]
I don't mind the first version (schemas can already be objects or booleans, including strings with straightforward semantics is not a big deal).

The second version ("Level 2") would be ambiguous in cases when property names can contain commas, so definitely no.

**Comment by Crutchmaster** [comment]
Hmm. May be regexp in keys?

**Comment by Julian** [comment]
Going to be bold and just close this -- it's extremely unlikely to happen for many many reasons, and the mechanisms are there (both previously and particularly now with vocabularies) for other, simpler specs to sit on top of JSON Schema and support this kind of thing.

See e.g. the way something like [vega lite](https://vega.github.io/vega-lite/) sits on top of [vega](https://vega.github.io/vega/), supports fewer features, but in shorter ways.

**Comment by awwright** [comment]
This comes up from time to time and maybe I should write a little article about it, but there's two arguments:

One: Using strings where a schema is expected was historically used to reference another schema by URI reference. I don't know if there's any implementations that still support this, but this would break those.

Two: This seems like premature optimization, you have to completely rewrite the schema if you want to add an additional property—if you want readability, use a DSL: http://json-schema.org/implementations.html#schema-to-schema

**Comment by handrews** [comment]
I'll weigh in to agree with @Julian and @awwright .  

The boolean schemas were added because:

1. They were already allowed for two keywords, and it made things easier (and made those two keywords more understandable) to generalize it.
2. The booleans convey a common intent (allow all / disallow all) that is not as easy to programmatically detect otherwise, or as immediately clear to a human reader.

Verbosity wasn't a concern there- `true` is actually longer than `{}`

----------

I don't think that vocabularies would allow replacing an entire schema with a string, but I'm still skeptical of that shortcut.  It is one that could be easily managed as a preprocessing step if you're mostly concerned about author convenience.
