### ISSUE TITLE
Question: Draft 08 vs Draft 07

### ISSUE THREAD

**Issue by fmvilas** [json-schema-org/json-schema-spec#761]
Hi folks!

Quick question: Are there any breaking changes from Draft 07 to Draft 08? If Draft 08 is not yet completed, are there any breaking changes so far or do you think there will be?

Thanks!

**Comment by Relequestual** [comment]
Easiest thing to do is read all of http://json-schema.org/work-in-progress
Each spec document lists a changelog.

**Comment by handrews** [comment]
@fmvilas there will at some point be a nicer page on json-schema.org giving migration guidance, as there has been for the last two drafts.  But the changelog in the spec documents should be enough to figure out the basics.

We are getting very close on draft-08, I just posted #762 to address some confusion, and will be following up with a few more things.  This is in support of efforts in #756 as well.  All of this being the result of someone other than me trying to actually write a vocabulary for the first time 😄

**Comment by handrews** [comment]
The only other thing that has come up is a vague idea about deprecating (but *NOT* at this point removing or discouraging) `format` in favor of modular vocabularies.  This is because `format` is very confusing in its optional implementation requirements, and we would love to see people try out vocabularies as an alternative.

If I were defining all non-core keywords from scratch but with vocabularies available, I would not define something like `format`.  Instead I'd encourage people to create vocabularies for describing (for example) networking concepts, or date/time concepts, etc.

**Comment by handrews** [comment]
I should file an issue for that so people can freak out about it appropriately 😛

**Comment by fmvilas** [comment]
Thanks for the hints. Keep up the great work.
