### ISSUE TITLE
Missing contains in validation vocabulary?

### ISSUE THREAD

**Issue by fmvilas** [json-schema-org/json-schema-spec#766]
Hi! I was reading the work-in-progress validation vocabulary and realized that `contains` is missing [here](https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-validation.xml#L362). Hope it helps.

**Comment by handrews** [comment]
@fmvilas it's now in the Core spec as part of the [applicator vocabulary](http://json-schema.org/work-in-progress/WIP-jsonschema-core.html#rfc.section.12.3.1.4), since it takes a schema rather than a literal value.

This will probably need a FAQ entry as it's one that feels like an assertion but it's not: conceptually, the keyword applies the schema to every element of the array, and ORs their validation results to produce its validation result.  Any keyword that is the result of apply boolean logic to the results of subschema applications is considered an applicator.

**Comment by handrews** [comment]
hmm... I'm just realizing we may have left something out about what that implies for annotation collection.  I'll check tomorrow but re-opening this to remind me.

**Comment by awwright** [comment]
That does seem like kind of an arbitrary way of categorizing it, though: "additionalItems" is mostly the same thing as "contains", except in how it propagates validation results. And if it doesn't produce annotation results, can it really be called an applicator?

**Comment by handrews** [comment]
@awwright it does produce annotation results.  That's what I need to go make sure is clear throughout (not just for `contains` but for all applicators).  But I'd just gotten home from a party last night and didn't feel like digging into it.

I'm not sure how this is arbitrary, though, that has always been the definition of an applicator.  In particular, it is exactly the reason why `dependencies` was split into `dependentRequired` (an assertion) and `dependentSchema` (an applicator).  This has been well-explored and thoroughly discussed in the past year.

**Comment by handrews** [comment]
Filed #768 for the clarification regarding annotations, so closing this again.
