### ISSUE TITLE
[draft 04] Dealing with contradictory constrains with anyOf/allOf

### ISSUE THREAD

**Issue by terazus** [json-schema-org/json-schema-spec#773]
Hello there,
What would happen if an allOf (or anyOf) reference points to two schemas that implement the same field but with different constraints?

Here is a schema that describes an object with a 'source' field that should be both a Person and an Organization (don't ask me why). However both Person and Organization have a different implementation of 'identifier', one being a string URL, the other a number.
In other words, i don't think it's possible to create data that is valid against that schema.
```{
 "id": "https://example.com/example_schema.json",
 "$schema": "http://json-schema.org/draft-04/schema",
 "type": "object",
 "definitions" : {
   "Person": {
       "required": ["identifier"],
       "properties": {
           "identifier": {"type":"string", "format":"uri"}
       }
   },
   "Organization": {
       "required": ["identifier"],
       "properties": {
           "identifier": {"type":"number"}
       }
   }
 },
 "properties": {
   "source": {
       "type":"object",
       "allOf": [
         {"$ref":"#/definitions/Person"},
         {"$ref":"#/definitions/Organization"}
       ]
   }
 },
 "required":["source"]
}```

I agree that this is stupidly written, it'd be easy to harmonizes. However, in real life, we rely on external schemas referenced with their absolute URL and onto which we have no control at all.

Is this an expected behavior? If not, what did I miss? If it is intended, would you have any recommendations to deal with these use-cases?

Best regards,

**Comment by Julian** [comment]
That schema fails on all instances, yes.

**Comment by handrews** [comment]
Yup, just like it is possible to write programs that don't do anything useful, it's possible to write schemas that are really elaborate ways of always failing.

Anyone who is publishing re-usable schemas should provide a way to file bugs on them, just like anyone who publishes a code library.

I'm going to close this because it is within the expected set of possible schemas, but please comment further if there is something more that you wanted to see addressed.
