### ISSUE TITLE
This url - https://json-schema.org/draft/2019-09/vocab/core doesn't work

### ISSUE THREAD

**Issue by opethe1st** [json-schema-org/json-schema-spec#815]
This url in the latest draft as defined here https://json-schema.org/draft/2019-09/schema. You can go to the url and check that this is one of the urls under "$vocabulary"

**Comment by opethe1st** [comment]
I could work on a PR if that works too.

**Comment by notEthan** [comment]
this URL is just an identifier which does not correspond to a document. it sort of corresponds to the meta document at https://json-schema.org/draft/2019-09/meta/core (referenced in the allOf property of the metaschema), though I can't quite explain the relationship.

I was confused by this for a while too. I think it needs improved clarification in the spec.

**Comment by opethe1st** [comment]
I know from the spec it doesn't have to correspond to a retrievable document but this particular case looked like an oversight to me. 
Plus it is actually better develop UX to be able to click in an editor on the url and get the document being referenced. 

RIght now, I would have to jump through hoops to find the validation schema.

**Comment by handrews** [comment]
> I know from the spec it doesn't have to correspond to a retrievable document but this particular case looked like an oversight to me.

It doesn't correspond to a retrievable document because we don't know what to put in the document until people try to implement the vocabulary feature and tell us what should go there.

Some of the inconclusive discussions involved can be found at #602 and at https://github.com/json-schema-org/json-schema-spec/issues/563#issuecomment-438869464
