### ISSUE TITLE
spec: should the version be -05?

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#82]
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L17
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-validation.xml#L18
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-hyperschema.xml#L21

**Comment by awwright** [comment]
The way we're going to have to upload the new I-Ds means a change in the document name, which means re-starting the sequence at -00. The new series can be marked as a replacement for the old series, this is a reasonably common occurrence as documents change editors and working groups.

As it stands now, the documents are all numbered differently anyways. Presently we have three different document numbers, I suppose going forward we'll have four: One for the collection of meta-schemas, and one per I-D.

This might set off some OCD to begin with, but since we plan on releasing I-Ds frequently, we don't want to also have to release a new numbered set of meta-schemas in the course of doing so, so this is probably better anyways.

**Comment by epoberezkin** [comment]
Ok, so we need to mark them as a replacement then? So it is clear what standard is replaced with this one? I think it's important both to indicate continuity but also the maturity of the standard... I would continue numbering, but I'm not that precious about it as long as it is clear what it supersedes.

**Comment by awwright** [comment]
yeah, it's just something I have to ask the IETF to do. I was just reading an I-D that had changed authors three times so far... I forget what it was

**Comment by awwright** [comment]
@epoberezkin If this answers your question you can go ahead and close this out, if you would please.

**Comment by Relequestual** [comment]
You mean CDO...
