### ISSUE TITLE
why schema keyword value can not be a path ?

### ISSUE THREAD

**Issue by DaiKiQi** [json-schema-org/json-schema-spec#826]
I have recently used json schema to help validate json data.
but i found that its hard to validate cascade relation.
for example：

          "ageRange": {
            "minAge": 20,
            "maxAge": 30
          }
I want to limit 18<minAge<maxAge<50. its hard to limit minAge<maxAge. Because keyword minimum's value must be number.
why schema keyword value can not be a path？like this:

"maxAge": {
              "minimum": "$.ageRange.minAge",
              "exclusiveMaximum": 50
            }
do you have any idea to implement this？

**Comment by DaiKiQi** [comment]
@stevehu

**Comment by awwright** [comment]
The quick answer is that this is not "structural validation", it is "data
consistency validation" - it is comparing one piece of data against another.

For example, verifying that a user ID exists in a database is the same kind
of validation as your example: It is comparing one value against some other
data.

JSON Schema validation only targets structural validation: a rule that's
applied the same way to every value, without using any other data (not
including the schema itself, of course).

In part, data consistency is difficult to implement. It would effectively
turn JSON Schema into a scripting language. And in my view, this is best
left up to actual scripting languages.

Give me a day, I will post a lengthier explanation, with some alternate
ways to accomplish what you're looking for.

**Comment by DaiKiQi** [comment]
I have implement in min max keyword with @stevehu's validator. actually it diffrent from others.
It can not be initailized before you really validate the data, beacause the infomation is contained in the data.

**Comment by DaiKiQi** [comment]
Is this example "structural validation" or "data consistency validation"？
```json
{
  "honors": [
    {
      "date": "2018-01-01",
      "title": "honor1"
    },
    {
      "date": "2019-01-01",
      "desc": "honor2"
    },
    {
      "date": "2020-01-01",
      "desc": "honor3"
    }
  ]
}
```
I want to limit the honor items' date increasing. I have no idea to descript with present schema. But if using the path value and the keyword order. It can be realized:
```json
{
  "type": "array",
  "items": {
    "required": [
      "date",
      "title"
    ]
  },
  "order": "$.honors.date"
}
```
It actually use the the json data itself to validate. But *structural validation* need json data too. We can compare the schema to a function with parameter json data and returning boolean. But using value path does not need other parameter. Is this really make diffrent?

**Comment by awwright** [comment]
@DaiKiQi I think that would be data consistency validation. In order to test if the data is valid, you have to look up the next value; or you have to hold the previous record in memory. And JSON Schema validation isn't designed to require this.

I wrote https://github.com/json-schema-org/json-schema-spec/wiki/Scope-of-JSON-Schema-Validation hopefully this answers some of your questions. It's a common question, but it hasn't been well explained.

**Comment by Relequestual** [comment]
@DaiKiQi posting the same question to our google group is not going to get a different response or reach different people. Sorry.

**Comment by DaiKiQi** [comment]
@Relequestual I just didn't find a right place to discuss this. Sorry, too.

**Comment by Relequestual** [comment]
Hi @DaiKiQi This is the right place to discuss, or if you want more discussion, please join our slack server from our website.

**Comment by handrews** [comment]
What is the desired outcome here?  If this is a question about adding data consistency validation, that's addressed in @awwright 's page that he linked to, as well as in various other issues with the `$data` tag.

**Comment by awwright** [comment]
Well to answer the original question:

> do you have any idea to implement this？

Right now, the answer is "You should implement this in your application, since this is outside the scope of JSON Schema."

Extended reasoning for this is provided at [Scope of JSON Schema Validation](https://github.com/json-schema-org/json-schema-spec/wiki/Scope-of-JSON-Schema-Validation). Note the bottom "Annotations" section, maybe there can be some way to say "... And there's other requirements applied by the server, not described here". If you have a specific proposal for this, it might be best proposed in a new issue.

**Comment by handrews** [comment]
@awwright yeah that sounds like a solid answer, and there hasn't been a significant comment from the poster for a month or so, so I'm going to close this.  As you say, if there's a real issue for the spec in here somewhere, it should be filed on its own.
