### ISSUE TITLE
How to reference JSON schema from JSON data?

### ISSUE THREAD

**Issue by goldingdamien** [json-schema-org/json-schema-spec#828]
How to reference JSON schema from JSON data?

I can see a $schema property for referencing the JSON schema version in a JSON schema file, but I can not find a way to reference the JSON schema from a standard JSON data file.
For example, in XML, the following seems to be what I would want: https://www.w3schools.com/xml/schema_howto.asp

Please, can you provide a basic example of how to achieve this? Plus any information on how validation works for this.
Regards.

**Comment by awwright** [comment]
Unlike XML, JSON does not define a standard way to do this. This information is usually known out-of-bound, in some fashion.

If your application is validating input, there's no need for the JSON file to declare the schema it's an instance of: Either it's within the bounds that your application understands, or it's not.

If your JSON file is declaring how an application should process it, this is what a media type is for; consider creating a media type underneath the vendor or personal tree.

**Comment by localheinz** [comment]
Would be nice if this were possible in a standardized way.

This could help with

- validation
- auto-completion

**Comment by Relequestual** [comment]
I'm locking this issue. We are aware of it and how it could be beneficial.
I will have a discussion to see how we can flag issues for consideration later down the line.

**Comment by glen-84** [comment]
I don't see how this is possible, actually.

`"$schema"` is a valid JSON key, which means that any existing (or future) system may be using it, for potentially different purposes – it may not reference a JSON schema document, and it may not even reference a URL.

It's a chicken/egg scenario – you need a schema to know that a specific document has this `$schema` key with a specific format/purpose, and you can't load that schema via this key until that information is known, so it has to be loaded out-of-band. Unless I'm missing something?

The only (somewhat hacky) way of implementing this would be to use a _really_ uncommon/specific key name, like the URL to the JSON schema schema:

```json
{
    "http://json-schema.org/schema#": "https://getcomposer.org/schema.json"
}
```

... but that's possibly not ideal.

This is just another one of the limitations of the JSON format.

**Comment by Relequestual** [comment]
Right. There's no ideal solution to this.
In the spec we have defined a way when the data is part an HTTP response, by setting a header, we haven't defined anything for this outside of an HTTP request for those and a number of other reasons. We've discussed it quite a lot. We may discuss it again later, but not right now.
I'm going to lock this issue for now.

**Comment by Relequestual** [comment]
Movin this to next draft. Doesn't need to be resolved as part of the patch draft

**Comment by about-code** [comment]
> I don't see how this is possible, actually.
> 
> `"$schema"` is a valid JSON key, which means that any existing (or future) system may be using it, for potentially different purposes – it may not reference a JSON schema document, and it may not even reference a URL.
>
> [...]
> 
> The only (somewhat hacky) way of implementing this would be to use a _really_ uncommon/specific key name, like the URL to the JSON schema schema:
>
> ```json
> {
>     "http://json-schema.org/schema#": "https://getcomposer.org/schema.json"
> }
> ```
>
> ... but that's possibly not ideal.
>
> This is just another one of the limitations of the JSON format.
>
> _Originally posted by @glen-84 in https://github.com/json-schema-org/json-schema-spec/issues/828#issuecomment-572626261_

First of all I think the problem of having no upfront context in JSON is the same which JSON-LD had on the one hand and aims to solve on the other. JSON-LD itself decided to standardize the `@context` keyword regardless of other possible uses.

*But* that doesn't mean JSON-Schema must go down the same path and standardize it's own semantically uninterpretable `$schema` attribute. Rather it could consider the *chicken-egg-problem* solved and solve its own *contextual problem* in exactly the "hacky" way Glen-84 proposed - by specifing a property as a URI because *that is exactly how JSON-LD looks at Linked Data and JSON properties*. It maps ambiguous properties into a semantically meaningful context. 

So let's first assume there's `$schema` and many instances use it today to denote a schema location:

```json
{
   "$schema": "https://getcomposer.org/schema.json"
}
```
This completely relies on a non-standarized convention-based *interpretation* of the `$schema` property. JSON-LD first acknowledged that there are a lot of JSON documents and APIs out there with properties that are - technically - not meaningful but interpreted by implicit understanding of their semantics. So the idea to give them explicit unique semantic meaning was to define a standard for mapping/projecting property names onto URIs.

So to make `$schema` semantically meaningful with JSON-LD we would add 

```json
{
   "@context": {  "$schema": "http://json-schema.org/schema#"  },
   "$schema": "https://getcomposer.org/schema.json"
}
```

See [JSON-LD Playground's Compacted View](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22%24schema%22%3A%22http%3A%2F%2Fjson-schema.org%2Fschema%23%22%7D%2C%22%24schema%22%3A%22https%3A%2F%2Fgetcomposer.org%2Fschema.json%22%7D&context=%7B%7D) how this were identical to writing

```json
{
    "http://json-schema.org/schema#": "https://getcomposer.org/schema.json"
}
```

So the message is: you are able to avoid standardizing a *particular* property name like `$schema` whose *implicit* interpretations could change over time or vary from one context to another. Still you can standardize a URI with explicit semantics *of being the link between an instance document and a (JSON-)schema*. It's then up to tooling vendors whether they continue implicitely interpreting `$schema` as an alias for the Standard URI or whether they ask users to become explicit which of their properties semantically stands for a schema reference - either by expecting the property name to be the URI or requiring a JSON-LD contextual mapping from their own arbitrary name onto the standardized URI.

**Comment by awwright** [comment]
@about-code 

> First of all I think the problem of having no upfront context in JSON is the same which JSON-LD had on the one hand and aims to solve on the other. JSON-LD itself decided to standardize the @context keyword regardless of other possible uses.

Can you clarify which question is this answering? By "context", do you mean the media type semantics?

JSON documents (`application/json` documents) don't have any meaning _by themselves_ (beyond the underlying data structure). Though if both parties agree to a certain interpretation, they can exchange useful data. But there is no standard way to do this.

In contrast, in JSON-LD (`application/ld+json`), the `@context` property has a standardized meaning.

And some media types have an option to extend the semantics, to introduce a JSON Schema keyword.

---

There's nothing we can change about `application/json`, but we can document alternative solutions:

* A new media type (`application/instance+json`)
* Updating an existing media type (one that is forward compatible with new features like this)
* Out-of-band information, like the HTTP Link header

**Comment by about-code** [comment]
> >First of all I think the problem of having no upfront context in JSON is the same which JSON-LD had on the one hand and aims to solve on the other. JSON-LD itself decided to standardize the @context keyword regardless of other possible uses.
>
> Can you clarify which question is this answering? By "context", do you mean the media type semantics?

@awwright Your hint on the `application/ld+json` media type is fair. Indeed for JSON-LD *due to having a particular media type* there is only a single meaning of `@context` when that particular media type is provided. This is some kind of *context* provided *out-of-band* as you correctly pointed out earlier (in that sense, me writing *[...] regardless of other possible uses* was a bit misleading, probably).

At the moment I am not sure I could decide for a media type `application/instance+json` for schema *instances*, though. After all even JSON documents which do not refer to a concrete schema are usually implicitly instance of some schema. The mere fact of being an instance of *some schema* doesn't qualify for a specific media type, for me, personally.  Usually it is *concrete schemas* or processing models I see media types are being registered for. Schema validation may be some kind of a processing model, but I am not sure.

If there were `application/geo+json` instance documents, for example, I would expect that both parties want to keep on using the `application/geo+json` media type, not use some `application/instance+json` media type. Are you refering to that situation when proposing to *upgrade existing media types*? So you mean to upgrade media type specifications to make a commitment to `$schema`? Wouldn't it impose on any future JSONish media types to make the same commitment? Just out of curiosity: what if they were lazy or reluctant? Were users of their media type permitted to use `$schema`? 

The reason why I like the idea of @glen-84 is, that it builds on some core idea of W3C standards which is the idea of using *URIs to encode standardized semantics, unambiguously*. While it looks weird at first to use an URI as a JSON property name, JSON-LD was actually just mentioned to show that it is not *that* weird. But that's all to say about JSON-LD. I don't see that JSON-Schema would make any commitment to JSON-LD by deciding for an URI instead of `$schema`.  And W3C should not be an argument, either. 

I just think an URI had some nice consequences:

- it were a property name which JSON-Schema could put a claim on because it owns the URI domain (the DNS registry is the replacement for the IANA registry, here)
- an URI wouldn't require a media type but any tooling vendor could just test for the given property being present and apply a certain processing model
- JSON-Schema could still decide to make a commitment to `$schema` as an *alias* if it wanted to and adoption rate for the URI were slow or caused interoperability issues which I don't see at the moment. 

XML namespaces have been URIs as well. They allow merging XML documents from arbitrary namespaces without naming collisions. For me, this issue is the same problem category: merging arbitrary instance documents with a document

~~~
{
   "$schema": "..."
}
~~~

or the URI equivalent of it

~~~
"http://json-schema.org/#$schema": "..."
~~~

----
Disclaimer: I am not acting on behalf of any organisation or standards body but out of personal motivation, only.

**Comment by awwright** [comment]
@about-code Can you clarify what, exactly, you're proposing?

> The mere fact of being an instance of some schema doesn't qualify for a specific media type, for me, personally.

My point is since we can't change how `application/json` works, we can register a new media type. This new one can reserve the property `$schema` to point to a schema that the rest of the instance is supposed to follow.

We could also propose a revision of existing media types such as `application/collection+json`.

Or we can more comprehensively document how schemas are referenced out-of-band.

But in the end, there's not too many solutions available to us.

**Comment by about-code** [comment]
> Can you clarify what, exactly, you're proposing?

Okay, I am proposing:

- to *standardize* a property name which is *syntactically* an URI like *for example* `http://json-schema.org/#schema` and which *semantically* uniquely represents the meaning of being a schema reference
- it must always be possible to use *that URI* in instance documents instead of `$schema` and JSON schema validators should always check a JSON document for the presence of a property whose name matches this URI

In addition to that, I am not proposing myself but neither opposing *your ideas*:

1. to register a particular media type which when being used permits the use of `$schema` *as an alias property name* for the given URI
1. to add documentation for out-of-band references which allow for omitting any reference property within the instance document

Adding to 1.:
Some recipient of an instance document *and* media type metadata must replace the `$schema` property with the URI prior to passing the instance document to a JSON-Schema processor *unless* the JSON-Schema processor accepts a media-type parameter in addition to the instance document. The processor then may or may not translate `$schema` internally.

Adding to 2.:
An out-of-band reference *may* be an HTTP link header where the formerly specified URI acts as a *link relation*.

@awwright hope that add some clarification. Sorry for the inconvenience.

**Comment by gregsdennis** [comment]
I don't think defining this is within the domain of JSON Schema.  We define the schema itself, which is a way to describe raw JSON instances.  We can't specify the content of the instance.

This seems like an application-level concern to me and not the responsibility of JSON Schema.

**Comment by about-code** [comment]
I think I understand the wariness. But I think there's also a need given the fact how widely `$schema` is already being used. I would argue that it still remains an application-level decision to make use of it. But JSON-Schema could assist applications who want to address the concern (which is linking instances with a schema) by providing guidance or standardization on how to do it in a way that is most likely compatible with tooling. I don't see (and don't prefer to see) another authority to fill the gap, actually. Yet, I feel quite uncomfortable with leaving this unspecified, given that I am a user of `$schema` myself.

There's something similar in XML Schema which describes the [`xsi:schemaLocation`][xsd] attribute for the same purpose:

> *In an instance document, the attribute xsi:schemaLocation provides *hints from the author to a processor* regarding the location of schema documents. The author warrants that these schema documents are relevant to checking the validity of the document content [...]* [XML Schema Tutorial Part 0][xsd]

So even if it may not make it into the actual specification. Giving some authoritative guidance via an addendum may be an option as well.

**Comment by awwright** [comment]
> to standardize a property name

> But I think there's also a need given the fact how widely `$schema` is already being used.

It's not a matter of how widely a property name is being used. We can't make _any_ property name special _at all_, as far as JSON syntax is concerned. Plain JSON doesn't have directives the same way XML or JSON-LD does.

**Comment by gregsdennis** [comment]
I could see something along the lines of

```json
{
  "schema": "https://uri.to/schema",
  "payload": {
    "json": "data"
  }
}
```

But this would require that everybody wrap their instances in an object.

---

The primary problem is with JSON itself.  It's a really good format for communicating data, but it has no mechanism for communicating metadata, and the schema is metadata.

As a comparison, XML doesn't have this problem because it has attributes. Any value requires a node to which any number of attributes can be added.  But with JSON, `true`, `42`, and `[]` are valid values, none of which can take additional information (like an attribute).

We've experienced this in other areas as well.  For example, we'd like to use namespaces to specify which vocabulary a keyword comes from when multiple vocabs are used, but we haven't found a good mechanism for it.

**Comment by about-code** [comment]
> The primary problem is with JSON itself. It's a really good format for communicating data, but it has no mechanism for communicating metadata, and the schema is metadata. @gregsdennis 

Syntax is not what I see the issue being about. When I am refering to how widely `$schema` is used its because of me acknowledging that it serves *a need* and (naming aside) there is *a pragmatic approach* of embedding metadata alongside the actual data that people seem to be okay with, in many cases. In my opinion they have already "voted with their feet" (resp. fingers) on the syntax/metadata matter. If we could agree on this as a bottom line then we may be able to skip a discussion about the differences of JSON and XML syntax.

Because dissatisfying for me is not the syntax which others have found to suite their needs but the fact that tooling vendors (ISVs and even big ones) currently *hardcode* a meaning of the name `$schema` as being a *reference to a JSON-Schema* without clarifying the circumstances under which it is sane to do so. That's like ignoring completely that there are other JSONish schema languages like Apache Avro IDL and it may not be a solution to invent a new name for every schema language.

> It's not a matter of how widely a property name is being used. We can't make any property name special at all, as far as JSON syntax is concerned. @awwright 

I aggree with you due to your use of *property name*. If we do not want to make any commitment on a particular *property* and syntax what about geting rid of *property name* and talk about *names*, only:

> It's not a matter of how widely a [...] name is being used. We can't make any [...] name special at all, as far as JSON syntax is concerned.

If you had said this, I wouldn't have agreed. Because we *can* make special names and define their meaning once we are fine with the general idea of URIs and that every authority may define any name with any meaning under its own domain. That's why I am proposing to standardize an URI and give it the desired meaning.

**I am proposing (rev.2):**

- to standardize a <del>property</del> name which is syntactically an URI like *for example* http://json-schema.org/#$schema and which semantically uniquely represents the meaning of being a schema reference from an instance document to its schema

In addition to that, I am not proposing myself but neither opposing:

1. to register a particular media type which when being used permits the use of `$schema` *as an alias <del>property name</del>* for the given URI (see [14.2](http://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.14.2))
1. to add documentation for out-of-band references which allow for omitting any reference <del>property</del> within the instance document (see  [9.5.1.1](http://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.9.5.1.1))

Adding to 1.:
Some recipient of an instance document *and* media type metadata must replace <del>the</del> `$schema` <del>property</del> with the URI prior to passing the instance document to a JSON-Schema processor *unless* the JSON-Schema processor accepts a media-type parameter in addition to the instance document. The processor then may or may not translate `$schema` internally.

If both <del>properties</del> names are available, the URI and its alias <del>exist on an instance document</del> then the URI takes precedence.

Adding to 2.:
An out-of-band reference *may* be an HTTP link header (see section [9.5.1.1](http://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.9.5.1.1)).

**Comment by gregsdennis** [comment]
Your proposal still only applies to objects, and this is the inherent problem that you're not addressing.  We need a solution that works for _all_ JSON instances.  How would these documents specify a schema?

```json
"strings are documents, too"
[ "one", "two", "three" ]
```

**Comment by awwright** [comment]
@about-code

> Syntax is not what I see the issue being about.

That's what this issue is about, though. JSON is a syntax. There's no way to add semantics to that syntax without breaking it.

> When I am refering to how widely $schema is used it's because of me acknowledging that it serves a need and (naming aside) there is a pragmatic approach of embedding metadata alongside the actual data that people seem to be okay with, in many cases. In my opinion they have already "voted with their feet" (resp. fingers) on the syntax/metadata matter. If we could agree on this as a bottom line then we may be able to skip a discussion about the differences of JSON and XML syntax.

We're not adopting `$schema` either. If someone wants to use that, that's their problem, but it's not a standard.

> to standardize a name which is syntactically an URI like for example `http://json-schema.org/#$schema` and which semantically uniquely represents the meaning of being a schema reference from an instance document to its schema

This isn't possible. It doesn't matter how many qualifiers you put on it. JSON doesn't have a concept of a URI, so a string that is "syntactically a URI" doesn't accomplish anything for us.

**Comment by about-code** [comment]
>>  to standardize a name which is syntactically an URI like for example http://json-schema.org/#$schema and which semantically uniquely represents the meaning of being a schema reference from an instance document to its schema
>
> This isn't possible. 

@awwright JSON-Schema has already standardized a few other names using URI syntax. Of course it were possible if we could get over the syntax debate for the moment and focus on naming and semantics, first. Because citing cases where JSON syntax may not allow applying a standardized name does not rule out the cases where having a standardized name for the matter would help. Media types aren't applicable in every situation, either. Still they have been specified because they help in situations where a Hypermedia protocol is being used. If there are documents like `"strings are documents, too"` and JSON syntax doesn't permit using a name in that situation to refer to the document schema, then this is not the business of JSON-Schema. Solving this is indeed the kind of application-level decision you referred to, earlier, and an application then may decide to choose a Link Header.

> It doesn't matter how many qualifiers you put on it. JSON doesn't have a concept of a URI, so a string that is "syntactically a URI" doesn't accomplish anything for us.

But JSON has syntactical positions where using a *name* (key) is possible and URIs are names and having a standardized name to use in cases where JSON allows declaring a name does accomplish something for JSON-Schema *users*. Otherwise there wouldn't be `$schema` at all. And I have no doubts you know that the authority part of an URI *matters* because it allows the domain owner to occupy a name solely and standardize the name's meaning. I don't see anyone on the web, questioning that. That's what URIs are about.

>  If someone wants to use that, that's their problem

If that's your position anyways then you should not have a problem with standardizing *a name* and let people decide when to use it. If people want to use that, that's their [benefit]. I don't expect a syntactical solution at all but I can't speak on behalf of anyone else, but me, either. So I think I made my points clear. There's nothing new I can add so I calm down.

**Comment by gregsdennis** [comment]
> ... standardizing a name...

This is what we've been saying.  We can't standardize a name.  That would be attempting to standardize something in JSON, over which we (as _JSON Schema_) have _no control_.  JSON Schema _uses_ JSON, but it _is not_ JSON.  We can't put requirements on JSON.  I don't know how to make this clearer.

Using `$schema` in an object instance is a convention.  It's fine to leave it that way.  It's like a naming convention in programming languages: it's a rule that most people tend to follow because it aids in readability, but it's not enforced by any compiler.

**Comment by karenetheridge** [comment]
FWIW, when I want to pass metadata along with a json data payload that I intend to be processed with a particular schema, I add HTTP headers (which *are* in the spec):

```
Link: <https://example.com/my-schema.json>; rel="describedby"
Content-Type: application/schema-instance+json
```

**Comment by awwright** [comment]
@about-code The best we can do is specify a link relation, and we already standardize on using "describedBy" and "profile". Any media type that allows embedding hyperlinks can automatically support referencing a JSON Schema this way.

> JSON-Schema has already standardized

We're not talking about JSON Schema keywords; we're talking about how we can _reference_ a JSON Schema from inside an _arbitrary_, plain JSON document.

There is no way to do this in ordinary, plain JSON. The entire value space in JSON is user-defined, and we can't make exceptions to that. We can't say "Except properties with this name, which has our standard meaning."

If you agree with this you need to admit it, and start your argument by saying that; because it's important to this topic, and I still don't understand what your point is.

> does not rule out the cases where having a standardized name for the matter would help

For JSON-based media types (like JSON-LD or collection+json), we can't even _suggest_ a standard way to do it. Each media type is going to have to decide the best way to reference JSON Schema documents, because each media type allocates the JSON value space differently.

For example, JSON-LD assigns special meaning to keys that look like URIs, but collection+json does not. The way those media types each reference a JSON Schema will vary accordingly.

And Hypermedia types already have standard ways to link to documents. Hydra and HAL both have their own ways to embed hyperlinks in JSON, they will want to use their technique rather than anything we specify.

> But JSON has syntactical positions where using a name (key) is possible and URIs are names and having a standardized name

Again, this thread is about plain JSON, and JSON doesn't have any special handling for key names that look like URIs. JSON handles it the same way as any other string, so there is no reason to do this.

**Comment by jdesrosiers** [comment]
I agree 100% with what @awwright and @gregsdennis are saying. We can't assign semantics to any property of a JSON instance. But, I think the argument @about-code has pivoted to is more about documenting a common an application design pattern so people are more likely to use the same pattern. I don't think it belongs in the spec but I could see it being documented on the website somewhere (maybe UJS) as a recommended pattern for cases that need to solve this problem and aren't using HTTP.

**Comment by gregsdennis** [comment]
I'm okay with documenting the convention, but we need to declare it as such.  We don't want to set precedent.

**Comment by selimnairb** [comment]
@jdesrosiers @gregsdennis Has there been any movement on this? I still don't see documentation of a non-HTTP convention for linking an instance document to one or more of its valid schemas in the [draft](https://json-schema.org/draft/2020-12/json-schema-core.html#name-associating-instances-and-s). Is the recommended convention to use `"$schema": "https://..."`? If so, it would be great to get this added to the draft, if not, what is the recommended convention? I am having a hard time finding example usages in the wild, so even references to such would be helpful. Thanks!

**Comment by gregsdennis** [comment]
@selimnairb as mentioned in the discussion above, we [can't prescribe](https://github.com/json-schema-org/json-schema-spec/issues/828#issuecomment-869950038) a mechanism that allows JSON to reference a schema.

Using `$schema` in the instance seems to be the convention that many applications have adopted, but again, we can't mandate that in our spec.  There was mention of putting some guidance for applications in documentation, but we haven't done that yet as we've been focused on other things.

**Comment by eleumik** [comment]
> As a TSC member of JSON Schema, the best DX thing you can push through would be the xsi:schemaLocation replacement because right now mapping files to their schema is some damn tomfoolery

https://news.ycombinator.com/item?id=41206145
