### ISSUE TITLE
spec: should we add previous (co) authors?

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#83]
I mean @kriszyp, @geraintluff, @fge?
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L21
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-validation.xml#L22
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-hyperschema.xml#L25

**Comment by awwright** [comment]
@epoberezkin They make an appearance in "Acknowledgments", I removed the inactive authors from the list because you get IETF mailings and such at those addresses. As far as I can tell, this is an appropriate way to deal with this case, but if there's precedent that shows otherwise, I can revert that.

**Comment by epoberezkin** [comment]
Ah, sorry, I didn't get there yet... Whatever works, as long as we give the credit to original authors. There may be some other issues I will submit as I read through the doc, it's easier that way... If I discover it's addressed further I'll just close.
