### ISSUE TITLE
"default" in dependency context

### ISSUE THREAD

**Issue by Finkman** [json-schema-org/json-schema-spec#872]
Sorry for the title. It was hard to find an appropriate headline.

Consider following schema which is picked from json-schema.org, and added an default value.

```js
{
  "type": "object",
  "properties": {
    "street_address": {
      "type": "string"
    },
    "country": {
      "enum": ["United States of America", "Canada"],
      "default": "Canada"
    }
  },
  "if": {
    "properties": { "country": { "const": "United States of America" } }
  },
  "then": {
    "properties": { "postal_code": { "pattern": "[0-9]{5}(-[0-9]{4})?" } }
  },
  "else": {
    "properties": { "postal_code": { "pattern": "[A-Z][0-9][A-Z] [0-9][A-Z][0-9]" } }
  }
}
```

Now, when validating:
```js
{
      "street_address": "24 Sussex Drive",
      "postal_code": "K1M 1M4"
}
```

the validator should take the *else* path, because the *country* defaults to `Canada` sets the pattern for the *postal_code*.
If it does not, it would end-up with an invalid document in case the document will be filled with default values afterwards.

Imho, the schemas postal_code pattern *logic* should default in the way the dependencies defaults.

**Comment by Relequestual** [comment]
Hey @Finkman. `default` is an ANNOTATION ONLY. JSON Schema the specification does not define any behaviour or expectations for this keyword.

Some libraries have implemented additional functionality that allows the use of this annotation keyword to do something, but that's up to them.

You may, for example, run validation, and if it fails, apply defaults and then re-run validation.
BUT, JSON Schema does not suggest or impose any such behaviour.

**Comment by Finkman** [comment]
Imho the meaning of an `default` implies more than an annotation, in generel. It tells to which value an value *defaults* in case no value was set.
So, knowing the schema, it is well defined that:

```js
{
  "street_address": "24 Sussex Drive"
}
```

brings `country` as well. Otherwise the value would default to `null`, which would the *actual* default value. And again, if that is the intention, *default* makes no sense as a keyword for this. It would be an alternative for `examples`, but not more.

> You may, for example, run validation, and if it fails, apply defaults and then re-run validation.
BUT, JSON Schema does not suggest or impose any such behaviour.

If I would follow your recommendation, I would:

- Not detect, that my example is invalid with `country` defaulted (as suggested by the schema) with `"postal_code": "K1M 1M4" or
- would become default values to apply, which will violate the schema.

It's a kind of shooting yourself in the foot, if the `default`is syntactically unrelated with the schema.

i would propose to make the schema aware of it's defaults and to instead of having a weak spec on `default` keyword:

> The default keyword specifies a default value for an item. JSON processing tools may use this information to provide a default value for a missing key/value pair, though many JSON schema validators simply ignore the default keyword. It should validate against the schema in which it resides, but that isn’t required.

make validation of default values against the schema an requirement and make evaluating the schema *with* default values obligatory. This would ship a schema with a *stronger* promise for it's validation.

**Comment by Relequestual** [comment]
> Imho the meaning of an default implies more than an annotation, in generel. It tells to which value an value defaults in case no value was set.

It doesn't matter what your opinion is in terms of what an implementation should do. The specification is clear, it's an annotation only. _JSON Schema should not modify your data._

If you try to make `default` do something, it gets very comple very quickly with anything more than a flat schema.

For example, say you have multiple possible valid defaults according to the schema? What now? Throw an error?

We DO specify that the default SHOULD be valid according to the schema. (SHOULD in caps means "you really better have a good reason if you don't" in spec speak).

Ultimatly, it is down to the application to decide how to process annotations.

Although interestingly, with annotation collection, if the value in the instance fails, the default annotation will not be collected. (Annotation collection only works for instances that pass validation, because annotations are attached to the specific instance, not generic about the schema. @handrews does this have any implications for what annotations are collected and what an implementation may do with them?) 

So really, it's down to the application to determine what it wants to do with the annotations. That isn't going to change.

**Comment by Finkman** [comment]
> It doesn't matter what your opinion is in terms of what an implementation should do. The specification is clear, it's an annotation only. _JSON Schema should not modify your data._

I agree that a schema should not modify data. i never said anything else. I mentioned my issue as a discussion about "Should default be more than an annotation?", or to help me understanding "default".

So my proposal is, that far, far in the future
```js
{
  "street_address": "24 Sussex Drive"
}
```
could / should carry the same information as
```js
{
  "street_address": "24 Sussex Drive",
  "country": "Canada"
}
```
_without_ modifying data. If "default" would be more than an annotation, the content (in sens of information) would equivalent.

> If you try to make default do something, it gets very comple very quickly with anything more than a flat schema.

and if you don't it might get complicated on the consumer side, the application that interprets a json document which has been validated. Moreover, it's a weak argument not to take defaults in to account because it gets to complicated.

> For example, say you have multiple possible valid defaults according to the schema? What now? Throw an error?

I must confess, there is a lack of knowledge on my side, since I have no idea what mulitple defaults could be. In every system / programming language / logic there is only one default state.

> We DO specify that the default SHOULD be valid according to the schema. (SHOULD in caps means "you really better have a good reason if you don't" in spec speak).

Sorry, but it sounds like: "Stop at red light, but you don't have to". As long as there is no spec for the exceptions for the rule, there is no rule.

But nevertheless, all is meant as a proposal / contribution / feedback and is free to be ignored. :-)

**Comment by Relequestual** [comment]
I'll expand on the multiple default aspect.

What should happen when you have a schema which says something like...

```
{
  "allOf": [
    {
      "properties": {
        "country": {
          "default": "A"
        }
      }
    },{
      "properties": {
        "country": {
          "default": "B"
        }
      }
    }
  ]
}
```

What should be the default?

When I said "it gets complicated", what I meant was, with complex schema structures and application keyword structures, it becomes very difficult to reason as to what the behaviour should be. People new to JSON Schema often come from assuming they are mostly defining a single "class" or a "form", but that simply isn't the case. There are multiple layers and many ways in which to combine subschemas. Many are not advised, but it's built to be very flexible and powerful.

**Comment by Finkman** [comment]
Okay, i got the point.

Without rating, two possible answers come to my mind:

1. The default is "A". allOf comes in a defined sequence and first definition defines the value
2. "country" becomes *required*
3. Schema becomes *invalid*, since "country" is over-constrained

**Comment by handrews** [comment]
@Finkman annotations intentionally do not interact with validation.  The reason is that annotations indicate things that either have nothing to do with validation (`title`, `description`), or maybe could interact, but have behavior that impossible to agree upon without application context (`default`, `readOnly`, `writeOnly`).

Many, many, many, many, many people have shown up here demanding that `default` behave in some way or another.  It's not physically possible to accommodate all of those demands.  Every single person thinks their behavior is correct.  And it usually is... for their use case.  But not for other people's use cases.

Instead of picking an option and making most people unhappy, we have defined that the exact behavior of annotations is determined by the application, not the JSON Schema specification.  And application-defined behavior takes place after validation.

**Comment by Relequestual** [comment]
Closing this now. Feel free to come back if you have any other JSON Schema questions =]
