### ISSUE TITLE
how to validate the unique values

### ISSUE THREAD

**Issue by yuzhujiutian** [json-schema-org/json-schema-spec#876]
On github and stackoverflow, I have seen a lot of features that mention the uniqueness of the check value.

e.g. as follows:
need to validate the ID (and/or name) value is uniqueness? (or how to validate by python, at currently )
![image](https://user-images.githubusercontent.com/386347/76280095-c28b1780-62cb-11ea-85bf-c6c6a6436b6d.png)

**Comment by awwright** [comment]
Tests like this are typically out-of-scope for JSON Schema because it's falls outside of "structural validation" (e.g. this value will be an object and must have a property "name"), and into "data consistency validation" (comparing two parts of a document against each other): see [Scope of JSON Schema Validation](https://github.com/json-schema-org/json-schema-spec/wiki/Scope-of-JSON-Schema-Validation) for more information.

**Comment by gregsdennis** [comment]
@yuzhujiutian you may be interested in https://github.com/json-schema-org/json-schema-vocabularies/issues/22.  I think this proposal gives you what you want.
