### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by blackmase** [json-schema-org/json-schema-spec#877]
So after countless hours I cant seem to get the youtube video to play in iframe, I have it setup so the user pastes the youtube link into a submit form linked to my src="<%=blog.video%>" schema and i get this error:
Refused to display 'https://www.youtube.com/watch?v=XN7Amgdfi0s&feature=youtu.be' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Is the only solution to use Ajax? and then use the youtube API? Ive provided images below
![image](https://user-images.githubusercontent.com/53386309/76585518-ab425a80-6482-11ea-90f0-9cf5a6f230c3.png)
![image](https://user-images.githubusercontent.com/53386309/76585548-bbf2d080-6482-11ea-867d-91abbf8a1ee7.png)

**Comment by handrews** [comment]
You need to file a ticket with whoever writes your tools or supports your API.  This is just about the standard itself.

**Comment by awwright** [comment]
@blackmase I'll note this doesn't have anything to do with Mongoose either, or any schema tool. The error is being emited by YouTube, which is requesting that it not be be embedded. For YouTube videos, you have to use the special URL that does allow embedding.

See: <https://stackoverflow.com/questions/9934944/embedding-youtube-video-refused-to-display-document-because-display-forbidden-b>
See: <https://lmgtfy.com/?q=X-Frame-Options+sameorigin+youtube>

**Comment by blackmase** [comment]
@awwright Thank you man! my god I almost beat my rig with a hammer today hahaha
