### ISSUE TITLE
"contains" is undocumented now

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/json-schema-spec#881]
I was doing some light bedtime reading of https://tools.ietf.org/html/draft-handrews-json-schema-validation-02 and noticed that "contains" has been omitted from section 6.4. To my surprise, its absence has not yet been noticed and it's still missing from https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-validation.xml!  Its only mentions are in its interactions with maxContains and minContains.

**Comment by karenetheridge** [comment]
I would assume the language from draft-07 still applies:  https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.4.6

> 6.4.6.  contains
> The value of this keyword MUST be a valid JSON Schema.
> An array instance is valid against "contains" if at least one of its elements is valid against the given schema.

**Comment by notEthan** [comment]
it's in the core rather than the validation spec:
https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.9.3.1.4

all the core subschema applicators are in section 9 there

**Comment by karenetheridge** [comment]
ah interesting, I totally missed that.
I wonder if some sort of cross-document reference should/could be made, without being too verbose and cluttering the document.

**Comment by awwright** [comment]
As I've been reworking my parser I think it makes sense to have "applicators" described in both places. After the subschema has been applied, it still has to look at the results and make a decision on if the keyword as a whole is valid. allOf/anyOf/oneOf all apply all the subschemas, their only difference is they each compute validation differently. I think this is a good reason to also call these validation keywords.

**Comment by handrews** [comment]
@awwright applicators just define what logical operation to perform on the subschema results.  They are not validators on their own.  Their validation outcome is a pure function of the validation outcomes of the subschemas and application rules:

In-place applicators:
`allOf` => AND
`anyOf` => OR
`oneOf` => XOR
`not` => NOT
`if`/`then`/`else` => predicate evaluation
`$ref` => identity

All of the child applicators are identity operators (single schema) or AND their results, with the sole exception of `contains` which ORs its results.

I'm going to close this since `contains` is definitely documented.

I'm strongly against duplicating the keywords across vocabularies or specifications.  The keywords go in one place each, no organizational scheme is perfect, and we spent a lot of time working out this one already.

The fact that applicator validation outcomes are simply functions of subschema outcomes is also a core architectural principle.

**Comment by handrews** [comment]
@karenetheridge the move is noted in the changelog.

A cross-reference is appropriate on the web site and I have something like that partially written.  It should not clutter the spec.
