### ISSUE TITLE
Mix plain name fragments and JSON-pointers

### ISSUE THREAD

**Issue by pboettch** [json-schema-org/json-schema-spec#885]
I'm lost in the jungle of RFCs and drafts and standards. I had a bug in my validator-implementation related to plain name fragments. And now have a question:

Can a sub-schema be referenced via the URI of a parent-schema which has a plain name fragment in its `$id`?

```JSON
"childDef": {
            "$id": "#childDef_ref",
            "type": "object",
            "properties": {
                "value": {
                    "type": "integer",
                    "maximum": 100
                }
            }
}
```

Is `"$ref": "#childDef_ref/properties/value"` a valid reference? Where is this case described?

**Comment by karenetheridge** [comment]
I'm not a project member, but hopefully I can answer this one correctly...

> Is `"$ref": "#childDef_ref/properties/value"` a valid reference?

It's a valid relative json pointer (it lacks a leading /), but it's not a location that will exist (if an implementation were to support resolving it, it would be relative to the base uri at the original location), so it's not a valid `$ref` to use in your document.  I don't think the spec has anything to say about relative json pointers; I'm guessing they would not be supported but it might be good to have something definitive.

You can however use a non-fragment `$id`, without the `#`. That will let you create a valid uri-reference relative to it, e.g. an `$id` of `childDef_ref` will allow you to do `"$ref": "childDef_ref#/properties/value"` (and if the document's base uri was "http://foo.bar.com", then you can also create a `$ref` like "http://foo.bar.com/childDef_ref#/properties/value").

This is all documented in https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2, and in draft-07 at https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.1.

**Comment by handrews** [comment]
@karenetheridge Relative JSON Pointers are completely separate from plain name fragments, and cannot be used in URIs.  Because the only rules for fragments when combining a base URI and a URI reference is to remove the base's fragment and use that if the reference (if any),  There is no notion of a partial fragment reference,

Plain name fragments exist to let you identify things in a location-independent way, without minting a new resource (which is what happens when assigning a non-fragment `$id`- we made that explicit in the latest draft but it was always more or less true.

They also exist because it's a fragment syntax you can use across representations, e.g. in XML or even HTML.  That is not true of JSON pointers.

**Comment by handrews** [comment]
(why you'd try to write a JSON Schema in HTML is beyond me but people do weird things).

**Comment by pboettch** [comment]
Thanks for your help!
