### ISSUE TITLE
Validate against enum derived from list of objects dynamically

### ISSUE THREAD

**Issue by sunnyofhell** [json-schema-org/json-schema-spec#887]
Using JSON Schema 7 to perform validations

Is the below validation possible using json schema.

```
 {
    properties : [{name: "a"}, {name: "b"}, {name: "c"}],
    rules : [{ prop : ["a","b"] }, { prop : ["a"] }, {prop: ["c"]}]
 }
```
The "prop" property in object is dependent values in properties.

ie only of "properties.name" exists then that value can be added to the "prop" array

Note:

The "properties" array can have any object of type {name : }
"name" can have any possible string, which i don't know beforehand
I have been going through documentation, but can't find a answer.

Is this validation not supported in Json Schema yet? Any plans/workarounds for doing this?

**Comment by handrews** [comment]
No, and no current plans.  See https://github.com/json-schema-org/json-schema-vocabularies/issues/26 for an in-depth discussion of keywords with external dependencies.  I'm closing this because the general issue is well-covered elsewhere.  And we wouldn't put such a keyword in the core JSON specification even if generally supported- it would be 3rd-party extension.  My apologies if this is a little terse, we should probably have a better write-up somewhere that explains why we don't do this.  I think there's one on the wiki but it's pretty abstract.
