### ISSUE TITLE
use tag URI for core vocabulary IDs

### ISSUE THREAD

**Issue by notEthan** [json-schema-org/json-schema-spec#890]
I suggest JSON schema changes the core vocabulary ID URIs from https to tag.

```diff
-https://json-schema.org/draft/20XX-XX/vocab/core
+tag:json-schema.org,2019:draft/20XX-XX/vocab/core
```

along with all the rest of the vocab/* vocabularies

instead of using a transport protocol for vocabularies, which have no document to transport, why not use a uri that is simply an identifier? the tag URI seems like it was built for this. (I think most of the json schema members are familiar, but a tag URI is described at [taguri.org](https://www.taguri.org/), [wikipedia](https://en.wikipedia.org/wiki/Tag_URI), [its RFC](https://tools.ietf.org/html/rfc4151).)

this would help alleviate confusion on the part of people looking for retrievable resources at vocabulary URIs (#815).

**Comment by handrews** [comment]
I considered this, but decided against it primarily because the intention is that there will be something there in the future.  `tag` URIs, which I love and use in various other projects, are not incredibly familiar to most people.  If we planned to leave the URIs not pointing to anything, it would be worth asking people to understand them.

However, that is not the plan.  I do not want to create extra mental load in understanding vocabularies and then just switch back to something more familiar.

Please remember that JSON Schema is a draft.  It is _supposed_ to have unfinished pieces here and there.  Otherwise, we'd finalize it.  This is one of the main unfinished pieces, and it's like this on purpose.

**Comment by notEthan** [comment]
sounds good. thanks for the consideration @handrews

**Comment by awwright** [comment]
I'll also chime in tag: URIs are great, I use them for resources that I know are not going to be documents... e.g. so I can have a tag: URI describing some thing, and an http: URI for a document _about_ that thing. I use this technique to build tables in https://fullstack.wiki/

I agree with with @handrews but it's not a bad idea to keep in mind @notEthan, thanks for the suggestion!
