### ISSUE TITLE
The $recursiveRef in meta/core's $defs schema is not working as expected

### ISSUE THREAD

**Issue by jdanyow** [json-schema-org/json-schema-spec#895]
Bear with me, I probably have this all wrong :grimacing: 

Consider this scenario from the json-schema-test-suite:

https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/c4d3e0f92ced13c288d1713815c00539b09c9d2e/tests/draft2019-09/defs.json#L13-L23
```json
    {
        "description": "invalid definition",
        "schema": {"$ref": "https://json-schema.org/draft/2019-09/schema"},
        "tests": [
            {
                "description": "invalid definition schema",
                "data": {"$defs": {"foo": {"type": 1}}},
                "valid": false
            }
        ]
    }
```

1. First there's the $ref to https://json-schema.org/draft/2019-09/schema
2. https://json-schema.org/draft/2019-09/schema sets $recursiveAnchor to true.
3. We hit the $allOf 
    https://github.com/json-schema-org/json-schema-spec/blob/4a122aad331aea72aa661bdb6ce9e30fbdaaf601/schema.json#L15-L22
4. $allOf brings us to meta/core which sets $recursiveAnchor to true.
    https://github.com/json-schema-org/json-schema-spec/blob/4a122aad331aea72aa661bdb6ce9e30fbdaaf601/meta/core.json#L3-L7
5. Finally the $recursiveRef in meta/core is encountered:
    https://github.com/json-schema-org/json-schema-spec/blob/4a122aad331aea72aa661bdb6ce9e30fbdaaf601/meta/core.json#L52-L56
6. My understanding is this $recursiveRef dereferences to meta/core (due to step 4) rather than https://json-schema.org/draft/2019-09/schema which means `/$defs/foo/type` is not validated against the primary meta-schema (and eventually meta/validation).

Do I have this right?

https://json-schema.org/draft/2019-09/json-schema-core.html#recursive-ref

**Comment by jdesrosiers** [comment]
The way I implemented it, `$recursiveAnchor` only sets the contextURI the first time it's encountered, otherwise the previous contextURI is used. So, in your example, `$recursiveRef`s should use `https://json-schema.org/draft/2019-09/schema` no matter how deep the `$recursiveRef`s go because that's where the first `$recursiveAnchor` was.

I'm still not %100 sure I've done it right, but it passes all the tests and seems to match the intent of `$recrusiveRef`/`$recursiveAnchor`.

**Comment by handrews** [comment]
@jdesrosiers sounds like you have it right to me.  

@jdanyow  the intent of these keywords is to allow "extending" recursive schemas.  I put "extending" in quotes because nothing about JSON Schema is an exact analogue to extending object-oriented classes, which is what people tend to think of first.  But if you look at how the old hyper-schema meta-schema was written for prior drafts, there's a ton of repetition even though the validation meta-schema is referenced.  Because of the recursive problem.  These keywords eliminate the need for such repetition.

**Comment by handrews** [comment]
My impression is that we all agree that the keywords are being used correctly in the meta-schemas so this issue is done?  Please re-open or comment if this still needs more follow-up.
