### ISSUE TITLE
Clarify what happens when "contains" is applied to an empty array

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-spec#924]
Should "contains" applied to an empty array result in a pass, and should it set the annotation to zero?

Update: as I think about this, there’s nothing in the array, technically, that matches, so I guess the answer is that it does not result in a pass nor annotations. But that brings up the question: what happens when an empty “contains” schema is applied to an empty array?

**Comment by notEthan** [comment]
> An array instance is valid against "contains" if at least one of its elements is valid against the given schema.

can't be the case that one of its elements validates, when there are no elements. doesn't matter if the schema is empty, it's specifying something must be there.

**Comment by karenetheridge** [comment]
I asked this exact question yesterday on slack. An empty data instance validates.  If you want to assert that there *must* be something there, then you should add `minContains: 1`.

**Comment by karenetheridge** [comment]
This is exactly parallel to 'properties'.  A properties keyword validates against an empty object. If you want to assert that the property *must* exist, then add `requires`.

**Comment by handrews** [comment]
@ssilverman @karenetheridge 

`contains` states _if at least one_.  I think that's pretty clear, it has the normal English meaning.  Is it possible to match at least one element in an empty array?  No.  That is not ambiguous.

Furthermore, `minContains` defaults to 1.

**Comment by karenetheridge** [comment]
related: https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/368

**Comment by karenetheridge** [comment]
> Furthermore, minContains defaults to 1.

Ooh, I missed that line. Very important! :)

**Comment by ssilverman** [comment]
How do we reconcile with https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/368#issuecomment-629218483?

Should the spec be changed to disallow “minContains affects the behaviour of “contains”?

**Comment by ssilverman** [comment]
@karenetheridge I noticed you gave the comment a thumbs down. How does "minContains" not affect "contains" if "contains" must validate to true for count == 0 only if "minContains" is zero?

**Comment by ssilverman** [comment]
@Relequestual Just tagging you because I think we should reopen this issue, and pending discussion, solve it with whatever new text we come up with. The relevant "minContains" text is:
> A value of 0 is allowed, but is only useful for setting a range of occurrences from 0 to the value of "maxContains". A value of 0 with no "maxContains" causes "contains" to always pass validation.

This definitely contradicts the "contains" implication that it only passes when count > 1.

**Comment by Relequestual** [comment]
@handrews Given that `contains` is in core and `minContains` is in validation, how would you like this to be resolved?

**Comment by Relequestual** [comment]
Given `min/maxContains` on their own do nothing, you could argue they should be in core, as their behaviour is actually modifying the result of an application, and not validation.

**Comment by Relequestual** [comment]
@ssilverman @notEthan @karenetheridge 
How do YA'LL feel this should be resolved?

I haven't been able to follow all of the slack chatter. Did you come to any consensus?

**Comment by notEthan** [comment]
to preserve the current behavior of `minContains: 0`, the `contains` spec must clarify its relationship to min/maxContains (wherever they live - I think moving those to core makes sense, given their interdependency).

@ssilverman 
> Should the spec be changed to disallow “minContains affects the behaviour of contains”?

this is another option, yeah. but separating `contains` to be independent of `minContains` would break `maxContains`' ability to validate an empty array. a minContains of 0 would no longer make sense, since the schema would fail on the `contains` keyword for an empty instance array.

then the only way to validate maxContains, allowing for an empty array, would be to add another schema, something like
`oneOf: [{const: []}, {contains: {...}, maxContains: 47}]`

this has the upside of a `contains` keyword that is independent of other keywords, but the downside of adding complexity to certain schemas and making them less readable. then again, there are many compromises on readability of json schemas.

which option is better? 🤷

**Comment by karenetheridge** [comment]
I think we can resolve this by amending the documentation, to add more cross-references between the 'contains' and 'minContains' sections.

**Comment by gregsdennis** [comment]
Just now reading over this issue and the associated tests PR after my lib failed on these two tests (and only these two, which was surprising given the number of tests that have been added).

Thinking through it I think it makes sense the way it currently is: with the interdependence.  It took me a while, but considering the case when the array is _not_ empty made me realize we need consistency.

`minContains = 0` is the only way to convey "this item may be in the array".  One may raise the question of whether it's beneficial to even have `contains` if the item is allowed to be missing, but that's a separate concern because authors can do all sorts of strange things.

If we approach it from the other end, `minContains = 0` is meaningless if `contains` is just going to invalidate the instance anyway.

I think this is defined correctly already, in a way that gives special meaning to `minContains = 0`.  Yes, it adds a circular dependency onto these keywords, but I'm okay with that in this case because the dependency is well-defined as is the behavior ob both keywords in the absence of the other.

**Comment by handrews** [comment]
@rjmill because hybrid applicator/validator keywords are a problem which is why we split `dependencies` into `dependentSchemas` and `dependentRequires`.

I agree that `contains` is challenging, and was more of a mixture than it first seemed from the start.

Coming back to this after a long break, here is what I see:

* `contains` remains an applicator.  It already returns annotations about how many items in the array matched, because `items` and `unevaluatedItems` depend on those annotations
* `minContains` and `maxContains` get defined in terms of the annotation results of `contains`

This provides a unidirectional dependency from the Validation spec to the Core spec, which is already generally the case.  I think it's actually a good thing to have a cross-vocabulary dependency to show how one vocabulary can build on what another already does.

There's a subtlety where if `contains` returns a `true` annotation (meaning that all items were valid against the subschema), then `minContains` and `maxContains` would need to check the instance array length.  Or we can say that `contains` only returns an index list and `items`/`unevaluatedItems` will just have to see if there are any items not covered by the list.

It is already the case that `contains` returns an empty set when the schema does not match any item, and the case of the instance array being empty is just a special case of that.

**Comment by karenetheridge** [comment]
I was typing this on #976 and am moving it to here, although it may be redundant with the above discussion:

---

(re switching to defining in terms of annotations) Don't forget about this case where the keywords can't be independent:  `contains: { schema.. }, minContains: 0`.

ref: ["A value of 0 with no "maxContains" causes "contains" to always pass validation."(https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.4.5)

ref: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2019-09/minContains.json#L153-L171

----

> It is already the case that contains returns an empty set when the schema does not match any item, and the case of the instance array being empty is just a special case of that.

Wouldn't the 'contains' keyword cause evaluation to fail, rather than succeeding with an annotation? Is 'contains' being redefined to never fail?  I guess that could work, as then the schema can say 'minContains: 1' to assert that zero matches is not acceptable. I wonder if this might be confusing to the user though.

**Comment by handrews** [comment]
Principles:
* Applicators consist of a rule for determining to which instance location(s) each subschema is applied, and a boolean function for combining the validation results
* Assertions consist of a boolean function in terms of the instance value

`contains` is challenging but can be solved by minimally relaxing one principle, and allowing an applicator's boolean function to include a boolean constant as well as the results of the application of the subschemas.

`contains`:
* has no effect unless the instance is an array
* the subschema is applied to each item in the instance array
* the set of validation results, plus the constant value `false`, are all ORed
* an annotation is produced consisting of the set of indices of items where the subschema was successfully (validation result `true`) applied; if none applied successfully this is an empty set, _not_ a missing annotation; if all items had a successful application, this annotation MAY instead be the boolean value `true`

This results in the correct behavior.  An empty instance array produces a `false` validation result, as does an array with items where none are valid against the subschema.  The presence of at least one item that is valid against the subschema produces a `true` validation result.

`minContains`/`maxContains`:
* passes if there is no adjacent `contains` annotation
* otherwise, take the size of the annotation set from `contains` (or the length of the instance array if the annotation is a boolean `true`)
    * `minContains`: if this number is >= the value of `minContains`, the assertion passes, otherwise it fails
    * `maxContains`: if this number is <= the value of `maxContains`, the assertion passes, otherwise it fails

I am fairly certain that this works, and is the minimal relaxation of existing principles that will work.

**Comment by karenetheridge** [comment]
> I am fairly certain that this works, and is the minimal relaxation of existing principles that will work.

Agreed, this looks good!  Given that `minContains` defaults to 1 when not provided, this allows for the base case of `contains` without `minContains` to produce the expected failure result when no instance items match.

My only remaining concern is that the execution order between these two keywords must be explicitly stated (just as  unevaluatedProperties must be considered after properties, additionalProperties etc).  (At present in my implementation, I consider the validation vocabulary first and applicators second, simply because it's more efficient that way when running in short-circuit mode (abort evaluation as soon as the first failure is found, so that will need to change.)

**Comment by handrews** [comment]
@karenetheridge thanks!

> Agreed, this looks good! Given that `minContains` defaults to 1 when not provided, this allows for the base case of `contains` without `minContains` to produce the expected failure result when no instance items match (would the error be generated referencing the 'minContains' keyword rather than 'contains'? this might be confusing when minContains doesn't even exist in the schema. would some tools be unhappy at a keywordLocation path that does not actually exist?)

It's actually a bit more than that: `minContains`/`maxContains` can and do rely on a `contains` annotation (presumably from the applicator vocab keyword `contains` but the code can't tell, it just looks for the annotation and if it's not the right annotation then it's garbage-in-garbage-out undefined behavior).  But `contains` cannot rely on the default of `minContains` or else that would be a circular dependency.  And within Validation and Core (the specs) we have decided that Validation (and its vocabularies) depends on Core (and its vocabularies), but not the other way around.

the "OR with `false`" definition of the applicator function of `contains` ensures that `contains` works correctly without any knowledge of `minContains` or its default.  It makes it so that there needs to be at least one successful application of the subschema in order for that function to produce a `true` overall result.

And in fact, this mechanism (supplying an initial boolean constant) is required in many place to get the right behavior with empty data structures.  So if R is the set of results of applying the subschema(s) per the applicator's rules, then:

* `items`, `prefixItems`, `unevaluatedItems`, `properties`, `patternProperties`, `additionalProperties`, `unevaluatedProperties`: `AND({true} ∪ R)`
* `contains`: `OR({false} ∪ R)`

This is consistent and correct.  `contains` produces a false result if there is not at least one true result in the set.  Everything else produces a true result unless there is at least one false result in the set.  You need these constant values in the function or else you end up without any value at all and special-casing the empty set.  I like it better when the complete behavior can be specified in terms of a boolean function.

In a way, this makes the default of `minContains` irrelevant, but it is intuitive and correct to specify it.  It's just redundant, which in this case is not a bad thing.

> My only remaining concern is that the execution order between these two keywords must be explicitly stated (just as unevaluatedProperties must be considered after properties, additionalProperties etc). (At present in my implementation, I consider the validation vocabulary before applicators, simply because it's more efficient that way when running in short-circuit mode ("abort evaluation as soon as the first failure is found"), so that will need to change.)

See #995 for this- let's keep it out of this issue as it's not really specific to `contains`

**Comment by Relequestual** [comment]
I'm making a PR to resolve this issue, but while we are saying `contains` doesn't depend on `minContains`, we are saying `minContains` may modify the assertion result of `contains` when it `minContains` has a value of `0`.

**Comment by Relequestual** [comment]
@ssilverman I've pre-emptively closed this issue and merged a PR.
Please see the PR as part of our 1 week review for RC1 of 2020-12.
🎉
