### ISSUE TITLE
uri format: Is schema-specific validation in scope?

### ISSUE THREAD

**Issue by yurikhan** [json-schema-org/json-schema-spec#951]
I stumbled on a corner case. A JSON Schema validator says `"http://"` is a valid instance of `{"type": "string", "format": "uri"}`. It is technically correct, because JSON Schema [Draft 2019-09 Validation § 7.3.5][0] defines the `uri` format in terms of RFC 3986, and, [several ABNF grammar steps skipped], by [RFC 3986 § 3.2.2][1], a host can be identified by a registered name, and a registered name is generally allowed to be empty.

[0]: https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.5
[1]: https://tools.ietf.org/html/rfc3986#section-3.2.2

However, the next paragraph after the definition of the `reg-name` production says, and I quote (emphasis mine):

> If the URI scheme defines a default for host, then that default applies when the host subcomponent is undefined or when the registered name is empty (zero length). For example, the `file` URI scheme is defined so that no authority, an empty host, and `localhost` all mean the end-user’s machine, whereas _the `http` scheme considers a missing authority or empty host invalid._

Indeed, [RFC 7230 § 2.7.1][2] paragraph 3:

[2]: https://tools.ietf.org/html/rfc7230#section-2.7.1

> A sender **must not** generate an `http` URI with an empty host identifier. A recipient that processes such a URI reference **must** reject it as invalid.

----

Is it the intent of JSON Schema to be usable for validating URIs according to their URI schemes, or is that out of scope and users who need stricter validation should use other tools after general syntax validation? **Must**, **should** or **may** validators implement further URI format validation depending on the scheme?

**Comment by handrews** [comment]
As of the most recent draft `format` by default does not perform validation, but is rather an annotation informing the application how to interpret the string.  Technically you can still turn on validation for it, but `format` support is wildly inconsistent which is why it is now off by default- it's never worked to anyone's satisfaction, and we prefer that new keywords be explored that have well-defined behavior, each for a single use case.  Stapling URIs, date-time, regular expressions, etc., etc. into one keyword made a completely mess.

So: in terms of "JSON Schema, the overall extensible system", yes doing such validation is in scope.  In terms of the current `format` keyword?  No.  On a personal level (this is not the project's official position), I would like to rip `format` out and nuke it from orbit, and replace it with literally anything else.

Replacements would likely start out as 3rd-party vocabulary extensions- we have a holding ground for such proposals ( https://github.com/json-schema-org/json-schema-vocabularies/issues ) so folks can find them, but are not working on them ourselves.  Please drop by our slack (see json-schema.org for an invite link in the upper right corner) to discuss in more detail.
