### ISSUE TITLE
References relative to $anchors valid?

### ISSUE THREAD

**Issue by mutech** [json-schema-org/json-schema-spec#993]
Until up to the appearance of `$anchor`, relative refs had been valid JSON pointers (and they might still be, didn't find the relevant portion in the specs even though I remember having read that in earlier specs). A ref like `#x/y` was to my understanding invalid.

It would be convenient to be able to address sub schema relative to anchored elements, using the syntax above (f.e. `#type/properties/p`), but that would mean that `#anchor/path` would no longer be a valid JSON pointer, neither would it be a valid implicit anchor reference (`/` is not a valid anchor character).

This situation is a bit unfortunate because:
* If I cannot reference subschemas relative to an anchor, the location independency advantage of anchors is greatly reduced.
* If I can use the syntax described above, this should be mentioned in the specification to give tool makers a chance to get their implementations right and provide schema authors with some security.

I appreciate the focus on vocabularies, this is a good strategy to enable extensibility for JSON schema. However, I believe the core specification should be more focussed to provide a clear and easy to understand basis for both tool makers and users.

The two most prominent use cases for JSON schema are validation and code generation (f.e. via openapi). The core should support both without the need for additional vocabularies. I am currently working on a code generator because none of the 7 code generators I found could cope with a relatively simple  schema definition and produce acceptable results. The most prominent problems are tools unable to resolve references outside of the document (either filesystem or URL references), others do not understand the scope (baseURI) changes introduced by "$id". None of them support anchors, and when they will support it, it will most likely be as inconsistent as the support for $id resolution.

I don't understand why you introduce complex concepts like relativeRefs which I don't understand enough to see what their advantages might be, while the fundamentals are either undefined or not clearly enough documented or not widely enough supported by the community and consequently only barely usable for schema authors because tools mostly don't support them right.

Take for example "true", "false", nothing, "type", "not", "if", "allOf", "oneOf" and "anyOf". It seems to be valid to use them all together, even though there is no real meaning to such a combination. You cannot validate it, you cannot generate code for it, you can just spend a lot of time imagining a possible use case for that degree of freedom that someone most likely could easily achieve otherwise. That someone should however not be your prime focus group.

Why does `{ "title": "t", "$ref": "#x" }` not have the clear semantics that the title of `#x` will be overridden? There is no reasonable way to interpret such a construct differently if there would be a tool that could benefit from the lack of defined semantics, it could just as well provide the user with an option to override the default semantics.

Somewhere I read that JSON schema does not support inheritance, but then again it does support it a bit using "allOf" except that it makes it impossible for a tool to interpret it because of all the redundancy and vagueries in its semantics.

Sorry for ranting so much, it's not my intention to diminish your efforts, but I would really like to see you shift your focus from creating esoteric features like `relativeRef` and instead create an actionable standard we all can benefit from.

**Comment by Relequestual** [comment]
It sounds like you have a lot of issues with JSON Schema. I'm not going to reply to everything here initially for a number of reasons, but I will say a few things.

JSON Schema is worked on by a group of volunteers on evenings and weekends, unpaid, with a small amount of donated funding from sponsors. We simply don't have the capacity to support the code generation use-case. If you'd like to support our work, we have an Open Collective. Not being able to support all use cases is the reason we created vocabularies. 
Unless you've done it yourself, you have no idea of the complexity and difficulty of trying to get many groups to agree on a standard, which is what we'd need to do for code generation.

You may find it interesting to know that OpenAPI 3.1, which is currently in release candidate stage, will bring with it full JSON Schema support. This will mean tooling vendors (tools made by companies who have money and full time paid staff) will look to support full JSON Schema. A lot of work from both sides over the past few years has gone into making that possible.

> Sorry for ranting so much, it's not my intention to diminish your efforts, but I would really like to see you shift your focus from creating esoteric features like relativeRef and instead create an actionable standard we all can benefit from.

I'll assume you mean `$recursiveRef` in 2019-09, which will be `$dynamicRef` in 2020-NN.
This IS a complex keyword to understand, mainly because it was created to enable the easy extension of JSON Schema meta schemas. The primary driver was developing the JSON Schema for OpenAPI. In short, if you want to extend a JSON Schema object before draft 2019-09, you had to duplicate the whole thing to add a single keyword. From draft 2019-09, this is no longer required and reduced the size of the OAS meta schema by more than half. That was a HUGE maintainability win.

In terms of your other questions, I didn't actually plan to do any JSON Schema work tonight. Feel free to come and join the JSON Schema slack server and ask questions, or wait for someone else to come and answer here, or I'll come back at a later date.

**Comment by mutech** [comment]
Hey Ben. Sorry again, I see your point and know the constraints from my own experience. I hope I didn't step on your toes too much.

You are not working for me and I'm not paying you, so I really have no right to expect anything but what comes my way from the team here. The other side of the coin is that I started to add a workable resolver to one of the code generators and ended up writing my own generator and am now working on converting my home cooked meta schema to the various dialects of JS that other tools support. I will probably end up writing a replacement for validators and swagger tools just to support my own use case. That's not exactly what I expected from having the model being the source of truth as a means to reduce the workload in my project ;-) (Especially considering how basic my use case is, I should never have considered using a declarative approach to manage models/services/versions)

Again, sorry if my comment was too harsh, I'm suffering from some intensive frustration regarding tooling around JSON schema.

Looking forward to discuss stuff on slack if I find you there.

**Comment by Relequestual** [comment]
No problem Michael. We get this a lot, and I hope you felt my reply remained professional.
I can totally appreciate how frustrating it is to come to something with expectations and feel let down.

As I said, we can't support the code gen use-case, but that doesn't mean we've ignored it (again see "vocabularies").
Everyone wants something specific or has a difference of opinion, and none of our team has sufficient experience (affik) with code gen to even know which arguments are valid even if we DID have the time.

Comments around how we focus our time and efforts hit close to home because we agonise over every single change to the spec. We react to real user needs. I've answered hundreds of JSON Schema questions over the past 5 years, and our collaborators are often also helping and aiding those in the slack server too, so we get a decent feel for pain points and what people actually want. We often move forward with a solution which individually we might not be happy with but yet wins based on the general consensus notion. (Once you see general consensus in action, it starts to become clear why this is often better than voting!)

Our slack is pretty active in all timezones, and you'll find a good handful of implementers who also have a good handle on the spec and the test suite.

I'm going to close this issue because I feel you'll ask specific questions in slack and get some answers, plus I'll be there too.
We're currently focusing on a push for draft 2020-NN, so I have to be careful where my time goes.
