### ISSUE TITLE
Proposal: Support for $ref referencing subschema below anchors

### ISSUE THREAD

**Issue by mutech** [json-schema-org/json-schema-spec#994]
$refs can currently use JSON pointers to reference sub schemas relative to schema IDs.

The split of $id and $anchor is great, but has one drawback which is that according to the latest spec, it is not possible to reference sub schemas of anchors.

A common use case would be to reference the type of a property of an object (e.g. to declare a foreign key or some such relation between properties of objects).

This can easily be mitigated if you control both source and target schema, by creating an entry in $defs for the property type. But even so it would be a bit clumsy to have to refactor a schema just to expose a type to make it available as reference target.

If the target reference schema is external, the only solution would be a location reference via JSON pointer, which would negate one main benefit of anchors (location independence) and is also fragile, because such a reference would not only depend on the version of the target schema itself but also unnecessarily on the version of JSON schema used to implement the model. Anchors are much more robust (it's unlikely that a ref like `http://example.com/#customer` will change, while `...com/#/$defs/sales-module/oneOf/1` is not a robust ID (silly example).

### Solution

Fragments referencing into schema documents should have the form:

```
fragment ::= '#' ( <anchor> ) ? ( <pointer> ) ?
```

Where anchor is an *anchor* name as defined by the latest spec and *pointer* a JSON pointer.

`#anchor` and `#/some/pointer` would still be valid and `#anchor/some/pointer` would be the new semantics that would allow to reference sub schema of an anchor.

Because the latest version of JSON schema introduced changes that requires tools to be updated in order to support it, this change would be relatively unobtrusive in comparison and I feel the benefit to make `$anchor` a wholesome replacement of `$id` for abstracting the schema location would be worth the updated semantics.

**Comment by handrews** [comment]
plain name fragments (`$anchor`) and JSON Pointer fragments are intended for different use cases.

If you know the structure of the schema (because, for example, it's the same schema, or because it is part of a set owned by the same person who would change them all at once), then JSON Pointers work great.

If you do not know the structure of the schema, then you want a plain name fragment.  The two should not be mixed- if you need to access a subschema of an `$anchor`-identified schema, you can add an `$anchor` to that subschema.  You can come up with your own convention on names to show they are related, or not (just don't expect anyone else to understand your convention).

**Comment by mutech** [comment]
JSON pointers and anchors have one thing in common, the provide a way to reference content elements of a document.

Pointers allow to address an element by its absolute document location, anchors by a defined name.

Using an anchor is always preferable, because the location of an element in a document is typically not a good interface and prone to change which makes reuse of modules difficult and fragile.

A sub element of a schema, such as a property type of an object is closely tied to the object itself and other than a schema location, it's exactly the right abstraction level. In my example I want to refer to the type of a property of a type identified by a name. The type of the property itself is not relevant, what is relevant is that it is the type of a property of a certain object.

It's particularly bad design to express "typeof property P of O" by saying "Go to the gas station and look under the blue carpet".

Most importantly, if you don't own the target schema (even if it's maintained in the same company by a different team) modifying it just to reference  a definition is unrealistic. What will happen is that someone will copy and paste the type definition for the sake of simplicity.

What is the disadvantage of mixing JSON pointers and anchors, especially considering that you are actually mixing them, just only to some extend? A fragment can currently be either an anchor or a pointer, just not both.

Both would in this case not be a muddy mix, it would just expose anchors as an optional root for a pointer in addition to the document root.

You are currently supporting this:
- A schema document can have an embedded document defining its own $id.
- A referrer has to know that such a document is embedded in another document with a different ID and the location of either document is both unrelated to their ID's and there is no way of specifying such locations in JSON documents. Schema processors are not required to be able to resolve ID's to documents.
- You can refer to such an embedded document either by referring to the enclosing document and a JSON pointer fragment leading to the root and maybe into that embedded document because that might be the only chance to convince your schema processor to find the thing, or you can use either a fragment relative to the embedded document or the ID of the embedded document with yet another pointer into its guts.

And you are reluctant to mix anchors and pointers in a setting that clearly and unambiguously defines the semantics of the address?

I have a hard time understanding this.

Here my proposal:

- URI w/o fragment -> addresses the root schema in a schema document
- URI w pointer fragment -> addresses a schema relative to the document root
- URI w anchor -> addresses a schema identified by anchor
- URI w anchor + pointer -> addresses a schema relative to the anchored schema

**Comment by handrews** [comment]
@mutech 

> I want to refer to the type of a property of a type identified by a name.

You mean that given something like:

```JSON
{
    "$defs": {
        "s": {
            "$anchor": "foo",
            "properties": {
                "p": {"type": "integer"}
            }
        }
    }
}
```

You want to access `integer`?  That is not possible at all, nor should it be.  `$ref` can only reference schemas.

**Comment by mutech** [comment]
No, I want to `{ "$ref": "#foo/properties/p" }`

```json
"$defs": {
  "customer": { "properties": { "id": { "type": "string", "format": "uuid" }, ... } },
  "invoice": { "properties": { ..., "customer-id": { "$ref": "#customer/id" } }
}
```

Would be the prototypical example. That's easy if both types are local, but if you refer to a Babel configuration option in your build tool config schema, you can't just add an anchor in their schema, at least you really don't want to do that.

**Comment by jdesrosiers** [comment]
> The split of $id and $anchor is great, but has one drawback which is that according to the latest spec, it is not possible to reference sub schemas of anchors.

No functionality has been lost as a result of `$anchor` being split from `$id`. What you are proposing would be completely new functionality, not restoring something that was lost because of the split. I just wanted to make that clear.

I think your proposal makes sense and it's even backwards compatible, which is great. However, I'm not convinced that it's necessary. I'd rather not add additional complexity to the spec without a really good reason.

**Comment by mutech** [comment]
If you compare ```#/$defs/customer/properties/p``` and ```#customer/properties/p``` does that not look like a rather intuitive and clearly defined construct?

**Comment by mutech** [comment]
Of course it's not necessary, but neither are the new $recursive keywords or $anchor itself. If there is no benefit in `#anchor/pointer` why did you define `#anchor`? Every reason to introduce $anchor equally applies to this proposal, just not quite as frequently. On the other hand, the semantic change of $id and $anchor breaks each and every schema processor, while my proposal would at worst just not be supported by tools not implementing it.

**Comment by mutech** [comment]
> No functionality has been lost as a result of `$anchor` being split from `$id`. 

Correct me if I'm wrong, but in previous versions I could do something like this:

```json
{
  "definitions": {
     "customer": { "$id": "#/customer", ... },
  }
}
```

and then $ref: "#/customer/properties/id" (or use the standard `definitions` property if /customer is a problem.

While that reference looked like a location reference, it had according to the specs to be resolved location independent.

That is a bit hypothetical because most tools never implement the baseURI functionality of $id, but that's another issue.

**Comment by handrews** [comment]
@mutech that usage of `$id` was never fully specified and was always a problem.

`"$id": "#/customer"` did *NOT* create a location-independent plain-name fragment, as plain-name fragments are not allowed to start with `/`.

Instead, it attempted to assert that the current JSON Pointer fragment was `#/customer` despite it clearly being `#/definitions/customer`.  There is no logical way to resolve this, and I suspect different implementations varied as to whether they did anything with it at all.

The only way in which such an `$id` could have been valid would be if it matched the actual JSON Pointer path: `#/definitions/customer`, which is a no-op and therefore not useful.

The fact that this was confusing, contradictory, and never "worked" in any consistent or meaningful manner was the main reason that we split out `$anchor`.

**Comment by handrews** [comment]
>  I'd rather not add additional complexity to the spec without a really good reason.

Yes, also this.  Thanks @jdesrosiers 

@mutech 
> If you compare `#/$defs/customer/properties/p` and `#customer/properties/p` does that not look like a rather intuitive and clearly defined construct?

No, because that's not how URIs work.  There is no such thing as a URI fragment reference.  URI reference resolution always chops the entire fragment off of the base, resolves the non-fragment reference against the non-fragment base, and then appends the entire reference fragment.  You never combine pieces of fragments.  This is determined by RFC 3986.

We would be inventing an entirely new way to combine URI references that would not be supported by any URI library anywhere.  I am not interested in doing that.

**Comment by mutech** [comment]
resolve URI http://x/a#base-fragment against http://x/a#another-fragment => http://x/a#another-fragment, that's what you described.

Let's apply this:

`"$ref": "#customer/properties/id"` resolved with base `http://x/my-schema/` results in `http://x/my-schema/#customer/properties/id`, exactly what I want, conforming to URI resolution specs. Where is the problem?

**Comment by jdesrosiers** [comment]
> Of course it's not necessary

I'm not at all saying there is no benefit. I'm just saying that in my judgement, the benefit doesn't outweigh the cost. Your judgement is different and that's ok. It's a subjective thing and everyone is going to have their own opinions. Honestly, I would not be upset at all if this was adopted. It's a good suggestion, it just comes down to subjective opinion on whether it's valuable enough to be worth a spec change.

**Comment by mutech** [comment]
> > I'd rather not add additional complexity to the spec without a really good reason.
> 
> Yes, also this. Thanks @jdesrosiers

Was there a good reason to introduce `$anchor`? The same reason applies to this. If it is valuable to be able to have location independent references, then it is equally valuable to have references relative to these.

The price for introducing $anchor and changing the semantics of $id is enourmous. There are tons and tons of schemas defining relative $id's like "#/definitions/x" and all of them are invalid according to the new specs. It's unlikely that many of them will be rewritten, which will make the adoption of newer schema version much less attractive.

If you are willing to pay this price but you are reluctant to accept a change that contributes to the benefit of this expensive feature while not introducing any penalty by itself, I wonder how you could decide for $anchor in the first place.

**Comment by jdesrosiers** [comment]
> Was there a good reason to introduce `$anchor`?

Plain name fragments have been a part of the spec as long as the `$id` (previously `id`) keyword has existed and predates everyone currently involved in the spec. So, no one can tell you why it was introduced in the first place.

> The price for introducing $anchor and changing the semantics of $id is enourmous.

Other than splitting out `$anchor`, the changes to the semantics of `$id` are backwards compatible for implementations. Nothing needs to be changed other than splitting the functionality of `$id` into two keywords.

> There are tons and tons of schemas defining relative $id's like "#/definitions/x" and all of them are invalid according to the new specs.

Yes, there is a tool that generates `$id` in this way. We've told them it's wrong and they need to fix it, but it was never fixed and continues to cause confusion. _Those `$id`s have always been wrong in every draft past and current._

**Comment by mutech** [comment]
> > The price for introducing $anchor and changing the semantics of $id is enourmous.
> 
> Other than splitting out `$anchor`, the changes to the semantics of `$id` are backwards compatible for implementations. Nothing needs to be changed other than splitting the functionality of `$id` into two keywords.

`"$id": "#/definitions/x/y"` is invalid according to the current spec. Ben pointed me to this fact on slack/general earlier today.

In draft07, $id's where allowed to consist of URI fragments with the exception of the toplevel $id.

> > There are tons and tons of schemas defining relative $id's like "#/definitions/x" and all of them are invalid according to the new specs.
> 
> Yes, there is a tool that generates `$id` in this way. We've told them it's wrong and they need to fix it, but it was never fixed and continues to cause confusion. _Those `$id`s have always been wrong in every draft past and current._

There are many tools - most code generation tools - who consider only type definitions specifying an $id as "exportable" or public (unless they are otherwise referenced). That's not an ideal solution, but it seems to be the dominant approach. It's not just one tool misbehaving, most of them do because they don't know how else to get stuff done.

But that aside, I understand that this feature is not attractive enough and don't have the energy to push it forth. Thanks for taking the time to discuss it in that depth.

**Comment by handrews** [comment]
Your URI example doesn't handle how the URI fragment is supposed to be constructed.  JSON Pointers are calculated relative to the base URI.  `http://x/my-schema/#current` has a base URI of `http://x/myschema/` so there's no way that `#current` is "remembered" in order to append pieces of JSON Pointers to it.

Furthermore, that's not how JSON Pointers work, and JSON Pointers are their own spec.

Plain name fragments (as a specific syntax) exist because the syntax is common across many media types, therefore something that might be represented in multiple media types can have the same fragment in all media types.  JSON Pointer fragments are not supported widely among media types.

> In draft07, $id's where allowed to consist of URI fragments with the exception of the toplevel $id.

**But they were never specified to do anything useful.**

> There are tons and tons of schemas defining relative $id's like "#/definitions/x" and all of them are invalid according to the new specs. 

They did not have defined behavior before, which in standards-ese means "don't do this."  It's common because many conditions are expensive to detect as errors so the exact behavior is left up to implementations.  You cannot rely on any specific behavior across implementations.

The fact that someone implemented them wrong does not make the wrong implementation right.  Nor does it make that behavior viable in the larger context of the spec.  You found an implementation that does what you wanted, but many others do not do that.  _Someone_ was going to end up broken.  What we did did not remove any correctly implemented functionality.

Draft-07 also [noted in a CREF](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3) that the scenario of non-plain-name fragments was not entirely specified and we did not yet know what to do with it.  We put that in to make it more clear that this area was under-specified and we were trying to figure out what to do with it.

And finally, `"$id": "#/definitions/x"` is not a valid 2019-09 `$id` anyway, so if they move to 2019-09 they will have to change the keyword anyway.  Changing the anchor to something like `definitions-x` would not be very difficult.

**Comment by mutech** [comment]
> Your URI example doesn't handle how the URI fragment is supposed to be constructed. JSON Pointers are calculated relative to the base URI. `http://x/my-schema/#current` has a base URI of `http://x/myschema/` so there's no way that `#current` is "remembered" in order to append pieces of JSON Pointers to it.

I really don't know what you are getting at. I never expected path resolution to happen for URI fragments. Not for my proposal, not for anything else. There is no URI resolution on fragments.

> Furthermore, that's not how JSON Pointers work, and JSON Pointers are their own spec.

What is not how JSON pointers work?

> > Plain name fragments (as a specific syntax) exist because the syntax is common across many media types, therefore something that might be represented in multiple media types can have the same fragment in all media types. JSON Pointer fragments are not supported widely among media types.

Ahm. Ok, but why then do you support JSON pointer fragments if you need to be compatible with HTML? I don't understand this argument.

> > In draft07, $id's where allowed to consist of URI fragments with the exception of the toplevel $id.
> 
> **But they were never specified to do anything useful.**

I am not sure if the people responsible for that part of the specification would agree with you on this.

> > There are tons and tons of schemas defining relative $id's like "#/definitions/x" and all of them are invalid according to the new specs.
> 
> They did not have defined behavior before, which in standards-ese means "don't do this." It's common because many conditions are expensive to detect as errors so the exact behavior is left up to implementations. You cannot rely on any specific behavior across implementations.

If a standard does not define the semantics of its constructs, you can hardly blame users or tools for how they interpret such degrees of freedom.

Most standards in the pre-living standards era got the issue of modularity right from version 1.0 and didn't need to lecture their users about compliance in version 9.

> And finally, `"$id": "#/definitions/x"` is not a valid 2019-09 `$id` anyway, so if they move to 2019-09 they will have to change the keyword anyway. Changing the anchor to something like `definitions-x` would not be very difficult.

Copy-and-pasting a meta model in order to add a property is also not difficult but you invented two new keywords to fix this issue and defined a semantics that is the most complex construct in the whole spec to support this use case.

You made a breaking change just for cosmetic reasons ($id/$anchor), you rename $defs just for cosmetic reasons with no substantial new functionality. I don't get your argument. But again, I get that you don't like the proposal, I closed it.

**Comment by handrews** [comment]
> I am not sure if the people responsible for that part of the specification would agree with you on this.

Dude.

I'm effectively the person responsible for that part of the specification.  Maybe consider not lecturing the specification authors on what their specification actually means?

**Comment by mutech** [comment]
> But they were never specified to do anything useful.

You did not specify [..] to do anything useful?

May I ask why you specified that such that it isn't doing anything useful Dude?

**Comment by mutech** [comment]
Or let's just close this chapter, we're only going to piss each other off. I don't want to contradict my gratitude for you doing this job by an overly emotional reaction to how you communicate or how I perceive this communication.

**Comment by Relequestual** [comment]
Every time we use SHOULD or MAY, what we're saying is: 99% of the time you do X, but there may be 1% of the time where you might have a valid reason for not doing X, and some we might not even know about right now, but let's at least not forbid it.

**Comment by mutech** [comment]
And that attitude makes perfect sense in some situations and not so much in others.

F.e., when you specify that URI's SHOULD be normalized, it makes sense. You want them normalized to reduce false negatives in comparisons, but you don't want to enforce it because that might do more damage if a non-normalized form is required in some situations.

Specifying something that doesn't do anything useful and then complaining that implementations do something useful that was not anticipated and is thus not compliant and abusive - that is not quite the same thing.

**Comment by handrews** [comment]
> Specifying something that doesn't do anything useful and then complaining that implementations do something useful that was not anticipated and is thus not compliant and abusive - that is not quite the same thing.

That is not how specifications work.  You don't get to implement something that's not specified and then complain when it gets contradicted.  That's like writing a browser that invents some random new tag, and then complaining if HTML adds a tag with the same name for a different purpose.  They didn't break compatibility, you just relied on something that wasn't guaranteed and that's your problem.

> May I ask why you specified that such that it isn't doing anything useful Dude?

Because spec writing is hard and we all stepped in to salvage an abandoned spec and have been putting tons of effort into seeing how it is actually used and making it a coherent thing.

That's why we put in CREFs noting that it was underspecified while we worked out what it really should do.

You don't like it.  You think things should be different.  You clearly have not done this sort of work, nor do you understand how specification language such as that explained by @Relequestual works.  You think it should work the way you want it to work.  You don't care that other people had different problems with the underspecified area, because you apparently don't consider perspectives other than your own.

I'll stop there.  Sorry @Relequestual, that's as nice as I'm willing to be to someone whose main goal seems to be to insult us because we won't dance the way the want us to.

**Comment by handrews** [comment]
> Ahm. Ok, but why then do you support JSON pointer fragments if you need to be compatible with HTML? I don't understand this argument.

Because JSON Pointer fragments and plain name fragments have different use cases.  We don't "need to be compatible with HTML."  We want to be a good citizen media type and offer a well-known path for compatibility with other possibly not-yet-designed media types that might be similar enough to be interoperable but different enough that a structured syntax such as JSON Pointer would not translate.  You could theoretically conceive of a format consisting of a flat set of schemas that are _only_ addressed by name.  JSON Schema and this format could interoperate via plain name fragments, but JSON Pointer fragments would be meaningless.

Idk why you would do that but that's not the point: the open nature of internet standards is all about allowing future things that you couldn't have guessed at the time.  That's why we (for example) use URIs and respect their rules instead of coming up with the most efficiently elegant identifiers for our own purposes.  Using URIs means we interoperate with everything else.  Using plain name fragments means interoperability is possible if someone finds a need for it.  Using JSON Pointer is useful because many times you don't need interoperability and there's no need to force people to name everything when the location will do just fine.

> If a standard does not define the semantics of its constructs, you can hardly blame users or tools for how they interpret such degrees of freedom.

Actually, yes we can.  These are I-Ds, internet drafts.  That has a [very specific meaning](https://en.wikipedia.org/wiki/Internet_Draft) about what can and cannot be relied upon.  JSON Schema is unusual in that it was largely abandoned after draft-04 due to arguments that the team at that time was unable to resolve.  But it became a de-facto standard despite those problems, which were only finally mostly resolved in 2019-09, because they were deeply difficult problems.  But the guidelines on what can and cannot be relied upon are quite clear, and you are quite wrong.

And even in full RFCs this is the case.  HTTP does not define semantics for `GET` and `DELETE` message bodies, which some people (ahem, ElasticSearch) try to exploit that gap and then get angry when intermediaries drop the body, or libraries don't make it available, or whatever.  They are wrong and the intermediaries/libraries/etc. are right.

> Most standards in the pre-living standards era got the issue of modularity right from version 1.0 and didn't need to lecture their users about compliance in version 9.

Most people attempting to get changes made don't drip condescending scorn at unpaid volunteers who have spent years trying to get a spec from a place with lots of unfinished areas and inconsistencies to a place of consistent principles and predictable behavior.  Particularly when they demonstrably do not understand what is involved in such work, or what the conventions are, or what the responsibilities of the spec vs implementations are, or what it's like to balance competing demands across a large deployed user base.

Also, JSON Schema is not a "living standard" it is an internet draft series.

> Copy-and-pasting a meta model in order to add a property is also not difficult but you invented two new keywords to fix this issue and defined a semantics that is the most complex construct in the whole spec to support this use case.

That really bugs you, doesn't it?  Have you ever maintained a large system with lots of references but also lots of duplication?  Sounds like you have not.  Let me know when you've been called in to rescue a product that copy-pasted tons of stuff and no longer works and no one understands why.  Your cost-benefit analysis is currently somewhat lacking.

> You made a breaking change just for cosmetic reasons ($id/$anchor)

If you think that was cosmetic you don't understand the implementation and maintainability problems that it caused at all, which goes with your general disregard for the perspectives of others.  Have you implemented JSON Schema yourself?  Do you understand the challenge of handling things the way they were?  Does the fact that you found yourself relying on an incorrect implementation not tell you something about the problems with the old way of doing things?

I guess not, because in your view all of the error lies with us no matter what.  Whatever you were doing is right, whatever we learned from surveying the community more broadly and trying to implement things ourselves is wrong.  We had lots of complaints about `$id`.  I decided to implement `$id` to show that it wasn't that hard.  It turned out to be a mess.  We discussed it and fixed the mess in a way that is fully backwards compatible _whether you believe us or not,_ and produced a much easier implementation requirement.

> you rename $defs just for cosmetic reasons with no substantial new functionality.

No, that was about consolidating the core specification to provide a mandatory minimal set of functionality that is clearly visible in usage.  An extensible system is not usable without reserving a location for referenceable schemas.  Without that, you get exactly the problem you're complaining about:  people make assumptions about where they can safely put them, and then complain when their assumptions are wrong.

So in this thread you are both complaining that we changed something that went against actual invalid assumptions, **and** you are complaining that we made a change to ensure that no one went further with unreliable assumptions.

**Comment by mutech** [comment]
> > Ahm. Ok, but why then do you support JSON pointer fragments if you need to be compatible with HTML? I don't understand this argument.
> 
> Because JSON Pointer fragments and plain name fragments have different use cases. We don't "need to be compatible with HTML." We want to be a good citizen media type and offer a well-known path for compatibility with other possibly not-yet-designed media types that might be similar enough to be interoperable but different enough that a structured syntax such as JSON Pointer would not translate. You could theoretically conceive of a format consisting of a flat set of schemas that are _only_ addressed by name. JSON Schema and this format could interoperate via plain name fragments, but JSON Pointer fragments would be meaningless.

That is a valid point. But still this argument falls short, because you support **both** anchors and pointers and because you already departed from a consistent view of your document as either hierarchy or dictionary (what anchors represent on an abstract level) there is no additional pollution to embrace the existence of two parallel views on your documents structure and support addressing both.

That is not a necessity, but it would not diminish your status as good citizen, not after you already added the fuzziness of two orthogonal document content addressing schemes.

There is also no issue with interoperability with similiar document types. Both JSON pointer and flat fragments are still valid and especially because '/' is not a valid anchor character, there are no conflicts, because you actually specified this well (in this case not allowing too much freedom in your spec).

> Idk why you would do that but that's not the point: the open nature of internet standards is all about allowing future things that you couldn't have guessed at the time.

Well your attitude is that if implementation use features that you did not especially specify for a certain purpose, such as the use of `$id` as mentioned above, that this is basically abusive and not specification conform. It's a bit ironic that you now encourage the use of specification in such a liberal way. Which is it?

> That's why we (for example) use URIs and respect their rules instead of coming up with the most efficiently elegant identifiers for our own purposes. Using URIs means we interoperate with everything else. Using plain name fragments means interoperability is possible if someone finds a need for it. Using JSON Pointer is useful because many times you don't need interoperability and there's no need to force people to name everything when the location will do just fine.

URI fragments are the domain of content types. The URI specification does not define what the meaning of a fragment is, it only specifies it's syntax and how it participates in URI resolution - not at all (except that fragments of resolved URIs override those of base URIs). Can you please stop accusing me of wanting to violate URI resolution specification? I start taking this personal.

Using JSON pointer as a semantics for URI fragments is not having any impact on interoperability of anything, because fragments have no innate semantics across content types. Can you please read up the relevant parts of the URI specs again? Whether you want to support this or that semantic for fragments applied to URIs addressing JSON schema documents is the sole domain of the JSON schema specification. And of course it would be strange if you would support XML Query as addressing scheme, but that would just be stupid but not an interoperability or conformance issue.

> > If a standard does not define the semantics of its constructs, you can hardly blame users or tools for how they interpret such degrees of freedom.
> 
> Actually, yes we can. These are I-Ds, internet drafts. That has a [very specific meaning](https://en.wikipedia.org/wiki/Internet_Draft) about what can and cannot be relied upon. JSON Schema is unusual in that it was largely abandoned after draft-04 due to arguments that the team at that time was unable to resolve. But it became a de-facto standard despite those problems, which were only finally mostly resolved in 2019-09, because they were deeply difficult problems. But the guidelines on what can and cannot be relied upon are quite clear, and you are quite wrong.

JSON schema became more popular mostly because of swagger and that is the thing that's really ironic. People start using a tool that was intended as validation mechanism for code generation, much the same way as XML schema was used for different purposes than just validation. And because JSON schema is not optimized for code generation, a lot of tools work around limitations and this is the point where we stand.

You are doing an excellent job by focussing on vocabularies, this is a good strategy. But until there actually are vocabularies with tool support, people have to continue using the validation parts of the spec and the work in progress in core to get their work done. You are hard pressed to catch up with demands and tool implementers are hard pressed to use a spec that just doesn't serve their needs.

What annoys me is the way how you come up with artificial arguments (that at least in my understanding are not even formally valid) to suppress a request instead of just either present valid arguments against it or just say that this is not valuable enough. I had no issues with either, but I really can't take it anymore that you say my suggestion would conflict with URI resolution or would introduce inoperability issues or unclean design.

> And even in full RFCs this is the case. HTTP does not define semantics for `GET` and `DELETE` message bodies, which some people (ahem, ElasticSearch) try to exploit that gap and then get angry when intermediaries drop the body, or libraries don't make it available, or whatever. They are wrong and the intermediaries/libraries/etc. are right.

My god, we are talking about `$id`s. They are used to identify things. Two things, schema documents (at the toplevel) and schema nodes (anywhere else) - both documents and nodes being schema objects. The sole purpose of ids is to reference them. Either from other schema nodes or from interested parties (code/documentation/service generators, validations or whatever) who want to access this information.

In the most general case, all parties interested in accessing a schema object want the most persistent and stable link, because whenever the target changes, you generate a miriad of change activities. That is why I like `#anchor`, because that provides a means to define a contract between a schema author and clients. The same kind of contract as an API that exposes a named feature.

JSON pointers are good for internal referencing but not really good when it comes to exposing features, because they expose implementation details - the absolute position of a schema object in a document.

JSON pointers relative to an anchor are not as bad, because they reference a sub-feature (f.e. the property (type) of an object type). That is not an implementation detail such as a location.

What I propose is not to abuse an obscure feature, it's actually a clean well defined addressing scheme that allows schema authors and consumers to define contracts for accessing schema objects (-> types).

I really don't see how what I propose is in any way conflicting with your standardization ethics, URI resolution or again interoperability. I want to enable schema authors and schema users to interoperate in well defined manner.

As a side note: I really cannot understand why you did not specify the pair of `schemaId` and `schemaLocation` to give schema authors, schema users and tool makers at least a chance to actually use modular and composable schemas. the absence of any mechanism to locate schema, especially considering the strong support for embedded schema as another level of obstruction and information hiding (in the unfriendly sense) is really a major defect in your specs. That has much more impact than the length of `definitions` vs. `$defs`. If you are worried about interoperability of JSON schema with other unrelated document types, a worry that has no practical impact because there is and will most likely never be an interoperation between other media types, why are you not worried about how your users interoperated with other users of your spec? Should that not be the main concern of a specification? 

> > Most standards in the pre-living standards era got the issue of modularity right from version 1.0 and didn't need to lecture their users about compliance in version 9.

> Most people attempting to get changes made don't drip condescending scorn at unpaid volunteers who have spent years trying to get a spec from a place with lots of unfinished areas and inconsistencies to a place of consistent principles and predictable behavior.

My condescension is not related to your work or your salary. However, I don't like being patronized and just because you are a member of a standardization project does not automatically mean that each of your opinions are more valuable or competent than that of a noname guy writing issues. You take the liberty you get pretty personal and I'm not in a state where moderation and patience are my most valued states of mind. That's not the right place to have this kind of discussion, but I offered two times to stop this conversation. I will not back off and accept your in my understanding invalid arguments just for the sake of politeness.

> Particularly when they demonstrably do not understand what is involved in such work, or what the conventions are, or what the responsibilities of the spec vs implementations are, or what it's like to balance competing demands across a large deployed user base.

My issue is pretty personal. I understand that conflicting demands can at best end in compromises and most often that means that you don't get what you want, I mean I don't get what I want in this case. I don't have an issue with the fact that conflicting demands need to be balanced, I have an issue with how you do that.

Concretely, you say that my proposal has a negative impact on interoperability and that it violates URI resolution concepts (I leave out the bunch of other comments that heated up my mood). I tried hard to answer objectively to these statements and did not see my answers being processed and rebuked or accepted. Instead you play the `I'm the professional board member and know it better` card. That is not the kind of attitude that results in better specifications and consequently better technologies for all of us to use. 

> > Copy-and-pasting a meta model in order to add a property is also not difficult but you invented two new keywords to fix this issue and defined a semantics that is the most complex construct in the whole spec to support this use case.
> 
> That really bugs you, doesn't it? Have you ever maintained a large system with lots of references but also lots of duplication? Sounds like you have not. Let me know when you've been called in to rescue a product that copy-pasted tons of stuff and no longer works and no one understands why. Your cost-benefit analysis is currently somewhat lacking.

It does not bug me that you introduced that feature. It's probably a good thing. What bugs me is that you spend so much effort to introduce such a complex feature and do not spend enough effort for basic problems in the specification.

What makes this annoying is that if you compare how many working hours are invested in schema vocabularies and how many people work on defining their data models with JSON schema and fail on the most basic and fundamental tasks, then I feel that you just don't focus on the more important task.

I worked for decades with really complex systems, much more complex than a data model for a vocabulary. If I wouldn't have this experience, I wouldn't use schemas to define data models. I wouldn't use code generators with the intention to generate compiler errors when models change instead of trusting a test team to find issues later on.

My starting point why I am interested in JSON schema is because I need to write my own tools to fulfil a use case - a trivial use case - because existing tools just don't get the job done. And the reason for that is mostly because these tools can't keep up with changes in JSON schema, because JSON schema does not specify means to let these tools interoperate and a lot of stuff JSON schema does specify is too complex, too loosely specified or too irrelevant for authors of these tools to respect the specs. These tool authors are also working for free on open source. And they deserve your respect just as much as you deserve theirs or mine. But the impact of your job and how you do it has much more impact on them than the other way round. Maybe you should consider looking at your work from their perspective every now and then. You might also want to read some of the dinosaur specs of your predecessor XSD to see how other people solved your problems. Some solutions have been proven successful in the past, I worked for decades with them and it really makes a difference.

> So in this thread you are both complaining that we changed something that went against actual invalid assumptions, **and** you are complaining that we made a change to ensure that no one went further with unreliable assumptions.

No, I am not complaining that you changed the spec. I actually cheer you on, I totally agree with your $id/$anchor change, I prefer $defs, once I understand the recursive refs and their implications I will probably also agree with them.

What I complain about is that if you apply your own arguments to the changes you made, you should not have made them. You are worried with interoperability issues with hypothetical actors and ignore the concrete problems your users have with the lack of interoperability. Many JSON schema processors do not implement any mechanism to resolve external entities. Every XML, XSD, XQuery, XSLT processor, every single one I ever used (that's probably all of them) had no issue at all with external entities and they are not dead because they could resolve external entities.

Embedding schemas in schemas is important (and thus creates some of the issues with $id's) *because* there is no defined resolution mechanism. Don't you see the irony of your argument?

The chaos in the JSON schema tool landscape is caused by the lack of guidance by the specs, at least in part.

I'm tired of holding back my horses. I'm offering again to just stop here. You have a talent to push my buttons, let's keep that closed and just work on our stuff, that's probably really more productive.

**Comment by handrews** [comment]
@Relequestual why are we tolerating this level of abuse from someone who doesn't understand how any of this works at all?

@mutech nearly everything you say is wrong in some way.  You claim our arguments aren't valid but really you're just asserting that.  As if somehow you know everything about JSON Schema and we are just deluded fools.  Do you even know what our current relationship with the OpenAPI project is?

>  ignore the concrete problems your users have with the lack of interoperability. 

No, we put tons of effort in, it just happens that the majority of concern doesn't align with you.

> I will not back off and accept your in my understanding invalid arguments just for the sake of politeness.

Then we're going to be here for a long time because you profoundly fail to understand what's going on here.  You've decided you want to pick fights.  Your opening issue was hostile, you've been hostile the whole time.  You didn't "offer to stop" you just wanted to end with your own insults as the last word.
